import type { UuidFormat, UuidOutputStyle, UuidPreset, UuidVersion } from "./types";

export const UUID_PRESETS: UuidPreset[] = [
  {
    id: "api-fixtures",
    name: "API fixtures",
    description: "Ten random UUID v4 values in a JSON array for mocks and tests.",
    version: "v4",
    count: 10,
    format: "standard",
    outputStyle: "json",
  },
  {
    id: "database-v7",
    name: "Database keys",
    description: "Time-ordered UUID v7 values for index-friendly application records.",
    version: "v7",
    count: 25,
    format: "standard",
    outputStyle: "lines",
  },
  {
    id: "csv-seed",
    name: "CSV seed batch",
    description: "Fifty UUID v4 values with a CSV header for seed data imports.",
    version: "v4",
    count: 50,
    format: "standard",
    outputStyle: "csv",
  },
  {
    id: "compact-ids",
    name: "Compact IDs",
    description: "Hyphen-free UUID v4 values for systems that require 32 hex digits.",
    version: "v4",
    count: 10,
    format: "no-hyphens",
    outputStyle: "lines",
  },
  {
    id: "urn-values",
    name: "UUID URNs",
    description: "Standards-style urn:uuid values for identifiers in documents and metadata.",
    version: "v4",
    count: 5,
    format: "urn",
    outputStyle: "lines",
  },
  {
    id: "uppercase-legacy",
    name: "Legacy uppercase",
    description: "Uppercase UUID v4 values for legacy exports and case-sensitive fixtures.",
    version: "v4",
    count: 10,
    format: "uppercase",
    outputStyle: "json",
  },
  {
    id: "single-api-id",
    name: "Single API ID",
    description: "Generate one canonical UUID v4 for an API request or manual fixture.",
    version: "v4",
    count: 1,
    format: "standard",
    outputStyle: "lines",
  },
  {
    id: "event-stream-v7",
    name: "Event stream IDs",
    description: "Generate time-ordered UUID v7 values for append-heavy event data.",
    version: "v7",
    count: 100,
    format: "standard",
    outputStyle: "lines",
  },
  {
    id: "json-mock-data",
    name: "JSON mock data",
    description: "Generate 20 v4 IDs as a JSON array for frontend fixtures.",
    version: "v4",
    count: 20,
    format: "standard",
    outputStyle: "json",
  },
  {
    id: "csv-import-v7",
    name: "CSV import keys",
    description: "Create sortable v7 identifiers for spreadsheet or database imports.",
    version: "v7",
    count: 50,
    format: "standard",
    outputStyle: "csv",
  },
  {
    id: "braced-guid",
    name: "Braced GUID style",
    description: "Generate brace-wrapped UUID values for legacy integrations.",
    version: "v4",
    count: 10,
    format: "braces",
    outputStyle: "lines",
  },
  {
    id: "compact-bulk",
    name: "Compact bulk IDs",
    description: "Generate 100 hyphen-free UUIDs for systems with compact identifier fields.",
    version: "v4",
    count: 100,
    format: "no-hyphens",
    outputStyle: "lines",
  },
  {
    id: "urn-metadata",
    name: "Metadata URNs",
    description: "Generate 25 urn:uuid identifiers for XML, RDF, or document metadata.",
    version: "v4",
    count: 25,
    format: "urn",
    outputStyle: "lines",
  },
  {
    id: "uppercase-csv",
    name: "Uppercase CSV export",
    description: "Create uppercase IDs in CSV format for older enterprise imports.",
    version: "v4",
    count: 25,
    format: "uppercase",
    outputStyle: "csv",
  },
  {
    id: "sortable-json-v7",
    name: "Sortable JSON IDs",
    description: "Generate 25 v7 values in JSON for APIs that benefit from time ordering.",
    version: "v7",
    count: 25,
    format: "standard",
    outputStyle: "json",
  },
  {
    id: "small-test-batch",
    name: "Small test batch",
    description: "Generate five canonical UUIDs for unit tests and snapshots.",
    version: "v4",
    count: 5,
    format: "standard",
    outputStyle: "lines",
  },

];

export const VERSION_OPTIONS: Array<{ label: string; value: UuidVersion; description: string }> = [
  { label: "UUID v4", value: "v4", description: "Random identifiers with 122 random bits." },
  { label: "UUID v7", value: "v7", description: "Unix-millisecond prefix with secure random data." },
];

export const FORMAT_OPTIONS: Array<{ label: string; value: UuidFormat; description: string }> = [
  { label: "Standard lowercase", value: "standard", description: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" },
  { label: "Uppercase", value: "uppercase", description: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" },
  { label: "Without hyphens", value: "no-hyphens", description: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" },
  { label: "URN prefix", value: "urn", description: "urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" },
  { label: "Braces", value: "braces", description: "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" },
];

export const OUTPUT_STYLE_OPTIONS: Array<{ label: string; value: UuidOutputStyle }> = [
  { label: "Plain lines", value: "lines" },
  { label: "JSON array", value: "json" },
  { label: "CSV", value: "csv" },
];

export const DEFAULT_UUID_PRESET = UUID_PRESETS[0];
