import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, GitCompareArrows, ShieldCheck } from "lucide-react";
import { AtlasHeroScene, MotionSection, SplitTextReveal } from "@/components/motion";
import { Badge, Card } from "@/components/ui";
import { EditorialCard, getEditorialPagesByKind } from "@/features/editorial";
import { absoluteUrl } from "@/features/tools/seo";

export const metadata: Metadata = {
  title: "Technology Comparisons — choose roles, frameworks, and workflows | Darma",
  description: "Compare frontend and backend roles, React and Vue and Angular, React Native and Flutter, design roles, product and project management, DevOps and SRE, developer levels, and delivery methods.",
  keywords: ["technology comparisons", "React vs Vue vs Angular", "DevOps vs SRE", "frontend vs backend", "Agile vs Scrum vs Kanban"],
  alternates: { canonical: "/comparisons" },
  openGraph: { title: "Darma Technology Comparisons", description: "Side-by-side technology decisions with practical criteria, primary references, and connected next steps.", url: absoluteUrl("/comparisons"), type: "website" },
};

export default function ComparisonsPage() {
  const comparisons = getEditorialPagesByKind("comparison");
  const jsonLd = { "@context": "https://schema.org", "@type": "CollectionPage", name: "Darma Technology Comparisons", description: metadata.description, url: absoluteUrl("/comparisons"), mainEntity: { "@type": "ItemList", numberOfItems: comparisons.length, itemListElement: comparisons.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.title, url: absoluteUrl(`/comparisons/${item.slug}`) })) } };
  return <div className="pb-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <section className="visual-grid-bg border-b border-[var(--color-border-subtle)]"><div className="mx-auto grid max-w-[var(--container-wide)] gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[minmax(0,1fr)_minmax(390px,.84fr)] lg:items-center lg:px-8 lg:py-20"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><Badge variant="soft">Decision library</Badge><Badge variant="outline">{comparisons.length} reviewed comparisons</Badge></div><SplitTextReveal text="Compare technology choices without searching through marketing claims." className="mt-5 text-4xl font-black tracking-[-0.055em] text-[var(--color-text-primary)] sm:text-5xl lg:text-7xl" /><p className="mt-6 max-w-3xl text-base leading-8 text-[var(--color-text-secondary)] sm:text-lg">See what changes in daily work, architecture, team fit, risk, learning effort, and long-term maintenance before choosing a role, framework, or process.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#comparison-library" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[var(--color-primary)] px-6 text-sm font-black text-[var(--color-primary-text)] shadow-[var(--shadow-md)]">Browse comparisons <ArrowRight className="h-4 w-4" aria-hidden /></a><Link href="/guides" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-raised)] px-6 text-sm font-black text-[var(--color-text-primary)]">Open practical guides</Link></div></div><AtlasHeroScene src="/atlas/decision-map.svg" alt="A decision map comparing two options based on context, trade-offs, tests, and learning" priority labels={[`${comparisons.length} comparisons`, "Decision frameworks", "Real constraints", "No universal winner"]} /></div></section>
    <MotionSection as="section" className="mx-auto max-w-[var(--container-page)] px-4 py-10 sm:px-6 lg:px-8" distance={18}><Card padding="lg" className="grid gap-6 border-[var(--color-primary-border)] lg:grid-cols-[auto_1fr_auto] lg:items-center"><span className="atlas-symbol"><GitCompareArrows className="h-5 w-5" aria-hidden /></span><div><h2 className="text-xl font-black text-[var(--color-text-primary)]">No universal winners</h2><p className="mt-2 text-sm leading-7 text-[var(--color-text-secondary)]">Every comparison begins with team skills, product needs, risk, environment, and the work you actually want to do.</p></div><Link href="/editorial-policy" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[var(--color-border-default)] px-4 text-sm font-black text-[var(--color-primary)]"><ShieldCheck className="h-4 w-4" aria-hidden />Review method</Link></Card></MotionSection>
    <section id="comparison-library" className="mx-auto max-w-[var(--container-wide)] scroll-mt-28 px-4 sm:px-6 lg:px-8"><div className="mb-7 max-w-3xl"><p className="font-mono text-[10px] font-black uppercase tracking-[0.16em] text-[var(--color-primary)]">Comparison library</p><h2 className="mt-2 text-3xl font-black tracking-[-0.04em] text-[var(--color-text-primary)]">Start with the decision you are trying to make.</h2></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{comparisons.map((item, index) => <MotionSection key={item.slug} delay={(index % 3) * .05} distance={18}><EditorialCard page={item} /></MotionSection>)}</div></section>
  </div>;
}
