import type { ButtonGeneratorConfig, ButtonPreset } from "./types";

export const defaultButtonConfig: ButtonGeneratorConfig = {
  style: "solid",
  shape: "rounded",
  contentMode: "text-icon",
  loading: false,
  className: "darma-button",
  text: "Get started",
  fontSize: 16,
  fontWeight: 700,
  lineHeight: 1.25,
  letterSpacing: 0,
  radius: 14,
  paddingX: 22,
  paddingY: 12,
  minWidth: 0,
  background: "#4f46e5",
  background2: "#ec4899",
  gradientAngle: 135,
  textColor: "#ffffff",
  borderEnabled: false,
  borderWidth: 1,
  borderStyle: "solid",
  borderColor: "#4f46e5",
  shadowEnabled: true,
  shadowX: 0,
  shadowY: 8,
  shadowBlur: 18,
  shadowSpread: 0,
  shadowColor: "#4f46e5",
  shadowOpacity: 0.24,
  shadowInset: false,
  hoverEffect: "lift",
  motionDuration: 180,
  motionEasing: "ease-out",
  customizeHoverState: false,
  hoverBackground: "#4338ca",
  hoverTextColor: "#ffffff",
  hoverBorderColor: "#4338ca",
  hoverTranslateY: -2,
  hoverScale: 1,
  hoverShadowY: 10,
  hoverShadowBlur: 28,
  customizeActiveState: false,
  activeBackground: "#3730a3",
  activeTextColor: "#ffffff",
  activeBorderColor: "#3730a3",
  activeTranslateY: 1,
  activeScale: 0.99,
  activeEffect: true,
  disabled: false,
  disabledOpacity: 0.55,
  iconPosition: "right",
  iconSymbol: "→",
  uppercase: false,
  fullWidth: false,
  mobileFullWidth: false,
  includeFocusRing: true,
  focusRingColor: "#7c83f3",
  focusRingWidth: 3,
  focusRingOffset: 3,
  includeReducedMotion: true,
  customCss: "",
};

function config(overrides: Partial<ButtonGeneratorConfig>): ButtonGeneratorConfig {
  return { ...defaultButtonConfig, ...overrides };
}

export const buttonPresets: ButtonPreset[] = [
  {
    id: "primary-lift",
    name: "Primary lift",
    description: "Clean primary action with subtle depth and motion.",
    category: "popular",
    tags: ["primary", "cta", "modern"],
    featured: true,
    cssOnly: true,
    recommendedBackground: "light",
    config: config({}),
  },
  {
    id: "dark-cta",
    name: "Dark CTA",
    description: "High-contrast black action for editorial and product UI.",
    category: "cta",
    tags: ["dark", "cta", "minimal"],
    featured: true,
    cssOnly: true,
    config: config({ background: "#111827", borderColor: "#111827", shadowColor: "#111827", text: "Start building", iconSymbol: "↗", radius: 12 }),
  },
  {
    id: "outline-clean",
    name: "Clean outline",
    description: "Quiet supporting action with a crisp border.",
    category: "minimal",
    tags: ["outline", "secondary", "clean"],
    cssOnly: true,
    config: config({ style: "outline", contentMode: "text", text: "Learn more", background: "#ffffff", textColor: "#111827", borderEnabled: true, borderColor: "#d1d5db", shadowEnabled: false, hoverEffect: "darken" }),
  },
  {
    id: "ghost-minimal",
    name: "Minimal ghost",
    description: "Text-first control for compact interfaces and toolbars.",
    category: "minimal",
    tags: ["ghost", "minimal", "toolbar"],
    cssOnly: true,
    config: config({ style: "ghost", contentMode: "text", text: "View details", textColor: "#334155", paddingX: 12, shadowEnabled: false, borderEnabled: false, hoverEffect: "darken" }),
  },
  {
    id: "pill-indigo",
    name: "Indigo pill",
    description: "Rounded CTA with a compact, friendly silhouette.",
    category: "popular",
    tags: ["pill", "rounded", "cta"],
    cssOnly: true,
    config: config({ shape: "pill", text: "Join free", iconSymbol: "+", paddingX: 24 }),
  },
  {
    id: "aurora-gradient",
    name: "Aurora gradient",
    description: "Vibrant two-color CTA with glow on hover.",
    category: "gradient",
    tags: ["gradient", "marketing", "glow"],
    featured: true,
    cssOnly: true,
    recommendedBackground: "light",
    config: config({ style: "gradient", shape: "pill", text: "Start free", background: "#0e7490", background2: "#7c3aed", gradientAngle: 135, borderEnabled: false, shadowColor: "#7c3aed", shadowBlur: 24, shadowOpacity: 0.32, hoverEffect: "glow" }),
  },
  {
    id: "sunset-gradient",
    name: "Sunset gradient",
    description: "Warm conversion CTA with a bold color transition.",
    category: "gradient",
    tags: ["gradient", "warm", "cta"],
    cssOnly: true,
    config: config({ style: "gradient", text: "Create account", background: "#c2410c", background2: "#be185d", gradientAngle: 110, borderEnabled: false, shadowColor: "#f97316", hoverEffect: "lift" }),
  },
  {
    id: "ocean-gradient",
    name: "Ocean gradient",
    description: "Cool blue gradient with balanced depth.",
    category: "gradient",
    tags: ["gradient", "blue", "modern"],
    cssOnly: true,
    config: config({ style: "gradient", text: "Explore now", background: "#0369a1", background2: "#0f766e", gradientAngle: 135, borderEnabled: false, shadowColor: "#0284c7", hoverEffect: "scale" }),
  },
  {
    id: "purple-glow",
    name: "Purple glow",
    description: "Rich violet CTA with expressive glow feedback.",
    category: "animated",
    tags: ["glow", "purple", "animated"],
    cssOnly: true,
    recommendedBackground: "dark",
    config: config({ background: "#7c3aed", borderColor: "#7c3aed", shadowColor: "#8b5cf6", shadowBlur: 28, shadowOpacity: 0.4, hoverEffect: "glow", text: "Launch app", iconSymbol: "↗" }),
  },
  {
    id: "glass-frost",
    name: "Frosted glass",
    description: "Translucent action designed for colorful surfaces.",
    category: "glass",
    tags: ["glass", "frosted", "overlay"],
    featured: true,
    cssOnly: true,
    recommendedBackground: "gradient",
    config: config({ style: "glass", text: "Open menu", textColor: "#ffffff", background: "#ffffff", background2: "#60a5fa", borderEnabled: true, borderColor: "#ffffff", shadowColor: "#0f172a", shadowOpacity: 0.18, hoverEffect: "lift" }),
  },
  {
    id: "glass-dark",
    name: "Dark glass",
    description: "Dark translucent button for immersive product surfaces.",
    category: "glass",
    tags: ["glass", "dark", "overlay"],
    cssOnly: true,
    recommendedBackground: "gradient",
    config: config({ style: "glass", text: "View project", background: "#111827", background2: "#8b5cf6", textColor: "#ffffff", borderEnabled: true, borderColor: "#c4b5fd", shadowColor: "#111827", shadowOpacity: 0.28, hoverEffect: "glow" }),
  },
  {
    id: "soft-neumorphic",
    name: "Soft neumorphic",
    description: "Soft raised control with restrained tactile depth.",
    category: "popular",
    tags: ["neumorphic", "soft", "raised"],
    cssOnly: true,
    config: config({ style: "neumorphic", contentMode: "text", text: "Continue", background: "#e5e7eb", textColor: "#111827", borderEnabled: false, shadowColor: "#64748b", shadowOpacity: 0.18, shadowBlur: 22, hoverEffect: "scale" }),
  },
  {
    id: "press-3d",
    name: "3D press",
    description: "Tactile raised button with a satisfying pressed state.",
    category: "3d",
    tags: ["3d", "press", "tactile"],
    featured: true,
    cssOnly: true,
    config: config({ style: "three-d", text: "Play now", background: "#2563eb", borderEnabled: false, shadowEnabled: true, shadowY: 7, shadowBlur: 22, shadowColor: "#1e3a8a", shadowOpacity: 0.32, hoverEffect: "lift" }),
  },
  {
    id: "chunky-3d",
    name: "Chunky 3D",
    description: "Bold playful control for games and expressive landing pages.",
    category: "3d",
    tags: ["3d", "playful", "bold"],
    cssOnly: true,
    config: config({ style: "three-d", shape: "rounded", text: "Let’s go", background: "#facc15", textColor: "#422006", borderEnabled: true, borderWidth: 2, borderColor: "#422006", shadowColor: "#422006", shadowOpacity: 0.5, fontWeight: 900, uppercase: true, hoverEffect: "scale" }),
  },
  {
    id: "brutalist",
    name: "Brutalist",
    description: "Hard edges, thick border, and offset shadow.",
    category: "3d",
    tags: ["brutalist", "bold", "square"],
    cssOnly: true,
    config: config({ shape: "square", contentMode: "text", text: "SUBMIT", background: "#fef08a", textColor: "#111827", borderEnabled: true, borderWidth: 3, borderColor: "#111827", shadowEnabled: true, shadowX: 6, shadowY: 6, shadowBlur: 0, shadowSpread: 0, shadowColor: "#111827", shadowOpacity: 1, uppercase: true, fontWeight: 900, hoverEffect: "slide" }),
  },
  {
    id: "retro-red",
    name: "Retro red",
    description: "Punchy retro action with compact uppercase typography.",
    category: "3d",
    tags: ["retro", "red", "bold"],
    cssOnly: true,
    config: config({ shape: "rounded", contentMode: "text", text: "INSERT COIN", background: "#dc2626", textColor: "#fff7ed", borderEnabled: true, borderWidth: 2, borderColor: "#7f1d1d", shadowX: 0, shadowY: 5, shadowBlur: 0, shadowColor: "#7f1d1d", shadowOpacity: 1, uppercase: true, letterSpacing: 1.2, hoverEffect: "darken" }),
  },
  {
    id: "neon-cyan",
    name: "Neon cyan",
    description: "Cyber-style outline with luminous hover feedback.",
    category: "animated",
    tags: ["neon", "cyan", "glow"],
    cssOnly: true,
    recommendedBackground: "dark",
    config: config({ style: "outline", contentMode: "text", text: "Connect", background: "#0f172a", textColor: "#67e8f9", borderEnabled: true, borderWidth: 1, borderColor: "#22d3ee", shadowEnabled: true, shadowY: 0, shadowBlur: 18, shadowColor: "#22d3ee", shadowOpacity: 0.45, hoverEffect: "glow" }),
  },
  {
    id: "shine-cta",
    name: "Shine CTA",
    description: "Glossy sweep animation for high-emphasis conversion actions.",
    category: "animated",
    tags: ["shine", "cta", "animated"],
    cssOnly: true,
    config: config({ text: "Upgrade now", background: "#111827", borderColor: "#111827", shadowColor: "#111827", hoverEffect: "shine" }),
  },
  {
    id: "fill-outline",
    name: "Fill outline",
    description: "Outline button that fills on hover while keeping readable contrast.",
    category: "animated",
    tags: ["fill", "outline", "animated"],
    cssOnly: true,
    config: config({ style: "outline", contentMode: "text", text: "Discover", background: "#2563eb", textColor: "#2563eb", borderEnabled: true, borderColor: "#2563eb", shadowEnabled: false, hoverEffect: "fill" }),
  },
  {
    id: "pulse-ring",
    name: "Pulse ring",
    description: "Soft halo feedback for primary actions that need extra emphasis.",
    category: "animated",
    tags: ["pulse", "ring", "animated"],
    cssOnly: true,
    config: config({ text: "Notify me", background: "#2563eb", borderColor: "#2563eb", shadowColor: "#2563eb", shadowOpacity: 0.18, hoverEffect: "pulse" }),
  },
  {
    id: "bounce-playful",
    name: "Playful bounce",
    description: "Expressive lift-and-scale feedback for friendly product moments.",
    category: "animated",
    tags: ["bounce", "playful", "motion"],
    cssOnly: true,
    config: config({ text: "Try it", iconSymbol: "↗", background: "#db2777", borderColor: "#db2777", shadowColor: "#db2777", hoverEffect: "bounce", motionDuration: 220 }),
  },
  {
    id: "soft-slate",
    name: "Soft slate",
    description: "Low-noise action for product dashboards and settings.",
    category: "minimal",
    tags: ["soft", "dashboard", "minimal"],
    cssOnly: true,
    config: config({ contentMode: "text", text: "Save changes", background: "#f1f5f9", textColor: "#0f172a", borderEnabled: true, borderColor: "#e2e8f0", shadowEnabled: false, hoverEffect: "darken" }),
  },
  {
    id: "white-on-dark",
    name: "White minimal",
    description: "Simple light action designed for dark surfaces.",
    category: "minimal",
    tags: ["white", "minimal", "dark"],
    cssOnly: true,
    recommendedBackground: "dark",
    config: config({ contentMode: "text", text: "Continue", background: "#ffffff", textColor: "#111827", borderEnabled: false, shadowColor: "#000000", shadowOpacity: 0.22, hoverEffect: "scale" }),
  },
  {
    id: "danger",
    name: "Danger action",
    description: "Clear destructive control for irreversible actions.",
    category: "cta",
    tags: ["danger", "destructive", "red"],
    cssOnly: true,
    config: config({ contentMode: "text", text: "Delete project", background: "#dc2626", borderColor: "#dc2626", shadowColor: "#dc2626", hoverEffect: "darken" }),
  },
  {
    id: "success",
    name: "Success action",
    description: "Positive confirmation button with calm green feedback.",
    category: "cta",
    tags: ["success", "green", "confirmation"],
    cssOnly: true,
    config: config({ text: "Confirm", iconSymbol: "✓", iconPosition: "left", background: "#15803d", borderColor: "#15803d", shadowColor: "#15803d" }),
  },
  {
    id: "download",
    name: "Download",
    description: "Icon-and-label action for files, reports, and exports.",
    category: "icon",
    tags: ["icon", "download", "utility"],
    cssOnly: true,
    config: config({ text: "Download", iconSymbol: "↓", iconPosition: "left", background: "#0f172a", borderColor: "#0f172a", shadowColor: "#0f172a" }),
  },
  {
    id: "arrow-cta",
    name: "Arrow CTA",
    description: "Directional CTA with motion-friendly arrow placement.",
    category: "icon",
    tags: ["icon", "arrow", "cta"],
    cssOnly: true,
    config: config({ text: "See what’s new", iconSymbol: "→", hoverEffect: "icon-shift", background: "#7c3aed", borderColor: "#7c3aed", shadowColor: "#7c3aed" }),
  },
  {
    id: "icon-circle",
    name: "Icon circle",
    description: "Compact icon-only control with an accessible label.",
    category: "icon",
    tags: ["icon-only", "circle", "compact"],
    cssOnly: true,
    config: config({ contentMode: "icon-only", shape: "pill", text: "Next step", iconSymbol: "→", background: "#0f172a", borderColor: "#0f172a", shadowColor: "#0f172a", paddingX: 14, paddingY: 14, minWidth: 0 }),
  },
  {
    id: "play-icon",
    name: "Play action",
    description: "Icon-led media control with a compact circular silhouette.",
    category: "icon",
    tags: ["play", "media", "icon-only"],
    cssOnly: true,
    config: config({ contentMode: "icon-only", shape: "pill", text: "Play video", iconSymbol: "▶", background: "#ffffff", textColor: "#111827", borderEnabled: true, borderColor: "#e5e7eb", shadowColor: "#111827", shadowOpacity: 0.16, paddingX: 15, paddingY: 15, hoverEffect: "scale" }),
  },
  {
    id: "loading-primary",
    name: "Loading primary",
    description: "Primary action previewed in a busy state.",
    category: "loading",
    tags: ["loading", "spinner", "state"],
    cssOnly: true,
    config: config({ loading: true, contentMode: "text", text: "Saving…", background: "#4f46e5", borderColor: "#4f46e5", shadowColor: "#4f46e5", hoverEffect: "none" }),
  },
  {
    id: "loading-dark",
    name: "Loading dark",
    description: "Compact dark busy state for forms and dashboards.",
    category: "loading",
    tags: ["loading", "dark", "form"],
    cssOnly: true,
    config: config({ loading: true, contentMode: "text", text: "Processing…", background: "#111827", borderColor: "#111827", shadowColor: "#111827", hoverEffect: "none" }),
  },
  {
    id: "large-hero",
    name: "Large hero CTA",
    description: "Generous spacing and typography for hero sections.",
    category: "cta",
    tags: ["hero", "large", "cta"],
    cssOnly: true,
    config: config({ text: "Build your project", iconSymbol: "→", fontSize: 18, paddingX: 30, paddingY: 16, radius: 16, shadowBlur: 24, shadowY: 10 }),
  },
  {
    id: "compact-toolbar",
    name: "Compact toolbar",
    description: "Small secondary control for dense product surfaces.",
    category: "minimal",
    tags: ["compact", "toolbar", "small"],
    cssOnly: true,
    config: config({ style: "outline", text: "Filter", iconSymbol: "+", iconPosition: "left", fontSize: 13, fontWeight: 700, paddingX: 12, paddingY: 8, radius: 9, textColor: "#334155", borderEnabled: true, borderColor: "#cbd5e1", shadowEnabled: false, hoverEffect: "darken" }),
  },
  {
    id: "dashed-outline",
    name: "Dashed upload",
    description: "Dashed secondary action for upload and empty states.",
    category: "minimal",
    tags: ["dashed", "upload", "outline"],
    cssOnly: true,
    config: config({ style: "outline", text: "Upload file", iconSymbol: "+", iconPosition: "left", textColor: "#475569", borderEnabled: true, borderStyle: "dashed", borderWidth: 2, borderColor: "#94a3b8", shadowEnabled: false, hoverEffect: "darken" }),
  },
  {
    id: "mint-soft",
    name: "Mint soft",
    description: "Friendly pastel action with subtle depth.",
    category: "popular",
    tags: ["pastel", "soft", "green"],
    cssOnly: true,
    config: config({ contentMode: "text", text: "Continue", background: "#d1fae5", textColor: "#065f46", borderEnabled: true, borderColor: "#a7f3d0", shadowColor: "#10b981", shadowOpacity: 0.14, hoverEffect: "lift" }),
  },
  {
    id: "full-width-form",
    name: "Full-width form",
    description: "Wide sign-in or checkout submit button for stacked forms.",
    category: "cta",
    tags: ["form", "submit", "full-width"],
    cssOnly: true,
    config: config({ contentMode: "text", text: "Create account", fullWidth: true, radius: 12, paddingY: 14, shadowY: 10, shadowBlur: 22, hoverEffect: "darken" }),
  },
  {
    id: "buy-now",
    name: "Buy now",
    description: "High-intent ecommerce action with compact strong styling.",
    category: "cta",
    tags: ["ecommerce", "checkout", "cta"],
    cssOnly: true,
    config: config({ text: "Buy now · $49", background: "#111827", borderColor: "#111827", shadowColor: "#111827", radius: 12, paddingX: 26, paddingY: 13, shadowBlur: 22, iconSymbol: "→", hoverEffect: "lift" }),
  },
  {
    id: "social-sign-in",
    name: "Social sign-in",
    description: "Neutral branded-login style with the provider mark on the left.",
    category: "minimal",
    tags: ["auth", "sign-in", "social"],
    cssOnly: true,
    config: config({ style: "outline", text: "Continue with Google", background: "#ffffff", textColor: "#111827", borderEnabled: true, borderColor: "#d1d5db", radius: 12, minWidth: 240, shadowEnabled: false, iconPosition: "left", iconSymbol: "G", hoverEffect: "darken" }),
  },
  {
    id: "nav-cta",
    name: "Navbar CTA",
    description: "Compact call-to-action sized for desktop navigation.",
    category: "cta",
    tags: ["navbar", "cta", "compact"],
    cssOnly: true,
    config: config({ text: "Book a demo", shape: "pill", fontSize: 14, paddingX: 18, paddingY: 14, shadowY: 6, shadowBlur: 16, hoverEffect: "lift" }),
  },
  {
    id: "destructive-outline",
    name: "Destructive outline",
    description: "Lower-emphasis destructive action for settings and account screens.",
    category: "minimal",
    tags: ["destructive", "outline", "settings"],
    cssOnly: true,
    config: config({ style: "outline", contentMode: "text", text: "Remove access", background: "#ffffff", textColor: "#b91c1c", borderEnabled: true, borderColor: "#fca5a5", shadowEnabled: false, hoverEffect: "darken" }),
  },
  {
    id: "status-pill",
    name: "Status pill",
    description: "Pill-shaped status control for filters and compact control bars.",
    category: "minimal",
    tags: ["status", "pill", "filter"],
    cssOnly: true,
    config: config({ shape: "pill", text: "Active", fontSize: 13, background: "#dcfce7", textColor: "#166534", borderEnabled: true, borderColor: "#86efac", paddingX: 16, paddingY: 14, shadowEnabled: false, iconSymbol: "✓", iconPosition: "left", hoverEffect: "darken" }),
  },
];

export const buttonPresetCategories = [
  { value: "all", label: "All" },
  { value: "popular", label: "Popular" },
  { value: "minimal", label: "Minimal" },
  { value: "cta", label: "CTA" },
  { value: "gradient", label: "Gradient" },
  { value: "glass", label: "Glass" },
  { value: "animated", label: "Animated" },
  { value: "3d", label: "3D" },
  { value: "icon", label: "Icon" },
  { value: "loading", label: "Loading" },
] as const;
