import type { ButtonGeneratorConfig, ButtonPreset } from "./types";

export const defaultButtonConfig: ButtonGeneratorConfig = {
  variant: "solid",
  className: "darma-button",
  text: "Get started",
  fontSize: 16,
  fontWeight: 700,
  letterSpacing: 0,
  radius: 14,
  paddingX: 22,
  paddingY: 12,
  minWidth: 0,
  shadow: 18,
  background: "#4f46e5",
  background2: "#ec4899",
  textColor: "#ffffff",
  borderColor: "#4f46e5",
  hoverEffect: "lift",
  activeEffect: true,
  disabled: false,
  iconPosition: "right",
  iconSymbol: "➜",
  uppercase: false,
  fullWidth: false,
  includeFocusRing: true,
  includeReducedMotion: true,
};

export const buttonPresets: ButtonPreset[] = [
  { id: "primary", name: "Primary CTA", description: "Bold main action button for hero sections and sign-up flows.", config: defaultButtonConfig },
  {
    id: "secondary",
    name: "Secondary action",
    description: "Clean outline style for supporting actions.",
    config: { ...defaultButtonConfig, variant: "outline", text: "Learn more", background: "#ffffff", textColor: "#111827", borderColor: "#d1d5db", shadow: 4, hoverEffect: "darken" },
  },
  {
    id: "gradient",
    name: "Gradient CTA",
    description: "Marketing button with strong visual pull.",
    config: { ...defaultButtonConfig, variant: "gradient", text: "Start free", background: "#06b6d4", background2: "#8b5cf6", borderColor: "#06b6d4", radius: 999, shadow: 22, hoverEffect: "glow" },
  },
  {
    id: "glass",
    name: "Glass action",
    description: "Frosted UI button for modern panels and overlays.",
    config: { ...defaultButtonConfig, variant: "glass", text: "Open menu", background: "#ffffff", background2: "#60a5fa", textColor: "#0f172a", borderColor: "#ffffff", shadow: 12 },
  },
  {
    id: "danger",
    name: "Danger action",
    description: "Destructive action with clear warning color.",
    config: { ...defaultButtonConfig, text: "Delete", background: "#dc2626", background2: "#991b1b", borderColor: "#dc2626", hoverEffect: "darken" },
  },
  {
    id: "success",
    name: "Success action",
    description: "Positive confirmation button for forms and flows.",
    config: { ...defaultButtonConfig, text: "Confirm", background: "#16a34a", background2: "#22c55e", borderColor: "#16a34a" },
  },
  {
    id: "neumo",
    name: "Soft neumorphic",
    description: "Friendly rounded button with soft raised depth.",
    config: { ...defaultButtonConfig, variant: "neumorphic", text: "Continue", background: "#e5e7eb", textColor: "#111827", borderColor: "#e5e7eb", shadow: 22, hoverEffect: "scale" },
  },
  {
    id: "icon",
    name: "Icon button",
    description: "Compact accessible icon-only control.",
    config: { ...defaultButtonConfig, variant: "icon", text: "Next step", iconSymbol: "→", background: "#0f172a", borderColor: "#0f172a", radius: 999, paddingX: 22, shadow: 14 },
  },
  {
    id: "minimal",
    name: "Minimal ghost",
    description: "Text-first button for quiet interfaces.",
    config: { ...defaultButtonConfig, variant: "ghost", text: "View details", background: "#ffffff", textColor: "#334155", borderColor: "#ffffff", shadow: 0, paddingX: 12, hoverEffect: "darken" },
  },
];
