import { createDefaultGridState, createGridItem } from "./grid";
import type { GridGeneratorState, GridPreset } from "./types";

function makeState(partial: Partial<GridGeneratorState>): GridGeneratorState {
  return { ...createDefaultGridState(), ...partial };
}

export const GRID_PRESETS: GridPreset[] = [
  {
    id: "bento-grid",
    name: "Bento grid",
    description: "Mixed card sizes for modern landing pages and dashboards.",
    state: createDefaultGridState(),
  },
  {
    id: "three-column",
    name: "Basic 3-column",
    description: "Equal columns for feature cards, pricing, or content blocks.",
    state: makeState({
      columns: 3,
      rows: 2,
      columnTemplate: "repeat(3, minmax(0, 1fr))",
      rowTemplate: "repeat(2, minmax(140px, auto))",
      items: [
        createGridItem({ id: "card-1", name: "Card 1", areaName: "cardOne", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 3, background: "#2563eb", content: "Card 1" }),
        createGridItem({ id: "card-2", name: "Card 2", areaName: "cardTwo", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 3, background: "#7c3aed", content: "Card 2" }),
        createGridItem({ id: "card-3", name: "Card 3", areaName: "cardThree", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 3, background: "#0f766e", content: "Card 3" }),
      ],
      selectedItemId: "card-1",
    }),
  },
  {
    id: "sidebar-layout",
    name: "Sidebar layout",
    description: "Classic sidebar and main content layout.",
    state: makeState({
      columns: 4,
      rows: 2,
      columnTemplate: "240px minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr)",
      rowTemplate: "auto minmax(300px, 1fr)",
      useTemplateAreas: true,
      items: [
        createGridItem({ id: "header", name: "Header", areaName: "header", columnStart: 1, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#1d4ed8", content: "Header" }),
        createGridItem({ id: "sidebar", name: "Sidebar", areaName: "sidebar", columnStart: 1, columnEnd: 2, rowStart: 2, rowEnd: 3, background: "#334155", content: "Sidebar" }),
        createGridItem({ id: "main", name: "Main", areaName: "main", columnStart: 2, columnEnd: 5, rowStart: 2, rowEnd: 3, background: "#059669", content: "Main content" }),
      ],
      selectedItemId: "main",
    }),
  },
  {
    id: "app-shell",
    name: "App shell",
    description: "Header, sidebar, content, and footer named areas.",
    state: makeState({
      columns: 4,
      rows: 4,
      columnTemplate: "220px repeat(3, minmax(0, 1fr))",
      rowTemplate: "72px repeat(2, minmax(150px, 1fr)) 72px",
      useTemplateAreas: true,
      items: [
        createGridItem({ id: "header", name: "Header", areaName: "header", columnStart: 1, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#4f46e5", content: "Header" }),
        createGridItem({ id: "sidebar", name: "Sidebar", areaName: "sidebar", columnStart: 1, columnEnd: 2, rowStart: 2, rowEnd: 4, background: "#0f172a", content: "Sidebar" }),
        createGridItem({ id: "content", name: "Content", areaName: "content", columnStart: 2, columnEnd: 5, rowStart: 2, rowEnd: 4, background: "#0d9488", content: "Content" }),
        createGridItem({ id: "footer", name: "Footer", areaName: "footer", columnStart: 1, columnEnd: 5, rowStart: 4, rowEnd: 5, background: "#9333ea", content: "Footer" }),
      ],
      selectedItemId: "content",
    }),
  },
  {
    id: "dashboard-cards",
    name: "Dashboard cards",
    description: "Metric cards, a wide chart, and a compact activity panel.",
    state: makeState({
      columns: 4,
      rows: 3,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "120px minmax(220px, 1fr) 140px",
      items: [
        createGridItem({ id: "metric-1", name: "Revenue", areaName: "revenue", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "Revenue" }),
        createGridItem({ id: "metric-2", name: "Orders", areaName: "orders", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#7c3aed", content: "Orders" }),
        createGridItem({ id: "metric-3", name: "Customers", areaName: "customers", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Customers" }),
        createGridItem({ id: "activity", name: "Activity", areaName: "activity", columnStart: 4, columnEnd: 5, rowStart: 1, rowEnd: 4, background: "#ea580c", content: "Activity" }),
        createGridItem({ id: "chart", name: "Chart", areaName: "chart", columnStart: 1, columnEnd: 4, rowStart: 2, rowEnd: 4, background: "#111827", content: "Chart area" }),
      ],
      selectedItemId: "chart",
    }),
  },
  {
    id: "gallery",
    name: "Gallery grid",
    description: "Featured image with supporting gallery tiles.",
    state: makeState({
      columns: 4,
      rows: 3,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "repeat(3, 150px)",
      items: [
        createGridItem({ id: "featured", name: "Featured", areaName: "featured", columnStart: 1, columnEnd: 3, rowStart: 1, rowEnd: 3, background: "#be123c", content: "Featured" }),
        createGridItem({ id: "tile-1", name: "Tile 1", areaName: "tileOne", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2, background: "#0891b2", content: "Tile" }),
        createGridItem({ id: "tile-2", name: "Tile 2", areaName: "tileTwo", columnStart: 4, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#7c2d12", content: "Tile" }),
        createGridItem({ id: "tile-3", name: "Tile 3", areaName: "tileThree", columnStart: 3, columnEnd: 5, rowStart: 2, rowEnd: 4, background: "#4f46e5", content: "Wide tile" }),
        createGridItem({ id: "tile-4", name: "Tile 4", areaName: "tileFour", columnStart: 1, columnEnd: 3, rowStart: 3, rowEnd: 4, background: "#166534", content: "Wide tile" }),
      ],
      selectedItemId: "featured",
    }),
  },
  {
    id: "landing-page",
    name: "Landing page",
    description: "Hero, proof, feature cards, and a full-width call to action.",
    state: makeState({
      columns: 4,
      rows: 4,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "minmax(220px, auto) 110px minmax(180px, auto) 140px",
      items: [
        createGridItem({ id: "hero-copy", name: "Hero copy", areaName: "heroCopy", columnStart: 1, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#4f46e5", content: "Hero copy" }),
        createGridItem({ id: "hero-media", name: "Hero media", areaName: "heroMedia", columnStart: 3, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Product preview" }),
        createGridItem({ id: "proof", name: "Social proof", areaName: "proof", columnStart: 1, columnEnd: 5, rowStart: 2, rowEnd: 3, background: "#334155", content: "Trusted by teams" }),
        createGridItem({ id: "feature-1", name: "Feature 1", areaName: "featureOne", columnStart: 1, columnEnd: 2, rowStart: 3, rowEnd: 4, background: "#2563eb", content: "Feature" }),
        createGridItem({ id: "feature-2", name: "Feature 2", areaName: "featureTwo", columnStart: 2, columnEnd: 4, rowStart: 3, rowEnd: 4, background: "#7c3aed", content: "Wide feature" }),
        createGridItem({ id: "feature-3", name: "Feature 3", areaName: "featureThree", columnStart: 4, columnEnd: 5, rowStart: 3, rowEnd: 4, background: "#ea580c", content: "Feature" }),
        createGridItem({ id: "cta", name: "CTA", areaName: "cta", columnStart: 1, columnEnd: 5, rowStart: 4, rowEnd: 5, background: "#0f172a", content: "Call to action" }),
      ],
      selectedItemId: "hero-copy",
    }),
  },
  {
    id: "pricing-comparison",
    name: "Pricing comparison",
    description: "Three plan cards with a highlighted plan and a full-width feature row.",
    state: makeState({
      columns: 3,
      rows: 2,
      columnTemplate: "repeat(3, minmax(0, 1fr))",
      rowTemplate: "minmax(300px, auto) 120px",
      items: [
        createGridItem({ id: "starter", name: "Starter", areaName: "starter", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 2, background: "#334155", content: "Starter" }),
        createGridItem({ id: "pro", name: "Pro", areaName: "pro", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#7c3aed", content: "Most popular" }),
        createGridItem({ id: "business", name: "Business", areaName: "business", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Business" }),
        createGridItem({ id: "comparison", name: "Comparison", areaName: "comparison", columnStart: 1, columnEnd: 4, rowStart: 2, rowEnd: 3, background: "#111827", content: "Feature comparison" }),
      ],
      selectedItemId: "pro",
    }),
  },
  {
    id: "blog-layout",
    name: "Blog + sidebar",
    description: "Article content with a supporting sidebar and related posts row.",
    state: makeState({
      columns: 4,
      rows: 3,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "90px minmax(360px, auto) 180px",
      items: [
        createGridItem({ id: "blog-header", name: "Header", areaName: "header", columnStart: 1, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#1d4ed8", content: "Blog header" }),
        createGridItem({ id: "article", name: "Article", areaName: "article", columnStart: 1, columnEnd: 4, rowStart: 2, rowEnd: 3, background: "#0f766e", content: "Article content" }),
        createGridItem({ id: "sidebar", name: "Sidebar", areaName: "sidebar", columnStart: 4, columnEnd: 5, rowStart: 2, rowEnd: 3, background: "#7c3aed", content: "Table of contents" }),
        createGridItem({ id: "related", name: "Related posts", areaName: "related", columnStart: 1, columnEnd: 5, rowStart: 3, rowEnd: 4, background: "#334155", content: "Related posts" }),
      ],
      selectedItemId: "article",
    }),
  },
  {
    id: "ecommerce-catalog",
    name: "E-commerce catalog",
    description: "Filter sidebar beside a responsive product-card grid.",
    state: makeState({
      columns: 4,
      rows: 3,
      columnTemplate: "220px repeat(3, minmax(0, 1fr))",
      rowTemplate: "repeat(3, minmax(180px, auto))",
      items: [
        createGridItem({ id: "filters", name: "Filters", areaName: "filters", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 4, background: "#0f172a", content: "Filters" }),
        createGridItem({ id: "product-1", name: "Product 1", areaName: "productOne", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "Product" }),
        createGridItem({ id: "product-2", name: "Product 2", areaName: "productTwo", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Product" }),
        createGridItem({ id: "product-3", name: "Product 3", areaName: "productThree", columnStart: 4, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#7c3aed", content: "Product" }),
        createGridItem({ id: "product-4", name: "Product 4", areaName: "productFour", columnStart: 2, columnEnd: 4, rowStart: 2, rowEnd: 3, background: "#ea580c", content: "Featured product" }),
        createGridItem({ id: "product-5", name: "Product 5", areaName: "productFive", columnStart: 4, columnEnd: 5, rowStart: 2, rowEnd: 3, background: "#be123c", content: "Product" }),
        createGridItem({ id: "pagination", name: "Pagination", areaName: "pagination", columnStart: 2, columnEnd: 5, rowStart: 3, rowEnd: 4, background: "#334155", content: "Pagination" }),
      ],
      selectedItemId: "product-4",
    }),
  },
  {
    id: "holy-grail",
    name: "Holy grail page",
    description: "Header, left navigation, main content, right rail, and footer.",
    state: makeState({
      columns: 5,
      rows: 3,
      columnTemplate: "200px repeat(3, minmax(0, 1fr)) 220px",
      rowTemplate: "72px minmax(360px, 1fr) 72px",
      items: [
        createGridItem({ id: "hg-header", name: "Header", areaName: "header", columnStart: 1, columnEnd: 6, rowStart: 1, rowEnd: 2, background: "#1d4ed8", content: "Header" }),
        createGridItem({ id: "hg-nav", name: "Navigation", areaName: "navigation", columnStart: 1, columnEnd: 2, rowStart: 2, rowEnd: 3, background: "#334155", content: "Navigation" }),
        createGridItem({ id: "hg-main", name: "Main", areaName: "main", columnStart: 2, columnEnd: 5, rowStart: 2, rowEnd: 3, background: "#0f766e", content: "Main content" }),
        createGridItem({ id: "hg-aside", name: "Aside", areaName: "aside", columnStart: 5, columnEnd: 6, rowStart: 2, rowEnd: 3, background: "#7c3aed", content: "Aside" }),
        createGridItem({ id: "hg-footer", name: "Footer", areaName: "footer", columnStart: 1, columnEnd: 6, rowStart: 3, rowEnd: 4, background: "#0f172a", content: "Footer" }),
      ],
      selectedItemId: "hg-main",
    }),
  },
  {
    id: "kanban-board",
    name: "Kanban board",
    description: "Three task columns for backlog, in progress, and done states.",
    state: makeState({
      columns: 3,
      rows: 3,
      columnTemplate: "repeat(3, minmax(220px, 1fr))",
      rowTemplate: "64px repeat(2, minmax(160px, auto))",
      items: [
        createGridItem({ id: "todo-head", name: "Todo", areaName: "todoHead", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 2, background: "#334155", content: "Backlog" }),
        createGridItem({ id: "doing-head", name: "Doing", areaName: "doingHead", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "In progress" }),
        createGridItem({ id: "done-head", name: "Done", areaName: "doneHead", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Done" }),
        createGridItem({ id: "todo-cards", name: "Todo cards", areaName: "todoCards", columnStart: 1, columnEnd: 2, rowStart: 2, rowEnd: 4, background: "#64748b", content: "Task cards" }),
        createGridItem({ id: "doing-cards", name: "Doing cards", areaName: "doingCards", columnStart: 2, columnEnd: 3, rowStart: 2, rowEnd: 4, background: "#4f46e5", content: "Task cards" }),
        createGridItem({ id: "done-cards", name: "Done cards", areaName: "doneCards", columnStart: 3, columnEnd: 4, rowStart: 2, rowEnd: 4, background: "#059669", content: "Task cards" }),
      ],
      selectedItemId: "doing-cards",
    }),
  },
  {
    id: "portfolio-projects",
    name: "Portfolio projects",
    description: "Editorial project grid with one dominant case study and supporting work.",
    state: makeState({
      columns: 4,
      rows: 3,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "repeat(3, minmax(160px, auto))",
      items: [
        createGridItem({ id: "case-study", name: "Case study", areaName: "caseStudy", columnStart: 1, columnEnd: 3, rowStart: 1, rowEnd: 3, background: "#4f46e5", content: "Featured project" }),
        createGridItem({ id: "project-2", name: "Project 2", areaName: "projectTwo", columnStart: 3, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Project" }),
        createGridItem({ id: "project-3", name: "Project 3", areaName: "projectThree", columnStart: 3, columnEnd: 4, rowStart: 2, rowEnd: 3, background: "#be123c", content: "Project" }),
        createGridItem({ id: "project-4", name: "Project 4", areaName: "projectFour", columnStart: 4, columnEnd: 5, rowStart: 2, rowEnd: 4, background: "#ea580c", content: "Tall project" }),
        createGridItem({ id: "project-5", name: "Project 5", areaName: "projectFive", columnStart: 1, columnEnd: 4, rowStart: 3, rowEnd: 4, background: "#0f172a", content: "Wide project" }),
      ],
      selectedItemId: "case-study",
    }),
  },
  {
    id: "form-layout",
    name: "Settings form",
    description: "Two-column settings form with a full-width message and action row.",
    state: makeState({
      columns: 2,
      rows: 4,
      columnTemplate: "repeat(2, minmax(0, 1fr))",
      rowTemplate: "repeat(3, minmax(110px, auto)) 88px",
      items: [
        createGridItem({ id: "profile", name: "Profile", areaName: "profile", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "Profile fields" }),
        createGridItem({ id: "contact", name: "Contact", areaName: "contact", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "Contact fields" }),
        createGridItem({ id: "preferences", name: "Preferences", areaName: "preferences", columnStart: 1, columnEnd: 3, rowStart: 2, rowEnd: 3, background: "#7c3aed", content: "Preferences" }),
        createGridItem({ id: "message", name: "Message", areaName: "message", columnStart: 1, columnEnd: 3, rowStart: 3, rowEnd: 4, background: "#334155", content: "Long text field" }),
        createGridItem({ id: "actions", name: "Actions", areaName: "actions", columnStart: 1, columnEnd: 3, rowStart: 4, rowEnd: 5, background: "#0f172a", content: "Cancel · Save changes" }),
      ],
      selectedItemId: "preferences",
    }),
  },
  {
    id: "analytics-overview",
    name: "Analytics overview",
    description: "KPI strip, large chart, secondary chart, and insight rail.",
    state: makeState({
      columns: 4,
      rows: 3,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "110px minmax(240px, 1fr) 180px",
      items: [
        createGridItem({ id: "kpi-1", name: "KPI 1", areaName: "kpiOne", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "Visitors" }),
        createGridItem({ id: "kpi-2", name: "KPI 2", areaName: "kpiTwo", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 2, background: "#7c3aed", content: "Conversion" }),
        createGridItem({ id: "kpi-3", name: "KPI 3", areaName: "kpiThree", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 2, background: "#0f766e", content: "MRR" }),
        createGridItem({ id: "insights", name: "Insights", areaName: "insights", columnStart: 4, columnEnd: 5, rowStart: 1, rowEnd: 4, background: "#ea580c", content: "Insights" }),
        createGridItem({ id: "primary-chart", name: "Primary chart", areaName: "primaryChart", columnStart: 1, columnEnd: 4, rowStart: 2, rowEnd: 3, background: "#0f172a", content: "Traffic chart" }),
        createGridItem({ id: "secondary-chart", name: "Secondary chart", areaName: "secondaryChart", columnStart: 1, columnEnd: 4, rowStart: 3, rowEnd: 4, background: "#475569", content: "Source breakdown" }),
      ],
      selectedItemId: "primary-chart",
    }),
  },
  {
    id: "magazine-layout",
    name: "Magazine layout",
    description: "Lead story, supporting stories, quote card, and a full-width footer story.",
    state: makeState({
      columns: 4,
      rows: 4,
      columnTemplate: "repeat(4, minmax(0, 1fr))",
      rowTemplate: "repeat(4, minmax(140px, auto))",
      items: [
        createGridItem({ id: "lead", name: "Lead story", areaName: "lead", columnStart: 1, columnEnd: 3, rowStart: 1, rowEnd: 3, background: "#be123c", content: "Lead story" }),
        createGridItem({ id: "story-2", name: "Story 2", areaName: "storyTwo", columnStart: 3, columnEnd: 5, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "Story" }),
        createGridItem({ id: "story-3", name: "Story 3", areaName: "storyThree", columnStart: 3, columnEnd: 4, rowStart: 2, rowEnd: 3, background: "#0f766e", content: "Story" }),
        createGridItem({ id: "quote", name: "Quote", areaName: "quote", columnStart: 4, columnEnd: 5, rowStart: 2, rowEnd: 4, background: "#7c3aed", content: "Pull quote" }),
        createGridItem({ id: "story-4", name: "Story 4", areaName: "storyFour", columnStart: 1, columnEnd: 4, rowStart: 3, rowEnd: 4, background: "#ea580c", content: "Wide story" }),
        createGridItem({ id: "footer-story", name: "Footer story", areaName: "footerStory", columnStart: 1, columnEnd: 5, rowStart: 4, rowEnd: 5, background: "#0f172a", content: "Full-width story" }),
      ],
      selectedItemId: "lead",
    }),
  },
  {
    id: "comparison-table",
    name: "Comparison matrix",
    description: "Sticky-like label column with three comparable option columns.",
    state: makeState({
      columns: 4,
      rows: 4,
      columnTemplate: "180px repeat(3, minmax(0, 1fr))",
      rowTemplate: "84px repeat(3, minmax(88px, auto))",
      items: [
        createGridItem({ id: "labels", name: "Labels", areaName: "labels", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 5, background: "#0f172a", content: "Features" }),
        createGridItem({ id: "option-a", name: "Option A", areaName: "optionA", columnStart: 2, columnEnd: 3, rowStart: 1, rowEnd: 5, background: "#2563eb", content: "Starter" }),
        createGridItem({ id: "option-b", name: "Option B", areaName: "optionB", columnStart: 3, columnEnd: 4, rowStart: 1, rowEnd: 5, background: "#7c3aed", content: "Pro" }),
        createGridItem({ id: "option-c", name: "Option C", areaName: "optionC", columnStart: 4, columnEnd: 5, rowStart: 1, rowEnd: 5, background: "#0f766e", content: "Business" }),
      ],
      selectedItemId: "option-b",
    }),
  },
  {
    id: "custom",
    name: "Custom grid",
    description: "Start from a clean blank-ish layout with one item.",
    state: makeState({
      columns: 3,
      rows: 3,
      columnTemplate: "repeat(3, minmax(0, 1fr))",
      rowTemplate: "repeat(3, minmax(120px, auto))",
      items: [createGridItem({ id: "item-1", name: "Item 1", areaName: "itemOne", columnStart: 1, columnEnd: 2, rowStart: 1, rowEnd: 2, background: "#2563eb", content: "Item 1" })],
      selectedItemId: "item-1",
    }),
  },
];
