import type { TimezonePreset } from "./types";

export const TIMEZONE_PRESETS: TimezonePreset[] = [
  {
    id: "remote-standup",
    label: "Remote standup",
    description: "New York morning with London, Hebron, Dubai, and Tokyo.",
    icon: "🌍",
    dateValue: "2026-07-15",
    timeValue: "09:00",
    sourceZone: "America/New_York",
    targetZones: ["America/New_York", "Europe/London", "Asia/Hebron", "Asia/Dubai", "Asia/Tokyo"],
    durationMinutes: 30,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "hebron-client-call",
    label: "Hebron client call",
    description: "Plan a late-afternoon call from Hebron to Europe and North America.",
    icon: "📞",
    dateValue: "2026-07-16",
    timeValue: "16:00",
    sourceZone: "Asia/Hebron",
    targetZones: ["Asia/Hebron", "Europe/London", "Europe/Berlin", "America/New_York", "America/Los_Angeles"],
    durationMinutes: 60,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "product-launch",
    label: "Global launch",
    description: "Compare a UTC launch across major customer regions.",
    icon: "🚀",
    dateValue: "2026-10-01",
    timeValue: "14:00",
    sourceZone: "UTC",
    targetZones: ["UTC", "America/New_York", "Europe/London", "Asia/Dubai", "Asia/Singapore", "Australia/Sydney"],
    durationMinutes: 90,
    workingStart: "08:00",
    workingEnd: "19:00",
  },
  {
    id: "webinar",
    label: "International webinar",
    description: "A London-hosted webinar for the Americas, Middle East, and Asia.",
    icon: "🎙️",
    dateValue: "2026-09-08",
    timeValue: "15:00",
    sourceZone: "Europe/London",
    targetZones: ["Europe/London", "America/Toronto", "America/Sao_Paulo", "Asia/Hebron", "Asia/Kolkata", "Asia/Singapore"],
    durationMinutes: 75,
    workingStart: "08:00",
    workingEnd: "20:00",
  },
  {
    id: "travel-arrival",
    label: "Travel arrival",
    description: "Check a Tokyo departure moment across Dubai, Cairo, and London.",
    icon: "✈️",
    dateValue: "2026-11-20",
    timeValue: "22:30",
    sourceZone: "Asia/Tokyo",
    targetZones: ["Asia/Tokyo", "Asia/Dubai", "Africa/Cairo", "Europe/London", "UTC"],
    durationMinutes: 45,
    workingStart: "07:00",
    workingEnd: "22:00",
  },
  {
    id: "dst-review",
    label: "DST review",
    description: "Inspect a date near European daylight-saving changes.",
    icon: "🕰️",
    dateValue: "2026-10-25",
    timeValue: "01:30",
    sourceZone: "Europe/London",
    targetZones: ["Europe/London", "Europe/Berlin", "UTC", "America/New_York", "Asia/Hebron"],
    durationMinutes: 60,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "us-eu-interview",
    label: "US ↔ Europe interview",
    description: "Plan a New York interview with London, Berlin, and Paris participants.",
    icon: "💼",
    dateValue: "2026-09-15",
    timeValue: "10:00",
    sourceZone: "America/New_York",
    targetZones: ["America/New_York", "Europe/London", "Europe/Berlin", "Europe/Paris"],
    durationMinutes: 45,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "mena-europe-sync",
    label: "MENA ↔ Europe sync",
    description: "Find an overlap for Hebron, Amman, Dubai, London, and Berlin.",
    icon: "🤝",
    dateValue: "2026-09-17",
    timeValue: "14:00",
    sourceZone: "Asia/Hebron",
    targetZones: ["Asia/Hebron", "Asia/Amman", "Asia/Dubai", "Europe/London", "Europe/Berlin"],
    durationMinutes: 60,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "asia-team-sync",
    label: "Asia team sync",
    description: "Coordinate Singapore, Tokyo, Seoul, Kolkata, and Dubai.",
    icon: "🌏",
    dateValue: "2026-09-21",
    timeValue: "15:00",
    sourceZone: "Asia/Singapore",
    targetZones: ["Asia/Singapore", "Asia/Tokyo", "Asia/Seoul", "Asia/Kolkata", "Asia/Dubai"],
    durationMinutes: 45,
    workingStart: "08:00",
    workingEnd: "19:00",
  },
  {
    id: "americas-sync",
    label: "Americas sync",
    description: "Compare Los Angeles, Denver, Chicago, New York, Toronto, and São Paulo.",
    icon: "🌎",
    dateValue: "2026-09-22",
    timeValue: "09:00",
    sourceZone: "America/Los_Angeles",
    targetZones: ["America/Los_Angeles", "America/Denver", "America/Chicago", "America/New_York", "America/Toronto", "America/Sao_Paulo"],
    durationMinutes: 60,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "follow-the-sun-handoff",
    label: "Follow-the-sun handoff",
    description: "Plan a support handoff from Sydney through Singapore, Dubai, London, and New York.",
    icon: "☀️",
    dateValue: "2026-09-24",
    timeValue: "17:00",
    sourceZone: "Australia/Sydney",
    targetZones: ["Australia/Sydney", "Asia/Singapore", "Asia/Dubai", "Europe/London", "America/New_York"],
    durationMinutes: 30,
    workingStart: "07:00",
    workingEnd: "19:00",
  },
  {
    id: "live-stream",
    label: "Global live stream",
    description: "Compare a UTC stream start across major audience regions.",
    icon: "📺",
    dateValue: "2026-12-05",
    timeValue: "18:00",
    sourceZone: "UTC",
    targetZones: ["UTC", "America/Los_Angeles", "America/New_York", "Europe/London", "Asia/Hebron", "Asia/Kolkata", "Asia/Tokyo"],
    durationMinutes: 120,
    workingStart: "07:00",
    workingEnd: "23:00",
  },
  {
    id: "board-meeting",
    label: "Board meeting",
    description: "Find a professional-hours overlap between San Francisco, London, Dubai, and Singapore.",
    icon: "🏢",
    dateValue: "2026-10-12",
    timeValue: "07:30",
    sourceZone: "America/Los_Angeles",
    targetZones: ["America/Los_Angeles", "Europe/London", "Asia/Dubai", "Asia/Singapore"],
    durationMinutes: 90,
    workingStart: "07:00",
    workingEnd: "19:00",
  },
  {
    id: "new-year-rollout",
    label: "New Year rollout",
    description: "Compare a UTC deployment around New Year across several regions.",
    icon: "🎆",
    dateValue: "2027-01-01",
    timeValue: "00:30",
    sourceZone: "UTC",
    targetZones: ["UTC", "America/New_York", "Europe/London", "Asia/Dubai", "Asia/Tokyo", "Australia/Sydney"],
    durationMinutes: 60,
    workingStart: "00:00",
    workingEnd: "23:59",
  },
  {
    id: "dst-us-review",
    label: "US DST review",
    description: "Inspect a date near the North American daylight-saving transition.",
    icon: "⏰",
    dateValue: "2026-11-01",
    timeValue: "01:30",
    sourceZone: "America/New_York",
    targetZones: ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "UTC", "Europe/London"],
    durationMinutes: 60,
    workingStart: "07:00",
    workingEnd: "19:00",
  },
  {
    id: "flight-checkin",
    label: "Flight check-in",
    description: "Compare a departure check-in time between Los Angeles, Tokyo, and destination clocks.",
    icon: "🧳",
    dateValue: "2026-11-18",
    timeValue: "18:00",
    sourceZone: "America/Los_Angeles",
    targetZones: ["America/Los_Angeles", "Asia/Tokyo", "Asia/Singapore", "UTC"],
    durationMinutes: 120,
    workingStart: "05:00",
    workingEnd: "23:00",
  },
  {
    id: "release-window",
    label: "Release window",
    description: "Plan a London release with engineering teams in New York, Hebron, and Bengaluru.",
    icon: "🛠️",
    dateValue: "2026-10-20",
    timeValue: "13:00",
    sourceZone: "Europe/London",
    targetZones: ["Europe/London", "America/New_York", "Asia/Hebron", "Asia/Kolkata"],
    durationMinutes: 120,
    workingStart: "07:00",
    workingEnd: "20:00",
  },
  {
    id: "customer-training",
    label: "Customer training",
    description: "Schedule training from Dubai for customers in London, Nairobi, Mumbai, and Singapore.",
    icon: "🎓",
    dateValue: "2026-10-22",
    timeValue: "13:30",
    sourceZone: "Asia/Dubai",
    targetZones: ["Asia/Dubai", "Europe/London", "Africa/Nairobi", "Asia/Kolkata", "Asia/Singapore"],
    durationMinutes: 90,
    workingStart: "08:00",
    workingEnd: "20:00",
  },

];
