import type { TimezonePreset } from "./types";

export const TIMEZONE_PRESETS: TimezonePreset[] = [
  {
    id: "remote-standup",
    label: "Remote standup",
    description: "New York morning with London, Hebron, Dubai, and Tokyo.",
    icon: "🌍",
    dateValue: "2026-07-15",
    timeValue: "09:00",
    sourceZone: "America/New_York",
    targetZones: ["America/New_York", "Europe/London", "Asia/Hebron", "Asia/Dubai", "Asia/Tokyo"],
    durationMinutes: 30,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "hebron-client-call",
    label: "Hebron client call",
    description: "Plan a late-afternoon call from Hebron to Europe and North America.",
    icon: "📞",
    dateValue: "2026-07-16",
    timeValue: "16:00",
    sourceZone: "Asia/Hebron",
    targetZones: ["Asia/Hebron", "Europe/London", "Europe/Berlin", "America/New_York", "America/Los_Angeles"],
    durationMinutes: 60,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
  {
    id: "product-launch",
    label: "Global launch",
    description: "Compare a UTC launch across major customer regions.",
    icon: "🚀",
    dateValue: "2026-10-01",
    timeValue: "14:00",
    sourceZone: "UTC",
    targetZones: ["UTC", "America/New_York", "Europe/London", "Asia/Dubai", "Asia/Singapore", "Australia/Sydney"],
    durationMinutes: 90,
    workingStart: "08:00",
    workingEnd: "19:00",
  },
  {
    id: "webinar",
    label: "International webinar",
    description: "A London-hosted webinar for the Americas, Middle East, and Asia.",
    icon: "🎙️",
    dateValue: "2026-09-08",
    timeValue: "15:00",
    sourceZone: "Europe/London",
    targetZones: ["Europe/London", "America/Toronto", "America/Sao_Paulo", "Asia/Hebron", "Asia/Kolkata", "Asia/Singapore"],
    durationMinutes: 75,
    workingStart: "08:00",
    workingEnd: "20:00",
  },
  {
    id: "travel-arrival",
    label: "Travel arrival",
    description: "Check a Tokyo departure moment across Dubai, Cairo, and London.",
    icon: "✈️",
    dateValue: "2026-11-20",
    timeValue: "22:30",
    sourceZone: "Asia/Tokyo",
    targetZones: ["Asia/Tokyo", "Asia/Dubai", "Africa/Cairo", "Europe/London", "UTC"],
    durationMinutes: 45,
    workingStart: "07:00",
    workingEnd: "22:00",
  },
  {
    id: "dst-review",
    label: "DST review",
    description: "Inspect a date near European daylight-saving changes.",
    icon: "🕰️",
    dateValue: "2026-10-25",
    timeValue: "01:30",
    sourceZone: "Europe/London",
    targetZones: ["Europe/London", "Europe/Berlin", "UTC", "America/New_York", "Asia/Hebron"],
    durationMinutes: 60,
    workingStart: "08:00",
    workingEnd: "18:00",
  },
];
