import type { TimestampPreset } from "./types";

export const TIMESTAMP_PRESETS: TimestampPreset[] = [
  {
    id: "unix-seconds",
    label: "Unix seconds",
    description: "A common 10-digit API or database timestamp.",
    icon: "⏱️",
    inputMode: "epoch",
    timestamp: "1700000000",
    unitMode: "seconds",
  },
  {
    id: "javascript-ms",
    label: "JavaScript ms",
    description: "A 13-digit Date.now() style timestamp.",
    icon: "🟨",
    inputMode: "epoch",
    timestamp: "1700000000000",
    unitMode: "milliseconds",
  },
  {
    id: "microseconds",
    label: "Log microseconds",
    description: "A 16-digit microsecond timestamp from logs or analytics.",
    icon: "🔬",
    inputMode: "epoch",
    timestamp: "1700000000123456",
    unitMode: "microseconds",
  },
  {
    id: "nanoseconds",
    label: "Trace nanoseconds",
    description: "A 19-digit nanosecond timestamp with sub-millisecond precision.",
    icon: "⚡",
    inputMode: "epoch",
    timestamp: "1700000000123456789",
    unitMode: "nanoseconds",
  },
  {
    id: "iso-webhook",
    label: "ISO webhook",
    description: "Convert an explicit UTC ISO value into epoch formats.",
    icon: "🌐",
    inputMode: "date",
    dateMode: "iso",
    dateInput: "2030-01-01T00:00:00Z",
  },
  {
    id: "mixed-batch",
    label: "Mixed batch",
    description: "Process seconds, milliseconds, microseconds, and invalid rows together.",
    icon: "📦",
    inputMode: "batch",
    unitMode: "auto",
    batchInput: [
      "1700000000 seconds",
      "1700000000000 ms",
      "1700000000123456 us",
      "1700000000123456789 ns",
      "not-a-timestamp",
    ].join("\n"),
  },
];
