import type { TimestampPreset } from "./types";

export const TIMESTAMP_PRESETS: TimestampPreset[] = [
  {
    id: "unix-seconds",
    label: "Unix seconds",
    description: "A common 10-digit API or database timestamp.",
    icon: "⏱️",
    inputMode: "epoch",
    timestamp: "1700000000",
    unitMode: "seconds",
  },
  {
    id: "javascript-ms",
    label: "JavaScript ms",
    description: "A 13-digit Date.now() style timestamp.",
    icon: "🟨",
    inputMode: "epoch",
    timestamp: "1700000000000",
    unitMode: "milliseconds",
  },
  {
    id: "microseconds",
    label: "Log microseconds",
    description: "A 16-digit microsecond timestamp from logs or analytics.",
    icon: "🔬",
    inputMode: "epoch",
    timestamp: "1700000000123456",
    unitMode: "microseconds",
  },
  {
    id: "nanoseconds",
    label: "Trace nanoseconds",
    description: "A 19-digit nanosecond timestamp with sub-millisecond precision.",
    icon: "⚡",
    inputMode: "epoch",
    timestamp: "1700000000123456789",
    unitMode: "nanoseconds",
  },
  {
    id: "iso-webhook",
    label: "ISO webhook",
    description: "Convert an explicit UTC ISO value into epoch formats.",
    icon: "🌐",
    inputMode: "date",
    dateMode: "iso",
    dateInput: "2030-01-01T00:00:00Z",
  },
  {
    id: "mixed-batch",
    label: "Mixed batch",
    description: "Process seconds, milliseconds, microseconds, and invalid rows together.",
    icon: "📦",
    inputMode: "batch",
    unitMode: "auto",
    batchInput: [
      "1700000000 seconds",
      "1700000000000 ms",
      "1700000000123456 us",
      "1700000000123456789 ns",
      "not-a-timestamp",
    ].join("\n"),
  },
  {
    id: "api-created-at",
    label: "API created_at",
    description: "Inspect a typical backend epoch-seconds created_at field.",
    icon: "🧩",
    inputMode: "epoch",
    timestamp: "1767225600",
    unitMode: "seconds",
  },
  {
    id: "browser-event",
    label: "Browser event",
    description: "Inspect a millisecond browser analytics event timestamp.",
    icon: "🖥️",
    inputMode: "epoch",
    timestamp: "1767225600123",
    unitMode: "milliseconds",
  },
  {
    id: "database-microseconds",
    label: "Database microseconds",
    description: "Decode a microsecond-resolution value from database exports.",
    icon: "🗄️",
    inputMode: "epoch",
    timestamp: "1767225600123456",
    unitMode: "microseconds",
  },
  {
    id: "otel-trace",
    label: "OpenTelemetry trace",
    description: "Inspect a nanosecond timestamp commonly seen in tracing pipelines.",
    icon: "📡",
    inputMode: "epoch",
    timestamp: "1767225600123456789",
    unitMode: "nanoseconds",
  },
  {
    id: "release-date",
    label: "Release date",
    description: "Convert a UTC software release date into all supported epoch formats.",
    icon: "🚀",
    inputMode: "date",
    dateMode: "iso",
    dateInput: "2027-06-15T09:30:00Z",
  },
  {
    id: "webhook-offset",
    label: "Webhook with offset",
    description: "Convert an ISO webhook timestamp that includes a positive UTC offset.",
    icon: "🪝",
    inputMode: "date",
    dateMode: "iso",
    dateInput: "2027-03-20T18:45:00+03:00",
  },
  {
    id: "incident-log",
    label: "Incident log",
    description: "Compare several log timestamps around one incident window.",
    icon: "🚨",
    inputMode: "batch",
    unitMode: "auto",
    batchInput: ["1767225600", "1767225635000", "1767225690123456", "1767225750123456789"].join("\n"),
  },
  {
    id: "analytics-import",
    label: "Analytics import",
    description: "Convert a mixed analytics export where units differ by source.",
    icon: "📈",
    inputMode: "batch",
    unitMode: "auto",
    batchInput: ["1704067200 seconds", "1704067200123 ms", "1704067200123456 us", "1704067200123456789 ns"].join("\n"),
  },
  {
    id: "legacy-seconds",
    label: "Legacy 2001 epoch",
    description: "Inspect an older 10-digit timestamp to validate historical data.",
    icon: "📚",
    inputMode: "epoch",
    timestamp: "1000000000",
    unitMode: "seconds",
  },
  {
    id: "future-2038",
    label: "2038 boundary check",
    description: "Inspect a timestamp close to the classic signed 32-bit Unix boundary.",
    icon: "🧪",
    inputMode: "epoch",
    timestamp: "2147483647",
    unitMode: "seconds",
  },
  {
    id: "local-form-date",
    label: "Local form date",
    description: "Convert a local date-time input as entered by a user-facing form.",
    icon: "📝",
    inputMode: "date",
    dateMode: "local",
    dateInput: "2027-09-01T10:15",
  },
  {
    id: "invalid-batch-review",
    label: "Validation batch",
    description: "Exercise valid, ambiguous, and invalid timestamp rows together.",
    icon: "✅",
    inputMode: "batch",
    unitMode: "auto",
    batchInput: ["1700000000", "1700000000000", "12345", "2027-01-01", "not-a-number"].join("\n"),
  },

];
