import type { ReadabilityPreset, ReadabilityTarget } from "./types";

export const READABILITY_TARGETS: ReadabilityTarget[] = [
  {
    id: "plain-language",
    label: "Plain language",
    description: "Public instructions, forms, and essential service information.",
    maxGrade: 6,
    minReadingEase: 70,
    maxSentenceWords: 16,
    maxComplexWordPercent: 8,
  },
  {
    id: "general-web",
    label: "General web",
    description: "Articles, landing pages, support content, and broad audiences.",
    maxGrade: 8,
    minReadingEase: 60,
    maxSentenceWords: 20,
    maxComplexWordPercent: 12,
  },
  {
    id: "middle-school",
    label: "Middle school",
    description: "Learning material intended for readers around grades 7–9.",
    maxGrade: 9,
    minReadingEase: 55,
    maxSentenceWords: 22,
    maxComplexWordPercent: 14,
  },
  {
    id: "professional",
    label: "Professional",
    description: "Business reports, policies, and technical communication.",
    maxGrade: 11,
    minReadingEase: 45,
    maxSentenceWords: 25,
    maxComplexWordPercent: 18,
  },
  {
    id: "academic",
    label: "Academic",
    description: "Research summaries and specialist writing where complexity is expected.",
    maxGrade: 14,
    minReadingEase: 30,
    maxSentenceWords: 30,
    maxComplexWordPercent: 24,
  },
];

export const READABILITY_PRESETS: ReadabilityPreset[] = [
  {
    id: "support-article",
    label: "Support article",
    description: "Clear troubleshooting steps for a broad web audience.",
    targetId: "general-web",
    text: `If the app will not open, restart your device first. Open the app again and check whether the problem remains. If it does, confirm that your internet connection is working. You can test the connection by opening another website. Next, install any available app update. Updates often fix known crashes and loading problems. If the issue continues, contact support and include the error message you saw.`,
  },
  {
    id: "public-notice",
    label: "Public notice",
    description: "Short plain-language instructions for an essential service.",
    targetId: "plain-language",
    text: `The water supply will stop on Tuesday from 9:00 a.m. to 1:00 p.m. Store enough water before the work begins. Keep taps closed during the outage. When service returns, let the cold water run for two minutes. Call the service desk if the water stays cloudy for more than one hour.`,
  },
  {
    id: "product-documentation",
    label: "Product documentation",
    description: "A technical explanation with a few sentences worth reviewing.",
    targetId: "professional",
    text: `The synchronization service stores pending changes in a local queue before it contacts the remote API. When connectivity returns, the worker processes each queued operation in chronological order and records the server response. Administrators can configure the retry interval, but an excessively aggressive interval may increase request volume and trigger upstream rate limits. Failed operations remain visible in the activity log so that an operator can inspect the payload and retry the request manually.`,
  },
  {
    id: "academic-abstract",
    label: "Academic abstract",
    description: "Dense research prose intended for a specialist audience.",
    targetId: "academic",
    text: `This study evaluates the relationship between retrieval practice and delayed recall in undergraduate learners. Participants completed three instructional conditions and returned after seven days for an unannounced assessment. The retrieval group demonstrated a statistically meaningful improvement in long-term retention, although the observed effect varied across prior-knowledge levels. These findings support the integration of low-stakes retrieval opportunities within introductory courses while highlighting the importance of differentiated instructional design.`,
  },
  {
    id: "dense-policy",
    label: "Dense policy draft",
    description: "A deliberately difficult paragraph that exposes review flags.",
    targetId: "general-web",
    text: `Notwithstanding any previously communicated implementation schedule, organizational representatives who anticipate requiring supplementary authorization documentation must, before initiating the applicable reimbursement procedure, coordinate with the designated administrative facilitator so that all prerequisite verification materials can be comprehensively evaluated and subsequently transmitted to the appropriate departmental authority. Requests that are submitted without the aforementioned documentation may be delayed, returned, or otherwise excluded from the current processing cycle.`,
  },
  {
    id: "release-notes",
    label: "Release notes",
    description: "Scannable product changes written for customers.",
    targetId: "general-web",
    text: `This release makes search faster and easier to understand. Results now show why an item matched your query. We also fixed a bug that could hide recently edited documents. Team owners can now export an activity report as a CSV file. No action is required after the update.`,
  },
  {
    id: "onboarding-email",
    label: "Onboarding email",
    description: "A welcome message that must be understood on a phone in one pass.",
    targetId: "general-web",
    text: `Welcome aboard. Your account is ready, so you can start straight away. First, add your name and a photo so teammates recognise you. Next, create your first project and invite one colleague. Most people finish both steps in under five minutes. If anything looks wrong, reply to this email and a real person will help.`,
  },
  {
    id: "medical-instructions",
    label: "Patient instructions",
    description: "After-visit guidance where plain language is a safety requirement.",
    targetId: "plain-language",
    text: `Take one tablet with food each morning. Do not take more than one tablet in a day. Drink a full glass of water with each dose. Some people feel dizzy in the first week. If you feel dizzy, sit down and rest. Call the clinic if the dizziness does not stop, or if you develop a rash.`,
  },
  {
    id: "safety-notice",
    label: "Workplace safety notice",
    description: "Short mandatory instructions posted where people act quickly.",
    targetId: "plain-language",
    text: `Wear eye protection in this area at all times. Keep the walkway clear. Report any spill right away. Do not use a machine unless you have been trained on it. In an emergency, press the red stop button and leave through the nearest exit.`,
  },
  {
    id: "school-newsletter",
    label: "School newsletter",
    description: "A parent update pitched at a general reading level.",
    targetId: "general-web",
    text: `Sports day is on Friday the fourteenth. Pupils should arrive in school uniform and bring a change of clothes. Events begin at ten in the morning and finish by two. Parents are welcome to watch from the field edge. If the weather is poor, we will move the day to the following Tuesday and send a message that morning.`,
  },
  {
    id: "study-material",
    label: "Study material",
    description: "Classroom explanation aimed at readers around grades 7 to 9.",
    targetId: "middle-school",
    text: `Photosynthesis is the process a plant uses to make its own food. The leaves take in carbon dioxide from the air, and the roots pull water up from the soil. Using energy from sunlight, the plant combines these two ingredients into sugar. Oxygen is released as a by-product, which is why forests matter so much to the air we breathe.`,
  },
  {
    id: "terms-of-service",
    label: "Terms excerpt",
    description: "Legal-style prose that usually scores far above its intended audience.",
    targetId: "general-web",
    text: `The subscriber acknowledges that continued utilisation of the platform subsequent to the effective date of any modification to these terms shall constitute acceptance of such modification in its entirety. In the event that any provision herein is determined to be unenforceable by a court of competent jurisdiction, the remaining provisions shall nevertheless continue in full force and effect to the maximum extent permissible under applicable law.`,
  },
  {
    id: "job-description",
    label: "Job description",
    description: "A role advert written for professional readers without unnecessary jargon.",
    targetId: "professional",
    text: `We are looking for a frontend engineer to join a small product team. You will build accessible interfaces, review pull requests from colleagues, and help shape how we approach performance. We expect solid experience with a modern component framework and a habit of writing tests alongside features. Experience with design systems is helpful but not required.`,
  },
  {
    id: "grant-proposal",
    label: "Grant proposal",
    description: "Funding prose that reviewers expect to be formal but still readable.",
    targetId: "professional",
    text: `This project will expand access to after-school literacy support in three underserved districts. Over eighteen months, we will train twenty volunteer tutors, deliver weekly sessions to approximately two hundred pupils, and measure progress using a standard reading assessment administered at intake and at completion. Funds will cover tutor training, learning materials, and part-time coordination.`,
  },
  {
    id: "news-summary",
    label: "News summary",
    description: "A short factual report of the kind wire services publish.",
    targetId: "general-web",
    text: `The city council approved the new bus route on Tuesday evening. The route will connect the eastern suburbs to the central station and is expected to open in March. Officials said the service will run every fifteen minutes during peak hours. Two councillors voted against the plan, arguing that the funding would be better spent on repairing existing roads.`,
  },
  {
    id: "recipe-steps",
    label: "Recipe steps",
    description: "Sequential instructions that should stay short and concrete.",
    targetId: "plain-language",
    text: `Heat the oven to 200 degrees. Cut the potatoes into small cubes. Toss them with oil and salt. Spread them on a tray in a single layer. Roast for twenty-five minutes. Turn them once halfway through. They are ready when the edges are golden and a fork goes in easily.`,
  },
  {
    id: "api-changelog",
    label: "API changelog",
    description: "Developer-facing notes where some technical density is expected.",
    targetId: "professional",
    text: `The list endpoint now returns a cursor instead of an offset. Existing offset parameters continue to work until the next major version, but they are deprecated and will emit a warning header. Clients should read the next_cursor value from each response and pass it back unchanged. Rate limits are unchanged, and no authentication changes are required.`,
  },
  {
    id: "literature-review",
    label: "Literature review",
    description: "Long academic sentences that push grade level well above general reading.",
    targetId: "academic",
    text: `Contemporary scholarship on distributed cognition has increasingly problematised the assumption that individual working memory constitutes the primary constraint on collaborative problem solving, suggesting instead that representational artefacts and the social distribution of expertise mediate performance in ways that resist straightforward decomposition. Subsequent empirical work has nonetheless produced heterogeneous findings, partly attributable to methodological divergence in how coordination overhead is operationalised across laboratory and field settings.`,
  },
];

export function getReadabilityTarget(id: ReadabilityTarget["id"]): ReadabilityTarget {
  return READABILITY_TARGETS.find((target) => target.id === id) ?? READABILITY_TARGETS[1]!;
}
