import type { SlugPreset } from "./types";

export const SLUG_PRESETS: SlugPreset[] = [
  {
    id: "blog-launch",
    name: "Blog launch",
    description: "Generate concise article routes and preserve previous paths for redirects.",
    mode: "bulk",
    input: "How to Build Better Browser Tools\t/blog/browser-tools-guide\nA Practical Guide to URL Design\t/blog/url-design\nThe Future of Local-First Utilities",
    pathPrefix: "/blog",
    collisionMode: "suffix",
    options: { removeStopWords: true, maxLengthEnabled: true, maxLength: 64 },
  },
  {
    id: "product-catalog",
    name: "Product catalog",
    description: "Keep model numbers and resolve repeated product names automatically.",
    mode: "bulk",
    input: "Wireless Keyboard K2\nWireless Keyboard K2\nUSB-C Dock 12-in-1\n27-inch 4K Monitor",
    pathPrefix: "/products",
    collisionMode: "suffix",
    options: { keepNumbers: true, maxLengthEnabled: true, maxLength: 72 },
  },
  {
    id: "docs-routes",
    name: "Documentation paths",
    description: "Preserve nested slash-separated documentation sections.",
    mode: "bulk",
    input: "getting started/installation\ngetting started/environment setup\napi/authentication/oauth 2\napi/authentication/api keys",
    pathPrefix: "/docs",
    collisionMode: "error",
    options: { preserveSlashes: true, removeStopWords: false, maxLengthEnabled: true, maxLength: 96 },
  },
  {
    id: "multilingual",
    name: "Multilingual routes",
    description: "Keep Arabic and other Unicode letters in readable URL slugs.",
    mode: "bulk",
    input: "أفضل أدوات المطورين\nدليل تحسين محركات البحث\nCafé Déjà Vu\n東京 開発 ガイド",
    pathPrefix: "/articles",
    collisionMode: "suffix",
    options: { asciiOnly: false, maxLengthEnabled: true, maxLength: 80 },
  },
  {
    id: "cms-migration",
    name: "CMS migration",
    description: "Create a redirect-ready route manifest from tab-separated old paths.",
    mode: "bulk",
    input: "Company About Page\t/about-us-old\nCustomer Success Stories\t/case-studies\nPricing and Plans\t/plans-and-pricing",
    pathPrefix: "",
    collisionMode: "error",
    options: { removeStopWords: true, maxLengthEnabled: true, maxLength: 64 },
  },
  {
    id: "ascii-handles",
    name: "ASCII handles",
    description: "Generate lowercase ASCII identifiers for systems that reject Unicode paths.",
    mode: "bulk",
    input: "Résumé Builder Pro\nCrème Brûlée Recipe\nÜber Analytics 2026\nDeveloper Portal",
    pathPrefix: "/apps",
    collisionMode: "suffix",
    options: { asciiOnly: true, keepNumbers: true, maxLengthEnabled: true, maxLength: 48 },
  },
  {
    id: "newsroom",
    name: "Newsroom routes",
    description: "Create concise story slugs while keeping dates and important numbers.",
    mode: "bulk",
    input: "Q3 Results: Revenue Up 18%\nRelease Notes 2026.09\n10 Product Updates Shipping This Week",
    pathPrefix: "/news",
    collisionMode: "suffix",
    options: { keepNumbers: true, removeStopWords: true, maxLengthEnabled: true, maxLength: 72 },
  },
  {
    id: "help-center",
    name: "Help center",
    description: "Generate readable support article routes from question-style titles.",
    mode: "bulk",
    input: "How do I reset my password?\nWhy is my payment pending?\nWhere can I download invoices?",
    pathPrefix: "/help",
    collisionMode: "suffix",
    options: { removeStopWords: true, maxLengthEnabled: true, maxLength: 64 },
  },
  {
    id: "event-pages",
    name: "Event pages",
    description: "Keep event years and edition numbers in stable public URLs.",
    mode: "bulk",
    input: "Developer Summit 2027\nDesign Week 2027\nCommunity Meetup #12",
    pathPrefix: "/events",
    collisionMode: "suffix",
    options: { keepNumbers: true, maxLengthEnabled: true, maxLength: 72 },
  },
  {
    id: "course-library",
    name: "Course library",
    description: "Create structured learning routes for course catalog titles.",
    mode: "bulk",
    input: "Introduction to TypeScript\nAdvanced CSS Layouts\nProduct Analytics Fundamentals",
    pathPrefix: "/courses",
    collisionMode: "suffix",
    options: { removeStopWords: true, maxLengthEnabled: true, maxLength: 72 },
  },
  {
    id: "job-board",
    name: "Job board",
    description: "Turn role titles into readable job listing routes.",
    mode: "bulk",
    input: "Senior Frontend Engineer\nProduct Designer — Growth\nData Analyst (Remote)",
    pathPrefix: "/jobs",
    collisionMode: "suffix",
    options: { removeStopWords: false, maxLengthEnabled: true, maxLength: 72 },
  },
  {
    id: "category-taxonomy",
    name: "Category taxonomy",
    description: "Generate stable category paths and surface duplicate names.",
    mode: "bulk",
    input: "Home & Garden\nDeveloper Tools\nDeveloper Tools\nArts & Culture",
    pathPrefix: "/categories",
    collisionMode: "error",
    options: { removeStopWords: false, maxLengthEnabled: true, maxLength: 56 },
  },
  {
    id: "user-generated-titles",
    name: "User-generated titles",
    description: "Normalize punctuation-heavy titles while preserving useful Unicode letters.",
    mode: "bulk",
    input: "My setup!!! 2027 edition ✨\nCafé recommendations — القدس\nWhat’s new in v3.2?",
    pathPrefix: "/posts",
    collisionMode: "suffix",
    options: { asciiOnly: false, keepNumbers: true, maxLengthEnabled: true, maxLength: 80 },
  },
  {
    id: "api-resource-names",
    name: "API resource names",
    description: "Create ASCII-safe resource identifiers using underscores instead of hyphens.",
    mode: "bulk",
    input: "Payment Events\nUser Preferences\nAudit Log Entries",
    pathPrefix: "",
    collisionMode: "error",
    options: { asciiOnly: true, removeStopWords: false, maxLengthEnabled: true, maxLength: 48, separator: "_" },
  },
  {
    id: "campaign-pages",
    name: "Campaign pages",
    description: "Create short marketing routes from long campaign names.",
    mode: "bulk",
    input: "Build Better Workflows With Darma\nSummer Product Launch 2027\nFree Developer Utilities for Teams",
    pathPrefix: "/campaigns",
    collisionMode: "suffix",
    options: { removeStopWords: true, maxLengthEnabled: true, maxLength: 48 },
  },
  {
    id: "redirect-audit",
    name: "Redirect audit",
    description: "Generate replacement paths while retaining old URLs for migration review.",
    mode: "bulk",
    input: "About Our Company\t/about\nDeveloper Documentation\t/dev-docs\nContact Sales Team\t/contact-us",
    pathPrefix: "",
    collisionMode: "error",
    options: { removeStopWords: true, maxLengthEnabled: true, maxLength: 64 },
  },
  {
    id: "localized-arabic",
    name: "Arabic content routes",
    description: "Keep Arabic words readable while cleaning punctuation and spacing.",
    mode: "bulk",
    input: "دليل أدوات المطورين المجانية\nكيفية تحسين أداء الموقع\nأفضل ممارسات تجربة المستخدم",
    pathPrefix: "/ar",
    collisionMode: "suffix",
    options: { asciiOnly: false, maxLengthEnabled: true, maxLength: 80 },
  },
  {
    id: "single-clean-title",
    name: "Single clean title",
    description: "Start from one title when you only need a clean route quickly.",
    mode: "single",
    input: "A Practical Guide to Better URLs in 2027",
    pathPrefix: "/guides",
    collisionMode: "suffix",
    options: { removeStopWords: true, keepNumbers: true, maxLengthEnabled: true, maxLength: 64 },
  },

];

export const DEFAULT_SLUG_PRESET_ID = "blog-launch";
