import type { PercentPreset } from "./types";

export const DEFAULT_PERCENT_PRESET_ID = "sale-discount";

export const PERCENT_PRESETS: PercentPreset[] = [
  {
    id: "sale-discount",
    name: "Sale discount",
    description: "Find the final price and savings after a 25% discount.",
    mode: "discount",
    a: 120,
    b: 25,
  },
  {
    id: "growth-rate",
    name: "Growth rate",
    description: "Measure a metric moving from 1,200 to 1,560.",
    mode: "change",
    a: 1200,
    b: 1560,
  },
  {
    id: "reverse-raise",
    name: "Reverse a raise",
    description: "Recover the original salary before an 8% increase.",
    mode: "reverseChange",
    a: 54000,
    b: 8,
  },
  {
    id: "conversion-rate",
    name: "Conversion rate",
    description: "Calculate what percent 186 conversions are of 4,250 visits.",
    mode: "isWhatPercent",
    a: 186,
    b: 4250,
  },
  {
    id: "markup-margin",
    name: "Markup & margin",
    description: "Compare a 45 cost with a 72 selling price.",
    mode: "markupMargin",
    a: 45,
    b: 72,
  },
  {
    id: "measurement-gap",
    name: "Percent difference",
    description: "Compare two peer measurements without a baseline.",
    mode: "percentDifference",
    a: 98.4,
    b: 103.1,
  },
  {
    id: "tax-addition",
    name: "Add sales tax",
    description: "Add 8.25% tax to a 79.99 purchase.",
    mode: "applyChange",
    a: 79.99,
    b: 8.25,
  },
  {
    id: "tip-percent",
    name: "Restaurant tip",
    description: "Find 18% of a 64.50 restaurant bill.",
    mode: "of",
    a: 18,
    b: 64.5,
  },
  {
    id: "budget-share",
    name: "Budget share",
    description: "See what percent a 2,750 line item is of a 12,000 budget.",
    mode: "isWhatPercent",
    a: 2750,
    b: 12000,
  },
  {
    id: "traffic-drop",
    name: "Traffic drop",
    description: "Measure visits falling from 48,000 to 39,600.",
    mode: "change",
    a: 48000,
    b: 39600,
  },
  {
    id: "price-increase",
    name: "Apply price increase",
    description: "Apply a 6.5% increase to a 249 subscription price.",
    mode: "applyChange",
    a: 249,
    b: 6.5,
  },
  {
    id: "reverse-discount",
    name: "Original before discount",
    description: "Recover the original value when 84 represents a 30% reduction.",
    mode: "reverseChange",
    a: 84,
    b: -30,
  },
  {
    id: "campaign-ctr",
    name: "Campaign CTR",
    description: "Calculate 1,245 clicks as a percentage of 72,500 impressions.",
    mode: "isWhatPercent",
    a: 1245,
    b: 72500,
  },
  {
    id: "sla-improvement",
    name: "SLA improvement",
    description: "Measure response time improving from 42 minutes to 31 minutes.",
    mode: "change",
    a: 42,
    b: 31,
  },
  {
    id: "portfolio-return",
    name: "Portfolio return",
    description: "Measure a portfolio moving from 18,500 to 20,350.",
    mode: "change",
    a: 18500,
    b: 20350,
  },
  {
    id: "wholesale-margin",
    name: "Wholesale margin",
    description: "Compare an 18.40 unit cost with a 29.95 retail price.",
    mode: "markupMargin",
    a: 18.4,
    b: 29.95,
  },
  {
    id: "ab-test-gap",
    name: "A/B test gap",
    description: "Compare two peer conversion rates, 4.8 and 5.3, without treating either as baseline.",
    mode: "percentDifference",
    a: 4.8,
    b: 5.3,
  },
  {
    id: "capacity-used",
    name: "Capacity used",
    description: "Calculate 73 as a percentage of a 120-seat capacity.",
    mode: "isWhatPercent",
    a: 73,
    b: 120,
  },

];
