import type { HarmonyMode, PalettePreset, PaletteSize } from "./types";

export const HARMONY_OPTIONS: Array<{ value: HarmonyMode; label: string; description: string }> = [
  { value: "monochromatic", label: "Monochromatic", description: "One hue with varied saturation and lightness. Best for calm UI systems." },
  { value: "analogous", label: "Analogous", description: "Neighboring hues for cohesive websites, dashboards, and brand visuals." },
  { value: "complementary", label: "Complementary", description: "Opposite hues for strong accent contrast and hero sections." },
  { value: "split-complementary", label: "Split complementary", description: "A base hue plus two softer opposite accents. Flexible for branding." },
  { value: "triadic", label: "Triadic", description: "Three evenly spaced hues with balanced visual energy." },
  { value: "tetradic", label: "Tetradic", description: "Two complementary pairs for rich campaigns and illustrations." },
  { value: "shades", label: "Shades", description: "Same hue stepping down through progressively darker tones." },
  { value: "tints", label: "Tints", description: "Same hue stepping up through progressively lighter tones." },
];

export const PALETTE_SIZE_OPTIONS: Array<{ value: PaletteSize; label: string }> = [
  { value: 3, label: "3 colors" },
  { value: 5, label: "5 colors" },
  { value: 7, label: "7 colors" },
  { value: 9, label: "9 colors" },
];

export const STARTER_COLORS = [
  "#2563EB",
  "#7C3AED",
  "#059669",
  "#EA580C",
  "#DB2777",
  "#0F172A",
  "#0891B2",
  "#CA8A04",
  "#DC2626",
  "#0D9488",
];

export const PALETTE_PRESETS: PalettePreset[] = [
  {
    id: "website",
    title: "Website UI",
    description: "Balanced colors for landing pages, dashboards, and content sites.",
    baseColor: "#2563EB",
    harmony: "analogous",
    size: 7,
    uiMode: "light",
    tags: ["UI", "SaaS"],
  },
  {
    id: "social-media",
    title: "Social post",
    description: "Energetic tones for posts, thumbnails, and creator graphics.",
    baseColor: "#DB2777",
    harmony: "triadic",
    size: 5,
    uiMode: "light",
    tags: ["Creator", "Bold"],
  },
  {
    id: "brand",
    title: "Brand system",
    description: "A flexible identity palette with primary, accent, and support colors.",
    baseColor: "#7C3AED",
    harmony: "split-complementary",
    size: 7,
    uiMode: "light",
    tags: ["Identity", "Tokens"],
  },
  {
    id: "dark-ui",
    title: "Dark app",
    description: "Deep surfaces and readable accents for dark interfaces.",
    baseColor: "#0F172A",
    harmony: "tints",
    size: 7,
    uiMode: "dark",
    tags: ["Dark", "Product"],
  },
  {
    id: "luxury",
    title: "Luxury editorial",
    description: "Premium warm tones for fashion, packaging, and high-end visuals.",
    baseColor: "#7F1D1D",
    harmony: "analogous",
    size: 5,
    uiMode: "light",
    tags: ["Premium", "Warm"],
  },
  {
    id: "nature",
    title: "Nature brand",
    description: "Organic greens and support colors for wellness, food, and environment.",
    baseColor: "#15803D",
    harmony: "split-complementary",
    size: 7,
    uiMode: "light",
    tags: ["Natural", "Fresh"],
  },
  {
    id: "saas-dashboard",
    title: "SaaS dashboard",
    description: "Cool product blues with enough accent range for navigation, charts, and status UI.",
    baseColor: "#4F46E5",
    harmony: "analogous",
    size: 7,
    uiMode: "light",
    tags: ["Dashboard", "Product"],
  },
  {
    id: "fintech",
    title: "Fintech product",
    description: "Trust-oriented blue and teal relationships for balances, transactions, and finance dashboards.",
    baseColor: "#0369A1",
    harmony: "split-complementary",
    size: 7,
    uiMode: "light",
    tags: ["Finance", "Trust"],
  },
  {
    id: "ecommerce",
    title: "E-commerce",
    description: "Commercial palette with a strong CTA accent and enough support colors for product states.",
    baseColor: "#C2410C",
    harmony: "split-complementary",
    size: 7,
    uiMode: "light",
    tags: ["Shop", "CTA"],
  },
  {
    id: "healthcare",
    title: "Healthcare",
    description: "Calm teal-led colors for appointment, wellness, and patient-facing interfaces.",
    baseColor: "#0F766E",
    harmony: "analogous",
    size: 7,
    uiMode: "light",
    tags: ["Health", "Calm"],
  },
  {
    id: "education",
    title: "Education app",
    description: "Friendly blue-violet palette for lessons, progress, quizzes, and learning dashboards.",
    baseColor: "#4338CA",
    harmony: "triadic",
    size: 7,
    uiMode: "light",
    tags: ["Learning", "Friendly"],
  },
  {
    id: "developer-tool",
    title: "Developer tool",
    description: "Technical dark-mode palette with readable cyan accents for editors and utility interfaces.",
    baseColor: "#0F172A",
    harmony: "tints",
    size: 9,
    uiMode: "dark",
    tags: ["Developer", "Dark"],
  },
  {
    id: "creator-portfolio",
    title: "Creator portfolio",
    description: "Expressive purple and pink relationships for case studies, portfolios, and personal brands.",
    baseColor: "#9333EA",
    harmony: "analogous",
    size: 7,
    uiMode: "light",
    tags: ["Portfolio", "Creative"],
  },
  {
    id: "editorial",
    title: "Editorial",
    description: "Restrained ink-like tones for magazines, newsletters, and reading-first experiences.",
    baseColor: "#334155",
    harmony: "monochromatic",
    size: 7,
    uiMode: "light",
    tags: ["Editorial", "Reading"],
  },
  {
    id: "restaurant",
    title: "Restaurant",
    description: "Warm appetizing tones for menus, reservations, food brands, and hospitality pages.",
    baseColor: "#B45309",
    harmony: "analogous",
    size: 7,
    uiMode: "light",
    tags: ["Food", "Warm"],
  },
  {
    id: "travel",
    title: "Travel experience",
    description: "Fresh ocean-led colors for booking flows, destination pages, and travel marketing.",
    baseColor: "#0284C7",
    harmony: "split-complementary",
    size: 7,
    uiMode: "light",
    tags: ["Travel", "Fresh"],
  },
  {
    id: "high-contrast",
    title: "High-contrast UI",
    description: "A compact palette intended to make foreground/background contrast choices easier to inspect.",
    baseColor: "#111827",
    harmony: "tints",
    size: 5,
    uiMode: "light",
    tags: ["Accessibility", "Contrast"],
  },
  {
    id: "data-visualization",
    title: "Data visualization",
    description: "Multi-hue set for charts and analytics where several categories need visible separation.",
    baseColor: "#2563EB",
    harmony: "tetradic",
    size: 9,
    uiMode: "light",
    tags: ["Charts", "Analytics"],
  },
];
