import type { LoanOptions, LoanPreset, LoanScenarioInput } from "./types";

export const DEFAULT_LOAN_INPUT: LoanScenarioInput = {
  amount: 30000,
  downPayment: 5000,
  financedFees: 700,
  annualRate: 6.25,
  termMonths: 60,
  extraMonthlyPayment: 0,
  oneTimeExtraPayment: 0,
  oneTimeExtraMonth: 12,
  startDate: "2026-08-01",
};

export const DEFAULT_LOAN_OPTIONS: LoanOptions = {
  currency: "USD",
  precision: 2,
};

export const LOAN_PRESETS: LoanPreset[] = [
  {
    id: "car-loan",
    name: "Car loan",
    description: "Five-year vehicle financing with a down payment and financed fees.",
    input: { ...DEFAULT_LOAN_INPUT },
  },
  {
    id: "mortgage",
    name: "Home mortgage",
    description: "Thirty-year mortgage with a 20% down payment.",
    input: {
      amount: 320000,
      downPayment: 64000,
      financedFees: 4500,
      annualRate: 5.75,
      termMonths: 360,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "accelerated-mortgage",
    name: "Accelerated mortgage",
    description: "Compare a recurring extra payment against a standard mortgage.",
    input: {
      amount: 320000,
      downPayment: 64000,
      financedFees: 4500,
      annualRate: 5.75,
      termMonths: 360,
      extraMonthlyPayment: 250,
      oneTimeExtraPayment: 2500,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "student-loan",
    name: "Student loan",
    description: "Ten-year education loan without a down payment.",
    input: {
      amount: 45000,
      downPayment: 0,
      financedFees: 0,
      annualRate: 4.8,
      termMonths: 120,
      extraMonthlyPayment: 75,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "personal-loan",
    name: "Personal loan",
    description: "Three-year unsecured loan with a higher fixed rate.",
    input: {
      amount: 12000,
      downPayment: 0,
      financedFees: 300,
      annualRate: 11.9,
      termMonths: 36,
      extraMonthlyPayment: 50,
      oneTimeExtraPayment: 500,
      oneTimeExtraMonth: 6,
      startDate: "2026-08-01",
    },
  },
  {
    id: "zero-interest",
    name: "Zero-interest plan",
    description: "A simple installment plan with no interest.",
    input: {
      amount: 2400,
      downPayment: 400,
      financedFees: 0,
      annualRate: 0,
      termMonths: 12,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 6,
      startDate: "2026-08-01",
    },
  },
  {
    id: "used-car",
    name: "Used car, short term",
    description: "A three-year used-car loan at a higher rate than new-car financing.",
    input: {
      amount: 14500,
      downPayment: 2000,
      financedFees: 450,
      annualRate: 9.4,
      termMonths: 36,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "first-home",
    name: "First home, low deposit",
    description: "A 25-year mortgage with a 5% deposit and financed closing costs.",
    input: {
      amount: 265000,
      downPayment: 13250,
      financedFees: 6800,
      annualRate: 6.1,
      termMonths: 300,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "fifteen-year-mortgage",
    name: "15-year vs 30-year",
    description: "A shorter mortgage term to compare total interest against the 30-year preset.",
    input: {
      amount: 320000,
      downPayment: 64000,
      financedFees: 4500,
      annualRate: 5.35,
      termMonths: 180,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "refinance-check",
    name: "Refinance check",
    description: "A remaining balance at a lower rate, to compare against the current loan.",
    input: {
      amount: 214000,
      downPayment: 0,
      financedFees: 3200,
      annualRate: 4.95,
      termMonths: 240,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "debt-consolidation",
    name: "Debt consolidation",
    description: "Combining several balances into one five-year fixed payment.",
    input: {
      amount: 24000,
      downPayment: 0,
      financedFees: 600,
      annualRate: 10.5,
      termMonths: 60,
      extraMonthlyPayment: 100,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "credit-card-payoff",
    name: "Credit card payoff plan",
    description: "A high-rate balance treated as a fixed two-year payoff schedule.",
    input: {
      amount: 8200,
      downPayment: 0,
      financedFees: 0,
      annualRate: 22.9,
      termMonths: 24,
      extraMonthlyPayment: 120,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 6,
      startDate: "2026-08-01",
    },
  },
  {
    id: "small-business",
    name: "Small business loan",
    description: "Seven-year equipment and working-capital financing with an origination fee.",
    input: {
      amount: 85000,
      downPayment: 10000,
      financedFees: 2100,
      annualRate: 8.75,
      termMonths: 84,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "home-improvement",
    name: "Home improvement",
    description: "A six-year renovation loan repaid faster with a modest extra payment.",
    input: {
      amount: 32000,
      downPayment: 0,
      financedFees: 500,
      annualRate: 7.4,
      termMonths: 72,
      extraMonthlyPayment: 150,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "motorcycle-loan",
    name: "Motorcycle or scooter",
    description: "A small four-year vehicle loan with a modest deposit.",
    input: {
      amount: 9500,
      downPayment: 1500,
      financedFees: 250,
      annualRate: 8.2,
      termMonths: 48,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "bonus-lump-sum",
    name: "Annual bonus lump sum",
    description: "A single large payment in month 12 to see how much interest one lump sum saves.",
    input: {
      amount: 42000,
      downPayment: 0,
      financedFees: 0,
      annualRate: 7.1,
      termMonths: 84,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 6000,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
  {
    id: "buy-now-pay-later",
    name: "Retail installment plan",
    description: "A short interest-bearing retail plan, useful for comparing against 0% offers.",
    input: {
      amount: 1800,
      downPayment: 200,
      financedFees: 45,
      annualRate: 15.9,
      termMonths: 18,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 6,
      startDate: "2026-08-01",
    },
  },
  {
    id: "graduate-loan-long",
    name: "Graduate loan, 20-year",
    description: "A long education loan where small rate changes move total interest sharply.",
    input: {
      amount: 96000,
      downPayment: 0,
      financedFees: 0,
      annualRate: 5.6,
      termMonths: 240,
      extraMonthlyPayment: 0,
      oneTimeExtraPayment: 0,
      oneTimeExtraMonth: 12,
      startDate: "2026-08-01",
    },
  },
];

/**
 * Grouping for the scenario picker. Every id must exist in LOAN_PRESETS; the
 * picker skips anything it cannot resolve rather than rendering a dead option.
 */
export const LOAN_PRESET_GROUPS: Array<{ label: string; presetIds: string[] }> = [
  { label: "Home", presetIds: ["mortgage", "first-home", "fifteen-year-mortgage", "accelerated-mortgage", "refinance-check", "home-improvement"] },
  { label: "Vehicle", presetIds: ["car-loan", "used-car", "motorcycle-loan"] },
  { label: "Education", presetIds: ["student-loan", "graduate-loan-long"] },
  { label: "Personal and debt", presetIds: ["personal-loan", "debt-consolidation", "credit-card-payoff", "bonus-lump-sum"] },
  { label: "Retail and business", presetIds: ["zero-interest", "buy-now-pay-later", "small-business"] },
];
