import type { AnimatedBackgroundState, BackgroundPreset, BackgroundPresetId } from "@/types/animatedBackgroundTypes";

export const presets: BackgroundPreset[] = [
  { id: "saas-hero-gradient", name: "SaaS Hero Gradient", description: "A polished animated hero background for startups, product launches, and modern SaaS landing pages.", tags: ["SaaS", "Hero", "Gradient"], bestFor: ["SaaS landing pages", "Product launches", "Startup homepages"], searchIntent: "animated hero background css", seed: 8241, colors: ["#38bdf8", "#6366f1", "#a855f7", "#22c55e"], background: "#020617", shape: "circle", particleCount: 13, minSize: 180, maxSize: 560, blur: 78, opacity: 0.5, speed: 0.7, intensity: 0.82, glow: 68, blendMode: "screen", borderRadius: 999, gradientStyle: "mesh" },
  { id: "ai-neural-glow", name: "AI Neural Background", description: "Glowing neural nodes and soft depth for AI tools, agents, automation platforms, and ML demos.", tags: ["AI", "Neural", "Tech"], bestFor: ["AI product pages", "Agent demos", "Automation tools"], searchIntent: "ai website background css", seed: 9286, colors: ["#22d3ee", "#818cf8", "#c084fc", "#67e8f9"], background: "#030712", shape: "circle", particleCount: 28, minSize: 8, maxSize: 56, blur: 5, opacity: 0.72, speed: 0.84, intensity: 0.7, glow: 42, blendMode: "screen", borderRadius: 999, gradientStyle: "mesh" },
  { id: "portfolio-minimal-glow", name: "Portfolio Minimal Glow", description: "Elegant low-motion glow for personal websites, case studies, and creative portfolios.", tags: ["Portfolio", "Minimal", "Glow"], bestFor: ["Designer portfolios", "Case studies", "Personal websites"], searchIntent: "portfolio background animation", seed: 4208, colors: ["#f8fafc", "#bae6fd", "#ddd6fe", "#fecdd3"], background: "#0f172a", shape: "circle", particleCount: 7, minSize: 260, maxSize: 720, blur: 118, opacity: 0.33, speed: 0.42, intensity: 0.38, glow: 28, blendMode: "overlay", borderRadius: 999, gradientStyle: "mesh" },
  { id: "dark-dashboard-ambient", name: "Dark Dashboard Ambient", description: "Subtle glassy cells and controlled movement for admin panels, analytics pages, and app shells.", tags: ["Dashboard", "Dark UI", "Ambient"], bestFor: ["Dashboards", "Analytics pages", "Admin panels"], searchIntent: "dark dashboard background", seed: 1776, colors: ["#38bdf8", "#5eead4", "#818cf8", "#e0f2fe"], background: "#0b1120", shape: "soft-square", particleCount: 16, minSize: 64, maxSize: 240, blur: 20, opacity: 0.38, speed: 0.56, intensity: 0.52, glow: 24, blendMode: "screen", borderRadius: 34, gradientStyle: "mesh" },
  { id: "startup-launch-mesh", name: "Startup Launch Mesh", description: "Warm, premium launch-page mesh gradient with enough motion to feel alive without distracting users.", tags: ["Startup", "Launch", "Mesh"], bestFor: ["Launch pages", "Waitlists", "Marketing sites"], searchIntent: "mesh gradient hero background", seed: 5150, colors: ["#fb7185", "#f97316", "#facc15", "#a855f7"], background: "#1e1b4b", shape: "soft-square", particleCount: 11, minSize: 180, maxSize: 560, blur: 92, opacity: 0.46, speed: 0.6, intensity: 0.62, glow: 62, blendMode: "plus-lighter", borderRadius: 36, gradientStyle: "mesh" },
  { id: "neon-cyber-grid", name: "Neon Cyber Grid", description: "A sharp futuristic grid for developer tools, security pages, game landing pages, and cyber visuals.", tags: ["Cyber", "Grid", "Neon"], bestFor: ["Developer tools", "Security pages", "Gaming websites"], searchIntent: "neon cyber grid background css", seed: 1209, colors: ["#22d3ee", "#2563eb", "#a855f7", "#67e8f9"], background: "#020617", shape: "circle", particleCount: 24, minSize: 7, maxSize: 36, blur: 2, opacity: 0.72, speed: 0.9, intensity: 0.58, glow: 34, blendMode: "screen", borderRadius: 999, gradientStyle: "linear" },
  { id: "galaxy-particle-field", name: "Galaxy Particle Field", description: "Deep space particle drift for launches, creative tech, futuristic apps, and immersive hero sections.", tags: ["Galaxy", "Particles", "Space"], bestFor: ["Product launches", "Immersive heroes", "Creative tech"], searchIntent: "star particle background css", seed: 8088, colors: ["#bfdbfe", "#c4b5fd", "#f5d0fe", "#ffffff"], background: "#020617", shape: "circle", particleCount: 44, minSize: 3, maxSize: 18, blur: 1, opacity: 0.74, speed: 0.64, intensity: 0.42, glow: 22, blendMode: "screen", borderRadius: 999, gradientStyle: "radial" },
  { id: "liquid-blur-bubbles", name: "Liquid Blur Bubbles", description: "Fresh glossy bubbles for wellness, fintech, mobile apps, and friendly product pages.", tags: ["Liquid", "Bubbles", "Fresh"], bestFor: ["Mobile apps", "Fintech pages", "Wellness brands"], searchIntent: "liquid bubble background css", seed: 3324, colors: ["#06b6d4", "#2dd4bf", "#67e8f9", "#a7f3d0"], background: "#042f2e", shape: "circle", particleCount: 18, minSize: 56, maxSize: 180, blur: 12, opacity: 0.5, speed: 0.82, intensity: 0.85, glow: 38, blendMode: "screen", borderRadius: 999, gradientStyle: "mesh" },
  { id: "designer-hero-section", name: "Designer Hero Section", description: "Editorial, soft, and high-end background treatment for design studios and visual portfolios.", tags: ["Design", "Editorial", "Hero"], bestFor: ["Design studios", "Creative agencies", "Visual portfolios"], searchIntent: "creative hero background css", seed: 6198, colors: ["#f0abfc", "#c084fc", "#93c5fd", "#fda4af"], background: "#18181b", shape: "soft-square", particleCount: 10, minSize: 220, maxSize: 640, blur: 104, opacity: 0.42, speed: 0.48, intensity: 0.5, glow: 40, blendMode: "screen", borderRadius: 42, gradientStyle: "mesh" },
  { id: "fintech-data-grid", name: "Fintech Data Grid", description: "Clean blue-green grid glow for finance dashboards, data products, and B2B platforms.", tags: ["Fintech", "Data", "Grid"], bestFor: ["Fintech dashboards", "B2B SaaS", "Data products"], searchIntent: "finance dashboard background css", seed: 2459, colors: ["#22c55e", "#14b8a6", "#38bdf8", "#2563eb"], background: "#031014", shape: "diamond", particleCount: 30, minSize: 6, maxSize: 44, blur: 3, opacity: 0.62, speed: 0.78, intensity: 0.5, glow: 30, blendMode: "screen", borderRadius: 12, gradientStyle: "linear" },
  { id: "agency-sunset-ribbons", name: "Agency Sunset Ribbons", description: "High-energy warm ribbons for agencies, event pages, creator products, and bold landing pages.", tags: ["Agency", "Ribbons", "Warm"], bestFor: ["Agency sites", "Event pages", "Creator launches"], searchIntent: "animated gradient ribbons css", seed: 5419, colors: ["#fb7185", "#f59e0b", "#f97316", "#ec4899"], background: "#2e1065", shape: "soft-square", particleCount: 13, minSize: 90, maxSize: 300, blur: 58, opacity: 0.5, speed: 0.9, intensity: 1.05, glow: 52, blendMode: "screen", borderRadius: 24, gradientStyle: "linear" },
  { id: "developer-terminal-matrix", name: "Developer Terminal Matrix", description: "Terminal-inspired digital rain for code tools, CLI projects, developer portfolios, and hacker themes.", tags: ["Developer", "Terminal", "Matrix"], bestFor: ["CLI tools", "Developer portfolios", "Hackathon projects"], searchIntent: "matrix rain background css", seed: 6110, colors: ["#22c55e", "#84cc16", "#10b981", "#bbf7d0"], background: "#020403", shape: "diamond", particleCount: 36, minSize: 5, maxSize: 30, blur: 2, opacity: 0.64, speed: 1.18, intensity: 1.2, glow: 26, blendMode: "screen", borderRadius: 12, gradientStyle: "linear" },
  { id: "glassmorphism-orbs", name: "Glassmorphism Orbs", description: "Glassy layered orbs for premium cards, pricing pages, and modern landing sections.", tags: ["Glass", "Orbs", "Premium"], bestFor: ["Pricing sections", "Landing cards", "Modern UI kits"], searchIntent: "glassmorphism background css", seed: 7812, colors: ["#60a5fa", "#c084fc", "#f472b6", "#67e8f9"], background: "#0f172a", shape: "circle", particleCount: 14, minSize: 90, maxSize: 260, blur: 36, opacity: 0.46, speed: 0.88, intensity: 0.75, glow: 48, blendMode: "screen", borderRadius: 999, gradientStyle: "radial" },
  { id: "premium-noise-glow", name: "Premium Noise Glow", description: "Minimal grain, cinematic glow, and restrained movement for editorial product pages.", tags: ["Noise", "Minimal", "Premium"], bestFor: ["Editorial pages", "Product storytelling", "Minimal brands"], searchIntent: "soft noise gradient background", seed: 9903, colors: ["#f8fafc", "#bae6fd", "#ddd6fe", "#fecdd3"], background: "#111827", shape: "circle", particleCount: 7, minSize: 260, maxSize: 680, blur: 110, opacity: 0.32, speed: 0.44, intensity: 0.38, glow: 28, blendMode: "overlay", borderRadius: 999, gradientStyle: "mesh" },
];

export const getPreset = (id: BackgroundPresetId) => presets.find((preset) => preset.id === id) ?? presets[0];

export const presetToState = (preset: BackgroundPreset): AnimatedBackgroundState => ({
  presetId: preset.id,
  seed: preset.seed,
  colors: [...preset.colors],
  background: preset.background,
  shape: preset.shape,
  particleCount: preset.particleCount,
  minSize: preset.minSize,
  maxSize: preset.maxSize,
  blur: preset.blur,
  opacity: preset.opacity,
  speed: preset.speed,
  intensity: preset.intensity,
  glow: preset.glow,
  blendMode: preset.blendMode,
  borderRadius: preset.borderRadius,
  gradientStyle: preset.gradientStyle,
  isPaused: false,
  showContent: true,
  previewMode: "hero",
});
