import type { TipPreset, TipScenarioInput } from "./types";

function guests(count: number) {
  return Array.from({ length: count }, (_, index) => ({
    id: `guest-${index + 1}`,
    name: `Guest ${index + 1}`,
    weight: 1,
  }));
}

export const DEFAULT_TIP_INPUT: TipScenarioInput = {
  subtotal: 86.4,
  taxPercent: 8.25,
  servicePercent: 0,
  tipPercent: 18,
  people: 3,
  currency: "USD",
  tipBasis: "subtotal-tax",
  roundMode: "fair",
  splitMode: "equal",
  guests: guests(3),
};

export const DEFAULT_TIP_PRESET_ID = "casual-dinner";

export const TIP_PRESETS: TipPreset[] = [
  {
    id: "casual-dinner",
    name: "Casual dinner",
    description: "Three people, local sales tax, and an 18% tip after tax.",
    input: { ...DEFAULT_TIP_INPUT, guests: guests(3) },
  },
  {
    id: "large-group",
    name: "Large group",
    description: "Eight guests with a restaurant service charge already included.",
    input: {
      subtotal: 420,
      taxPercent: 9,
      servicePercent: 20,
      tipPercent: 0,
      people: 8,
      currency: "USD",
      tipBasis: "subtotal",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(8),
    },
  },
  {
    id: "weighted-family",
    name: "Weighted family split",
    description: "Two adults and two children using weighted shares.",
    input: {
      subtotal: 145,
      taxPercent: 7.5,
      servicePercent: 0,
      tipPercent: 18,
      people: 4,
      currency: "USD",
      tipBasis: "subtotal-tax",
      roundMode: "fair",
      splitMode: "weighted",
      guests: [
        { id: "adult-1", name: "Adult 1", weight: 1 },
        { id: "adult-2", name: "Adult 2", weight: 1 },
        { id: "child-1", name: "Child 1", weight: 0.5 },
        { id: "child-2", name: "Child 2", weight: 0.5 },
      ],
    },
  },
  {
    id: "cafe-no-tax",
    name: "Quick cafe",
    description: "A simple two-person cafe bill with no entered tax or service fee.",
    input: {
      subtotal: 27.8,
      taxPercent: 0,
      servicePercent: 0,
      tipPercent: 15,
      people: 2,
      currency: "EUR",
      tipBasis: "subtotal",
      roundMode: "up-050",
      splitMode: "equal",
      guests: guests(2),
    },
  },
  {
    id: "shekel-takeaway",
    name: "Takeaway order",
    description: "Four-way ILS split with a small service fee and no extra tip.",
    input: {
      subtotal: 168,
      taxPercent: 0,
      servicePercent: 5,
      tipPercent: 0,
      people: 4,
      currency: "ILS",
      tipBasis: "subtotal",
      roundMode: "fair",
      splitMode: "equal",
      guests: guests(4),
    },
  },
  {
    id: "yen-group",
    name: "JPY group meal",
    description: "Zero-decimal currency example with five equal guests.",
    input: {
      subtotal: 12800,
      taxPercent: 10,
      servicePercent: 0,
      tipPercent: 0,
      people: 5,
      currency: "JPY",
      tipBasis: "subtotal",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(5),
    },
  },
  {
    id: "coffee-run",
    name: "Office coffee run",
    description: "One person pays for six drinks and needs each colleague's exact share.",
    input: {
      subtotal: 38.7,
      taxPercent: 6,
      servicePercent: 0,
      tipPercent: 10,
      people: 6,
      currency: "USD",
      tipBasis: "subtotal",
      roundMode: "up-050",
      splitMode: "equal",
      guests: guests(6),
    },
  },
  {
    id: "bar-tab",
    name: "Bar tab",
    description: "A rounded-up two-person tab with a generous tip on the pre-tax amount.",
    input: {
      subtotal: 64,
      taxPercent: 8,
      servicePercent: 0,
      tipPercent: 22,
      people: 2,
      currency: "USD",
      tipBasis: "subtotal",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(2),
    },
  },
  {
    id: "food-delivery",
    name: "Food delivery",
    description: "Delivery order with a service fee already applied and a driver tip on top.",
    input: {
      subtotal: 52.4,
      taxPercent: 7,
      servicePercent: 8,
      tipPercent: 12,
      people: 3,
      currency: "USD",
      tipBasis: "subtotal-tax",
      roundMode: "fair",
      splitMode: "equal",
      guests: guests(3),
    },
  },
  {
    id: "birthday-dinner",
    name: "Birthday dinner",
    description: "Six diners, but the person celebrating is not charged, so five people split the full bill.",
    input: {
      subtotal: 312,
      taxPercent: 8.5,
      servicePercent: 0,
      tipPercent: 20,
      people: 5,
      currency: "USD",
      tipBasis: "subtotal-tax",
      roundMode: "fair",
      splitMode: "equal",
      guests: guests(5),
    },
  },
  {
    id: "business-lunch",
    name: "Business lunch",
    description: "A single-payer receipt for an expense claim, using fair rounding and full tax basis.",
    input: {
      subtotal: 118.25,
      taxPercent: 8.875,
      servicePercent: 0,
      tipPercent: 18,
      people: 1,
      currency: "USD",
      tipBasis: "subtotal-tax",
      roundMode: "fair",
      splitMode: "equal",
      guests: guests(1),
    },
  },
  {
    id: "uk-service-charge",
    name: "UK discretionary service",
    description: "A GBP bill with a 12.5% service charge already added and no extra tip.",
    input: {
      subtotal: 96.5,
      taxPercent: 0,
      servicePercent: 12.5,
      tipPercent: 0,
      people: 4,
      currency: "GBP",
      tipBasis: "subtotal",
      roundMode: "fair",
      splitMode: "equal",
      guests: guests(4),
    },
  },
  {
    id: "hotel-breakfast",
    name: "Hotel breakfast",
    description: "A EUR bill split three ways with a modest rounded-up tip.",
    input: {
      subtotal: 47.4,
      taxPercent: 10,
      servicePercent: 0,
      tipPercent: 8,
      people: 3,
      currency: "EUR",
      tipBasis: "subtotal-tax",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(3),
    },
  },
  {
    id: "uneven-orders",
    name: "Uneven orders",
    description: "Four diners with clearly different order sizes, split by weight rather than evenly.",
    input: {
      subtotal: 184,
      taxPercent: 8,
      servicePercent: 0,
      tipPercent: 18,
      people: 4,
      currency: "USD",
      tipBasis: "subtotal-tax",
      roundMode: "fair",
      splitMode: "weighted",
      guests: [
        { id: "big-1", name: "Full meal", weight: 2 },
        { id: "big-2", name: "Full meal", weight: 2 },
        { id: "small-1", name: "Starter only", weight: 1 },
        { id: "small-2", name: "Drinks only", weight: 0.5 },
      ],
    },
  },
  {
    id: "salon-visit",
    name: "Salon or barber",
    description: "A single-service appointment with a standard 20% tip on the service price.",
    input: {
      subtotal: 75,
      taxPercent: 0,
      servicePercent: 0,
      tipPercent: 20,
      people: 1,
      currency: "USD",
      tipBasis: "subtotal",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(1),
    },
  },
  {
    id: "no-tip-region",
    name: "No-tipping region",
    description: "A tax-inclusive bill where tipping is not customary, split evenly.",
    input: {
      subtotal: 9600,
      taxPercent: 0,
      servicePercent: 0,
      tipPercent: 0,
      people: 4,
      currency: "JPY",
      tipBasis: "subtotal",
      roundMode: "fair",
      splitMode: "equal",
      guests: guests(4),
    },
  },
  {
    id: "catering-order",
    name: "Team catering order",
    description: "A large office order split across ten people with a service fee and small tip.",
    input: {
      subtotal: 640,
      taxPercent: 8.25,
      servicePercent: 5,
      tipPercent: 10,
      people: 10,
      currency: "USD",
      tipBasis: "subtotal",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(10),
    },
  },
  {
    id: "shared-taxi",
    name: "Shared taxi",
    description: "A short ride split three ways with the fare rounded up to a whole unit.",
    input: {
      subtotal: 28,
      taxPercent: 0,
      servicePercent: 0,
      tipPercent: 10,
      people: 3,
      currency: "ILS",
      tipBasis: "subtotal",
      roundMode: "up-whole",
      splitMode: "equal",
      guests: guests(3),
    },
  },
];
