import type { FakeScreenPreset, FakeScreenState } from "./types";

export const DEFAULT_FAKE_SCREEN_STATE: FakeScreenState = {
  mode: "update",
  color: "#ffffff",
  colorMode: "solid",
  brightness: 100,
  timerMinutes: 2,
  deadPixelIndex: 0,
  updateTemplate: "win11",
  updateDurationMinutes: 10,
  updateStartPercent: 7,
  updateProgressMode: "realistic",
  updateTitle: "Working on updates",
  updateSubtitle: "Keep this screen open. This is a safe Darma visual simulation.",
  updateCompletionText: "Update complete",
  manualProgress: 42,
  errorTemplate: "blue-modern",
  errorTitle: "Your device ran into a problem and needs to restart.",
  errorMessage: "We're just collecting some error info, and then we'll restart for this harmless Darma demo.",
  errorStopCode: "DARMA_SCREEN_TEST",
  errorProgress: 65,
  screensaverTemplate: "dvd",
  screensaverText: "DVD",
  screensaverSpeed: "medium",
  screensaverSize: 64,
  screensaverBackground: "#000000",
  screensaverColor: "#ff1f1f",
  showCornerCounter: true,
  canvasTemplate: "interactive-circles",
  canvasDensity: 650,
  canvasSpeed: "medium",
  canvasPrimaryColor: "#369bcc",
  canvasBackground: "#020617",
};

export const MODE_LABELS: Record<FakeScreenState["mode"], string> = {
  color: "Color screens",
  update: "Fake updates",
  error: "Prank/error screens",
  screensaver: "Screensavers",
  canvas: "Canvas backgrounds",
};

export const FAKE_SCREEN_PRESETS: FakeScreenPreset[] = [
  { id: "white-screen", title: "White Screen", description: "Bright fullscreen white for cleaning, light, and display checks.", mode: "color", previewClassName: "bg-white", state: { mode: "color", color: "#ffffff", colorMode: "solid", brightness: 100 } },
  { id: "black-screen", title: "Black Screen", description: "Dark fullscreen black for contrast checks and ambient scenes.", mode: "color", previewClassName: "bg-black", state: { mode: "color", color: "#000000", colorMode: "solid", brightness: 100 } },
  { id: "red-screen", title: "Red Screen", description: "Solid red screen for RGB display testing.", mode: "color", previewClassName: "bg-red-500", state: { mode: "color", color: "#ef4444", colorMode: "solid", brightness: 100 } },
  { id: "green-screen", title: "Green Screen", description: "Solid green screen for RGB display testing.", mode: "color", previewClassName: "bg-green-500", state: { mode: "color", color: "#22c55e", colorMode: "solid", brightness: 100 } },
  { id: "blue-screen", title: "Blue Screen", description: "Solid blue screen for RGB display testing.", mode: "color", previewClassName: "bg-blue-600", state: { mode: "color", color: "#2563eb", colorMode: "solid", brightness: 100 } },
  { id: "dead-pixel-test", title: "Dead Pixel Test", description: "Cycles white, black, red, green, and blue fixed test screens.", mode: "color", previewClassName: "bg-gradient-to-r from-white via-red-500 to-blue-600", state: { mode: "color", colorMode: "dead-pixel", deadPixelIndex: 0, brightness: 100 } },
  { id: "screen-cleaner", title: "Screen Cleaner", description: "Bright clean screen with an optional timer before wiping gently.", mode: "color", previewClassName: "bg-gradient-to-br from-white to-sky-100", state: { mode: "color", color: "#ffffff", colorMode: "cleaning", timerMinutes: 2, brightness: 100 } },
  { id: "soft-light", title: "Soft Warm Light", description: "Warm light source for reading, filming, or ambience.", mode: "color", previewClassName: "bg-orange-200", state: { mode: "color", color: "#ffd7a8", colorMode: "soft-light", brightness: 75 } },

  { id: "update-win11", title: "Windows 11", description: "Modern centered update screen with spinning dots.", mode: "update", previewClassName: "bg-slate-950", state: { mode: "update", updateTemplate: "win11", updateProgressMode: "realistic", updateStartPercent: 15, updateTitle: "Updates are underway", updateSubtitle: "Please keep your device on." } },
  { id: "update-win10", title: "Windows 10", description: "Blue centered update screen with spinner and percentage.", mode: "update", previewClassName: "bg-[#0078d7]", state: { mode: "update", updateTemplate: "win10", updateProgressMode: "realistic", updateStartPercent: 7, updateDurationMinutes: 10, updateTitle: "Working on updates", updateSubtitle: "Don't turn off your PC. This will take a while." } },
  { id: "update-winxp", title: "Windows XP", description: "Retro blue setup-like screen with top and bottom bands.", mode: "update", previewClassName: "bg-blue-500", state: { mode: "update", updateTemplate: "winxp", updateProgressMode: "realistic", updateStartPercent: 7, updateDurationMinutes: 8, updateTitle: "Installing updates", updateSubtitle: "Do not turn off or unplug your computer." } },
  { id: "update-mac", title: "Mac OS X", description: "Minimal dark update screen with centered mark and progress bar.", mode: "update", previewClassName: "bg-black", state: { mode: "update", updateTemplate: "mac", updateProgressMode: "linear", updateStartPercent: 12, updateTitle: "Installing update", updateSubtitle: "Your screen may restart during this harmless demo." } },
  { id: "update-ubuntu", title: "Ubuntu 22.04", description: "Purple update style with orange progress detail.", mode: "update", previewClassName: "bg-purple-950", state: { mode: "update", updateTemplate: "ubuntu", updateProgressMode: "linear", updateStartPercent: 24, updateTitle: "Installing system updates", updateSubtitle: "Preparing packages and visual components." } },
  { id: "update-chrome", title: "Chrome OS", description: "Dark recovery/update style with clean progress text.", mode: "update", previewClassName: "bg-neutral-900", state: { mode: "update", updateTemplate: "chrome", updateProgressMode: "stuck-99", updateStartPercent: 72, updateTitle: "Applying update", updateSubtitle: "This may take a few minutes." } },
  { id: "update-android", title: "Android", description: "Mobile-inspired installing screen with robot-like icon.", mode: "update", previewClassName: "bg-green-500", state: { mode: "update", updateTemplate: "android", updateProgressMode: "loop", updateStartPercent: 4, updateTitle: "Installing system update", updateSubtitle: "Optimizing visual apps." } },
  { id: "update-terminal", title: "Terminal Update", description: "Developer terminal progress for demos and streams.", mode: "update", previewClassName: "bg-black", state: { mode: "update", updateTemplate: "terminal", updateProgressMode: "loop", updateTitle: "Running package updates", updateSubtitle: "Resolving visual dependencies..." } },

  { id: "error-blue-modern", title: "Modern Blue Error", description: "Large sad-face error screen with progress and stop code.", mode: "error", previewClassName: "bg-sky-600", state: { mode: "error", errorTemplate: "blue-modern", errorProgress: 65 } },
  { id: "error-blue-classic", title: "Classic Blue Error", description: "Text-heavy retro blue error screen for old-school scenes.", mode: "error", previewClassName: "bg-blue-800", state: { mode: "error", errorTemplate: "blue-classic", errorTitle: "A problem has been detected and the system has been stopped.", errorProgress: 0, errorStopCode: "DEMO_SCREEN_HALTED" } },
  { id: "error-developer", title: "Developer Panic", description: "Terminal-style crash with logs and fake stack output.", mode: "error", previewClassName: "bg-slate-950", state: { mode: "error", errorTemplate: "developer", errorTitle: "Unhandled promise rejection in demo mode", errorStopCode: "SHIP_IT_ANYWAY", errorProgress: 99 } },
  { id: "error-kernel", title: "Kernel Panic", description: "Dense dark crash text for technical visual scenes.", mode: "error", previewClassName: "bg-neutral-950", state: { mode: "error", errorTemplate: "kernel", errorTitle: "panic(cpu 0 caller 0xffffff): Darma visual kernel demo", errorStopCode: "VISUAL_KERNEL_TEST", errorProgress: 0 } },
  { id: "error-no-signal", title: "No Signal", description: "TV color bars with a centered no-signal card.", mode: "error", previewClassName: "bg-gradient-to-r from-yellow-400 via-fuchsia-500 to-blue-600", state: { mode: "error", errorTemplate: "no-signal", errorTitle: "NO SIGNAL", errorMessage: "Check input source or press Esc to exit fullscreen." } },
  { id: "error-radar", title: "Radar Screen", description: "Green radar sweep style for playful prank scenes.", mode: "error", previewClassName: "bg-emerald-950", state: { mode: "error", errorTemplate: "radar", errorTitle: "Scanning visual area", errorMessage: "Target lock is simulated for entertainment only." } },
  { id: "error-broken", title: "Broken Screen", description: "Cracked-glass inspired visual without real damage.", mode: "error", previewClassName: "bg-zinc-900", state: { mode: "error", errorTemplate: "broken", errorTitle: "Display fracture simulation", errorMessage: "This is only a visual overlay. Your device is not damaged." } },
  { id: "error-hacker", title: "Hacker Typer", description: "Green code wall for movie-style demos.", mode: "error", previewClassName: "bg-black", state: { mode: "error", errorTemplate: "hacker", errorTitle: "ACCESSING DARMA VISUAL MODE", errorMessage: "Generating harmless terminal-looking output." } },

  { id: "saver-dvd", title: "DVD Bounce", description: "Classic bouncing logo-style screensaver with DVD text.", mode: "screensaver", previewClassName: "bg-black", state: { mode: "screensaver", screensaverTemplate: "dvd", screensaverText: "DVD", screensaverSpeed: "medium", screensaverBackground: "#000000", screensaverColor: "#ff1f1f", screensaverSize: 64 } },
  { id: "saver-flip-clock", title: "Flip Clock", description: "Large minimal clock-style screen for desks and ambient displays.", mode: "screensaver", previewClassName: "bg-white", state: { mode: "screensaver", screensaverTemplate: "flip-clock", screensaverBackground: "#f8fafc", screensaverColor: "#111827", screensaverSize: 56 } },
  { id: "saver-quote", title: "Quotes", description: "Centered quote card that can become a clean fullscreen scene.", mode: "screensaver", previewClassName: "bg-stone-100", state: { mode: "screensaver", screensaverTemplate: "quote", screensaverText: "The best way to predict the future is to create it.", screensaverBackground: "#f5f5f4", screensaverColor: "#1c1917" } },
  { id: "saver-no-signal", title: "No Signal Bars", description: "TV test bars screensaver with a simple label.", mode: "screensaver", previewClassName: "bg-gradient-to-r from-yellow-300 via-green-400 to-blue-600", state: { mode: "screensaver", screensaverTemplate: "no-signal", screensaverText: "NO SIGNAL", screensaverBackground: "#111827", screensaverColor: "#ffffff" } },
  { id: "saver-matrix", title: "Matrix Rain", description: "Falling green symbols inspired by terminal rain visuals.", mode: "screensaver", previewClassName: "bg-black", state: { mode: "screensaver", screensaverTemplate: "matrix", screensaverText: "DARMA", screensaverBackground: "#000000", screensaverColor: "#22c55e" } },
  { id: "saver-floating", title: "Floating Text", description: "Custom bouncing words for classrooms, demos, and streams.", mode: "screensaver", previewClassName: "bg-indigo-950", state: { mode: "screensaver", screensaverTemplate: "floating-text", screensaverText: "HELLO", screensaverSpeed: "slow", screensaverBackground: "#1e1b4b", screensaverColor: "#c4b5fd" } },

  { id: "canvas-circles", title: "Interactive Circles", description: "Colorful circles react to the mouse and expand on hover.", mode: "canvas", previewClassName: "bg-gradient-to-br from-rose-600 via-sky-500 to-slate-900", state: { mode: "canvas", canvasTemplate: "interactive-circles", canvasDensity: 900, canvasSpeed: "medium", canvasPrimaryColor: "#369bcc", canvasBackground: "#020617" } },
  { id: "canvas-starfield", title: "Starfield", description: "Fast moving stars for space, sci-fi, and loading backgrounds.", mode: "canvas", previewClassName: "bg-black", state: { mode: "canvas", canvasTemplate: "starfield", canvasDensity: 500, canvasSpeed: "fast", canvasPrimaryColor: "#ffffff", canvasBackground: "#000000" } },
  { id: "canvas-network", title: "Particle Network", description: "Connected particles that drift and draw soft linking lines.", mode: "canvas", previewClassName: "bg-slate-950", state: { mode: "canvas", canvasTemplate: "network", canvasDensity: 180, canvasSpeed: "medium", canvasPrimaryColor: "#7dd3fc", canvasBackground: "#020617" } },
  { id: "canvas-waves", title: "Wave Lines", description: "Animated layered sine waves for calm visual backgrounds.", mode: "canvas", previewClassName: "bg-blue-950", state: { mode: "canvas", canvasTemplate: "waves", canvasDensity: 12, canvasSpeed: "slow", canvasPrimaryColor: "#38bdf8", canvasBackground: "#082f49" } },
  { id: "canvas-aurora", title: "Aurora Glow", description: "Soft glowing gradients moving across a dark canvas.", mode: "canvas", previewClassName: "bg-gradient-to-br from-emerald-400 via-purple-500 to-slate-950", state: { mode: "canvas", canvasTemplate: "aurora", canvasDensity: 60, canvasSpeed: "slow", canvasPrimaryColor: "#a78bfa", canvasBackground: "#020617" } },
  { id: "canvas-fireflies", title: "Fireflies", description: "Tiny warm lights drifting in a dark night scene.", mode: "canvas", previewClassName: "bg-stone-950", state: { mode: "canvas", canvasTemplate: "fireflies", canvasDensity: 140, canvasSpeed: "medium", canvasPrimaryColor: "#fde68a", canvasBackground: "#0c0a09" } },
  { id: "canvas-bubbles", title: "Bubbles", description: "Floating bubbles for playful screens and classroom visuals.", mode: "canvas", previewClassName: "bg-cyan-700", state: { mode: "canvas", canvasTemplate: "bubbles", canvasDensity: 120, canvasSpeed: "slow", canvasPrimaryColor: "#cffafe", canvasBackground: "#0e7490" } },
  { id: "canvas-snow", title: "Snowfall", description: "Gentle falling snow on a winter background.", mode: "canvas", previewClassName: "bg-slate-800", state: { mode: "canvas", canvasTemplate: "snow", canvasDensity: 260, canvasSpeed: "slow", canvasPrimaryColor: "#ffffff", canvasBackground: "#1e293b" } },
  { id: "canvas-plasma", title: "Plasma Field", description: "Color waves that move like a retro plasma screen.", mode: "canvas", previewClassName: "bg-gradient-to-r from-fuchsia-500 via-blue-500 to-emerald-400", state: { mode: "canvas", canvasTemplate: "plasma", canvasDensity: 80, canvasSpeed: "medium", canvasPrimaryColor: "#f472b6", canvasBackground: "#020617" } },
  { id: "canvas-confetti", title: "Confetti", description: "Colorful falling pieces for celebrations and streams.", mode: "canvas", previewClassName: "bg-white", state: { mode: "canvas", canvasTemplate: "confetti", canvasDensity: 220, canvasSpeed: "medium", canvasPrimaryColor: "#f97316", canvasBackground: "#f8fafc" } },
];
