import type { UnitPreset } from "./types";

export const UNIT_PRESETS: UnitPreset[] = [
  {
    id: "room-length",
    name: "Room length",
    description: "Convert a 3.5 meter room dimension to feet.",
    categoryId: "length",
    fromId: "m",
    toId: "ft",
    value: 3.5,
    batchInput: "2.4\n3.5\n4.8",
  },
  {
    id: "road-distance",
    name: "Road distance",
    description: "Convert a 10 kilometer trip to miles.",
    categoryId: "length",
    fromId: "km",
    toId: "mi",
    value: 10,
    batchInput: "5 km\n10 km\n42.195 km",
  },
  {
    id: "body-weight",
    name: "Body weight",
    description: "Convert 72 kilograms to pounds.",
    categoryId: "mass",
    fromId: "kg",
    toId: "lb",
    value: 72,
    batchInput: "55\n72\n90",
  },
  {
    id: "oven-temperature",
    name: "Oven temperature",
    description: "Convert 180 °C to Fahrenheit for a recipe.",
    categoryId: "temperature",
    fromId: "c",
    toId: "f",
    value: 180,
    batchInput: "160 C\n180 C\n200 C",
  },
  {
    id: "recipe-volume",
    name: "Recipe volume",
    description: "Convert two US cups to milliliters.",
    categoryId: "volume",
    fromId: "cup",
    toId: "ml",
    value: 2,
    batchInput: "0.5 cup\n1 cup\n2 cup",
  },
  {
    id: "storage-capacity",
    name: "Storage capacity",
    description: "Compare 500 decimal megabytes with binary mebibytes.",
    categoryId: "digital",
    fromId: "MB",
    toId: "MiB",
    value: 500,
    batchInput: "128 MB\n500 MB\n1024 MB",
  },
];
