import type { UnitPreset } from "./types";

export const UNIT_PRESETS: UnitPreset[] = [
  {
    id: "room-length",
    name: "Room length",
    description: "Convert a 3.5 meter room dimension to feet.",
    categoryId: "length",
    fromId: "m",
    toId: "ft",
    value: 3.5,
    batchInput: "2.4\n3.5\n4.8",
  },
  {
    id: "road-distance",
    name: "Road distance",
    description: "Convert a 10 kilometer trip to miles.",
    categoryId: "length",
    fromId: "km",
    toId: "mi",
    value: 10,
    batchInput: "5 km\n10 km\n42.195 km",
  },
  {
    id: "body-weight",
    name: "Body weight",
    description: "Convert 72 kilograms to pounds.",
    categoryId: "mass",
    fromId: "kg",
    toId: "lb",
    value: 72,
    batchInput: "55\n72\n90",
  },
  {
    id: "oven-temperature",
    name: "Oven temperature",
    description: "Convert 180 °C to Fahrenheit for a recipe.",
    categoryId: "temperature",
    fromId: "c",
    toId: "f",
    value: 180,
    batchInput: "160 C\n180 C\n200 C",
  },
  {
    id: "recipe-volume",
    name: "Recipe volume",
    description: "Convert two US cups to milliliters.",
    categoryId: "volume",
    fromId: "cup",
    toId: "ml",
    value: 2,
    batchInput: "0.5 cup\n1 cup\n2 cup",
  },
  {
    id: "storage-capacity",
    name: "Storage capacity",
    description: "Compare 500 decimal megabytes with binary mebibytes.",
    categoryId: "digital",
    fromId: "MB",
    toId: "MiB",
    value: 500,
    batchInput: "128 MB\n500 MB\n1024 MB",
  },
  {
    id: "screen-size",
    name: "Screen size",
    description: "Convert a 27 inch monitor diagonal to centimeters.",
    categoryId: "length",
    fromId: "in",
    toId: "cm",
    value: 27,
    batchInput: "13.3 in\n15.6 in\n27 in\n32 in",
  },
  {
    id: "marathon-distance",
    name: "Marathon distance",
    description: "Convert the official 42.195 kilometer marathon to miles.",
    categoryId: "length",
    fromId: "km",
    toId: "mi",
    value: 42.195,
  },
  {
    id: "parcel-weight",
    name: "Parcel weight",
    description: "Convert a 2.5 kilogram parcel to ounces.",
    categoryId: "mass",
    fromId: "kg",
    toId: "oz",
    value: 2.5,
  },
  {
    id: "coffee-water",
    name: "Coffee water",
    description: "Convert 750 milliliters to US fluid ounces.",
    categoryId: "volume",
    fromId: "ml",
    toId: "floz",
    value: 750,
  },
  {
    id: "freezer-temperature",
    name: "Freezer temperature",
    description: "Convert −18 °C, a common freezer setting, to Fahrenheit.",
    categoryId: "temperature",
    fromId: "c",
    toId: "f",
    value: -18,
  },
  {
    id: "file-size",
    name: "Large file size",
    description: "Convert 4 GiB to decimal GB for storage and upload limits.",
    categoryId: "digital",
    fromId: "GiB",
    toId: "GB",
    value: 4,
  },
  {
    id: "memory-capacity",
    name: "RAM capacity",
    description: "Convert 16384 MiB to GiB.",
    categoryId: "digital",
    fromId: "MiB",
    toId: "GiB",
    value: 16384,
  },
  {
    id: "small-distance",
    name: "UI measurement",
    description: "Convert 24 millimeters to inches for physical mockups.",
    categoryId: "length",
    fromId: "mm",
    toId: "in",
    value: 24,
  },
  {
    id: "shipping-mass",
    name: "Shipping mass",
    description: "Convert 35 pounds to kilograms for international shipping.",
    categoryId: "mass",
    fromId: "lb",
    toId: "kg",
    value: 35,
  },
  {
    id: "recipe-spoons",
    name: "Recipe spoons",
    description: "Convert three tablespoons to milliliters.",
    categoryId: "volume",
    fromId: "tbsp",
    toId: "ml",
    value: 3,
  },
  {
    id: "weather-temperature",
    name: "Weather temperature",
    description: "Convert 86 °F to Celsius.",
    categoryId: "temperature",
    fromId: "f",
    toId: "c",
    value: 86,
  },
  {
    id: "download-size",
    name: "Download size",
    description: "Convert 850 MB to MiB to compare decimal and binary tooling.",
    categoryId: "digital",
    fromId: "MB",
    toId: "MiB",
    value: 850,
  },
  {
    id: "portrait-height",
    name: "Person height",
    description: "Convert 178 centimeters to feet.",
    categoryId: "length",
    fromId: "cm",
    toId: "ft",
    value: 178,
  },
  {
    id: "kitchen-flour",
    name: "Kitchen mass",
    description: "Convert 500 grams to ounces.",
    categoryId: "mass",
    fromId: "g",
    toId: "oz",
    value: 500,
  },

];
