import { InMemoryToolRegistry } from "../infra/inMemory/toolRegistry.memory";
import type { ToolRegistry } from "../domain/toolRegistry";
import type { ToolDefinition } from "../domain/tool";

const TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    id: "animated-background-generator",
    title: "Animated Background Generator",
    description: "Generate animated CSS backgrounds and copy the code.",
    href: "/tools/animated-background-generator",
    icon: "film",
    status: "ready",
    completion: 100,
    tags: ["css", "animation", "background"],
    mainCategory: ["tools"],
    secondaryCategory: ["css"],
    audiences: ["developer", "designer"],
    featured: true,
    visibility: "public",
  },
  {
    id: "box-shadows-generator",
    title: "Box Shadows Generator",
    description: "Build multi-layer box-shadows visually and copy CSS.",
    href: "/tools/box-shadows-generator",
    icon: "cube",
    status: "ready",
    completion: 100,
    tags: ["css", "shadow", "ui"],
    mainCategory: ["tools"],
    secondaryCategory: ["css"],
    audiences: ["developer", "designer"],
    featured: true,
    visibility: "public",
  },
  {
    id: "code-preview-tool",
    title: "Code Preview Tool",
    description: "Preview HTML, CSS, and JS in a sandboxed iframe.",
    href: "/tools/code-preview-tool",
    icon: "code",
    status: "ready",
    completion: 100,
    tags: ["html", "css", "javascript", "preview"],
    mainCategory: ["tools"],
    secondaryCategory: ["devtools"],
    audiences: ["developer", "student"],
    featured: true,
    visibility: "public",
  },
  {
    id: "buttons-css-generator",
    title: "Buttons CSS Generator",
    description: "Generate modern button styles and copy CSS.",
    href: "/tools/buttons-css-generator",
    icon: "magic",
    status: "ready",
    completion: 100,
    tags: ["css", "buttons", "ui"],
    mainCategory: ["tools"],
    secondaryCategory: ["css"],
    audiences: ["developer", "designer"],
    visibility: "public",
  },
  {
    id: "qr-code",
    title: "QR Code Generator",
    description: "Generate QR codes quickly for URLs and text.",
    href: "/tools/qr-code",
    icon: "qrcode",
    status: "ready",
    completion: 100,
    tags: ["qr", "generator", "utility"],
    mainCategory: ["tools"],
    secondaryCategory: ["utilities"],
    audiences: ["general", "creator"],
    featured: true,
    visibility: "public",
  },
  {
    id: "neumorphic-css-generator",
    title: "Neumorphic CSS Generator",
    description: "Create neumorphic shadows and surfaces with CSS.",
    href: "/tools/neumorphic-css-generator",
    icon: "paint",
    status: "ready",
    completion: 100,
    tags: ["css", "neumorphism", "ui"],
    mainCategory: ["tools"],
    secondaryCategory: ["css"],
    audiences: ["developer", "designer"],
    visibility: "public",
  },
  {
    id: "color-shades",
    title: "Color Shades Generator",
    description: "Generate smooth color gradients with curated suggestions and dynamic backgrounds.",
    href: "/tools/color-shades",
    icon: "palette",
    status: "ready",
    completion: 100,
    tags: ["color", "palette", "gradient"],
    mainCategory: ["tools"],
    secondaryCategory: ["design"],
    audiences: ["designer", "creator"],
    visibility: "public",
  },
  {
    id: "password-generator",
    title: "Password Generator",
    description: "Generate strong, cryptographically random passwords and passphrases with a real-time strength meter.",
    href: "/tools/password-generator",
    icon: "magic",
    status: "ready",
    completion: 100,
    tags: ["password", "security", "generator", "passphrase", "random"],
    mainCategory: ["tools"],
    secondaryCategory: ["security", "utilities"],
    audiences: ["developer", "general", "creator"],
    featured: true,
    pinned: 2,
    visibility: "public",
  },
  {
    id: "lorem-ipsum-generator",
    title: "Lorem Ipsum Generator",
    description: "Generate classic lorem ipsum, readable placeholder text, and structured HTML blocks for mockups, wireframes, and UI prototyping.",
    href: "/tools/lorem-ipsum-generator",
    icon: "magic",
    status: "ready",
    completion: 100,
    tags: ["placeholder", "lorem ipsum", "content", "mockup", "ui", "text"],
    mainCategory: ["tools"],
    secondaryCategory: ["content", "utilities"],
    audiences: ["designer", "developer", "creator"],
    featured: true,
    pinned: 1,
    visibility: "public",
  },
  {
    id: "text-cleaner",
    title: "Text Cleaner & Case Converter",
    description: "Clean messy text and convert between case formats — remove extra spaces, fix line endings, deduplicate lines, sort, and switch between camelCase, snake_case, and more.",
    href: "/tools/text-cleaner",
    icon: "magic",
    status: "ready",
    completion: 100,
    tags: ["text", "cleaner", "case converter", "formatter", "camelCase", "snake_case", "utilities"],
    mainCategory: ["tools"],
    secondaryCategory: ["utilities", "devtools"],
    audiences: ["developer", "creator", "general"],
    featured: true,
    pinned: 3,
    visibility: "public",
  },
  {
    id: "json-formatter",
    title: "JSON Formatter & Validator",
    description: "Format, validate, and minify JSON instantly with clear error messages, line and column numbers, and one-click copy or download.",
    href: "/tools/json-formatter",
    icon: "code",
    status: "ready",
    completion: 100,
    tags: ["json", "formatter", "validator", "minify", "prettify", "developer", "api", "utilities"],
    mainCategory: ["tools"],
    secondaryCategory: ["devtools", "utilities"],
    audiences: ["developer", "student", "general"],
    featured: true,
    pinned: 4,
    visibility: "public",
  },
];

let registry: ToolRegistry | null = null;

export function getToolRegistry(): ToolRegistry {
  if (registry) return registry;
  registry = new InMemoryToolRegistry(TOOL_DEFINITIONS);
  return registry;
}
