import { InMemoryToolRegistry } from "../infra/inMemory/toolRegistry.memory";
import type { ToolRegistry } from "../domain/toolRegistry";
import type { ToolDefinition } from "../domain/tool";

const TOOL_DEFINITIONS: ToolDefinition[] = [
  { id: "beam-calculator", title: "Beam Calculator", description: "Canvas-first structural beam calculator with reactions, shear force, and bending moment diagrams for determinate beams.", href: "/tools/beam-calculator", icon: "cube", status: "ready", completion: 80, tags: ["beam", "calculator", "structural", "engineering", "shear", "moment"], mainCategory: ["tools"], secondaryCategory: ["engineering", "utilities", "visual"], audiences: ["student", "developer", "general"], featured: true, pinned: 6, visibility: "public", layoutType: "visual-generator" },
  { id: "animated-background-generator", title: "Animated Background Generator", description: "Generate animated CSS backgrounds and copy the code.", href: "/tools/animated-background-generator", icon: "film", status: "ready", completion: 100, tags: ["css", "animation", "background"], mainCategory: ["tools"], secondaryCategory: ["css", "visual"], audiences: ["developer", "designer"], featured: true, visibility: "public", layoutType: "visual-generator" },
  { id: "box-shadows-generator", title: "Box Shadows Generator", description: "Build multi-layer box-shadows visually and copy CSS.", href: "/tools/box-shadows-generator", icon: "cube", status: "ready", completion: 100, tags: ["css", "shadow", "ui"], mainCategory: ["tools"], secondaryCategory: ["css", "visual"], audiences: ["developer", "designer"], visibility: "public", layoutType: "visual-generator" },
  { id: "buttons-css-generator", title: "Buttons CSS Generator", description: "Generate modern button styles and copy CSS.", href: "/tools/buttons-css-generator", icon: "magic", status: "ready", completion: 100, tags: ["css", "buttons", "ui"], mainCategory: ["tools"], secondaryCategory: ["css", "visual"], audiences: ["developer", "designer"], visibility: "public", layoutType: "visual-generator" },
  { id: "code-preview-tool", title: "Code Preview Tool", description: "Preview HTML, CSS, and JS in a sandboxed iframe.", href: "/tools/code-preview-tool", icon: "code", status: "ready", completion: 100, tags: ["html", "css", "javascript", "preview"], mainCategory: ["tools"], secondaryCategory: ["devtools"], audiences: ["developer", "student"], visibility: "public", layoutType: "text-workbench" },
  { id: "color-converter", title: "Color Converter", description: "Convert colors between HEX, RGB, HSL, HSV, CMYK, and CSS-friendly formats.", href: "/tools/color-converter", icon: "palette", status: "ready", completion: 100, tags: ["color", "converter", "hex", "rgb", "hsl"], mainCategory: ["tools"], secondaryCategory: ["design", "utilities"], audiences: ["designer", "developer"], visibility: "public", layoutType: "visual-generator" },
  { id: "color-shades", title: "Color Shades Generator", description: "Generate smooth color gradients with curated suggestions and dynamic backgrounds.", href: "/tools/color-shades", icon: "palette", status: "ready", completion: 100, tags: ["color", "palette", "gradient"], mainCategory: ["tools"], secondaryCategory: ["design", "visual"], audiences: ["designer", "creator"], visibility: "public", layoutType: "visual-generator" },
  { id: "css-gradient-generator", title: "CSS Gradient Generator", description: "Design CSS gradients visually and copy production-ready CSS.", href: "/tools/css-gradient-generator", icon: "paint", status: "ready", completion: 100, tags: ["css", "gradient", "background", "color"], mainCategory: ["tools"], secondaryCategory: ["css", "design"], audiences: ["designer", "developer"], visibility: "public", layoutType: "visual-generator" },
  { id: "neumorphic-css-generator", title: "Neumorphic CSS Generator", description: "Create neumorphic shadows and surfaces with CSS.", href: "/tools/neumorphic-css-generator", icon: "paint", status: "ready", completion: 100, tags: ["css", "neumorphism", "ui"], mainCategory: ["tools"], secondaryCategory: ["css", "visual"], audiences: ["developer", "designer"], visibility: "public", layoutType: "visual-generator" },
  { id: "base64-encoder-decoder", title: "Base64 Encoder Decoder", description: "Encode and decode Base64 text locally in your browser.", href: "/tools/base64-encoder-decoder", icon: "code", status: "ready", completion: 100, tags: ["base64", "encoder", "decoder", "text"], mainCategory: ["tools"], secondaryCategory: ["devtools", "utilities"], audiences: ["developer", "general"], visibility: "public", layoutType: "text-workbench" },
  { id: "json-formatter", title: "JSON Formatter & Validator", description: "Format, validate, and minify JSON instantly with clear error messages, line and column numbers, and one-click copy or download.", href: "/tools/json-formatter", icon: "code", status: "ready", completion: 100, tags: ["json", "formatter", "validator", "minify", "prettify", "developer", "api", "utilities"], mainCategory: ["tools"], secondaryCategory: ["devtools", "utilities"], audiences: ["developer", "student", "general"], featured: true, pinned: 4, visibility: "public", layoutType: "text-workbench" },
  { id: "markdown-previewer", title: "Markdown Previewer", description: "Write Markdown and preview the rendered HTML side by side with copy-ready output.", href: "/tools/markdown-previewer", icon: "code", status: "ready", completion: 100, tags: ["Markdown", "HTML", "Preview", "Editor"], mainCategory: ["Development"], secondaryCategory: ["Text", "Converters"], audiences: ["developer", "creator", "student"], visibility: "public", privacy: "browser-only", layoutType: "text-workbench", keywords: ["markdown previewer", "markdown to html", "live markdown preview", "markdown editor", "readme preview"], relatedTools: ["code-preview-tool", "text-cleaner", "json-formatter", "html-entity-encoder-decoder"] },
  { id: "lorem-ipsum-generator", title: "Lorem Ipsum Generator", description: "Generate classic lorem ipsum, readable placeholder text, and structured HTML blocks for mockups, wireframes, and UI prototyping.", href: "/tools/lorem-ipsum-generator", icon: "magic", status: "ready", completion: 100, tags: ["placeholder", "lorem ipsum", "content", "mockup", "ui", "text"], mainCategory: ["tools"], secondaryCategory: ["content", "utilities"], audiences: ["designer", "developer", "creator"], featured: true, pinned: 1, visibility: "public", layoutType: "text-workbench" },
  { id: "slug-generator", title: "Slug Generator", description: "Turn titles and messy text into clean URL slugs.", href: "/tools/slug-generator", icon: "magic", status: "ready", completion: 100, tags: ["slug", "url", "text", "seo"], mainCategory: ["tools"], secondaryCategory: ["utilities", "content"], audiences: ["developer", "creator", "general"], visibility: "public", layoutType: "text-workbench" },
  { id: "text-cleaner", title: "Text Cleaner & Case Converter", description: "Clean messy text and convert between case formats: remove extra spaces, fix line endings, deduplicate lines, sort, and switch between camelCase, snake_case, and more.", href: "/tools/text-cleaner", icon: "magic", status: "ready", completion: 100, tags: ["text", "cleaner", "case converter", "formatter", "camelCase", "snake_case", "utilities"], mainCategory: ["tools"], secondaryCategory: ["utilities", "devtools"], audiences: ["developer", "creator", "general"], featured: true, pinned: 3, visibility: "public", layoutType: "text-workbench" },
  { id: "url-encoder-decoder", title: "URL Encoder Decoder", description: "Encode and decode URL strings, query values, and URI components.", href: "/tools/url-encoder-decoder", icon: "code", status: "ready", completion: 100, tags: ["url", "encoder", "decoder", "uri"], mainCategory: ["tools"], secondaryCategory: ["devtools", "utilities"], audiences: ["developer", "general"], visibility: "public", layoutType: "text-workbench" },
  { id: "uuid-generator", title: "UUID Generator", description: "Generate secure v4 UUIDs in your browser for test data, database IDs, mock APIs, and development workflows.", href: "/tools/uuid-generator", icon: "code", status: "ready", completion: 100, tags: ["UUID", "Generator", "Developer", "IDs"], mainCategory: ["Development"], secondaryCategory: ["Generators"], audiences: ["developer"], visibility: "public", privacy: "browser-only", layoutType: "single-utility", keywords: ["uuid generator", "guid generator", "v4 uuid", "random uuid", "secure uuid", "developer id generator"], relatedTools: ["password-generator", "slug-generator", "timestamp-converter", "json-formatter"] },
  { id: "password-generator", title: "Password Generator", description: "Generate strong, cryptographically random passwords and passphrases with a real-time strength meter.", href: "/tools/password-generator", icon: "magic", status: "ready", completion: 100, tags: ["password", "security", "generator", "passphrase", "random"], mainCategory: ["tools"], secondaryCategory: ["security", "utilities"], audiences: ["developer", "general", "creator"], featured: true, pinned: 2, visibility: "public", layoutType: "single-utility" },
  { id: "qr-code", title: "QR Code Generator", description: "Generate QR codes quickly for URLs and text.", href: "/tools/qr-code", icon: "qrcode", status: "ready", completion: 100, tags: ["qr", "generator", "utility"], mainCategory: ["tools"], secondaryCategory: ["utilities"], audiences: ["general", "creator"], featured: true, visibility: "public", layoutType: "single-utility" },
  { id: "timestamp-converter", title: "Timestamp Converter", description: "Convert Unix timestamps to readable dates and back.", href: "/tools/timestamp-converter", icon: "code", status: "ready", completion: 100, tags: ["timestamp", "date", "unix", "time"], mainCategory: ["tools"], secondaryCategory: ["devtools", "utilities"], audiences: ["developer", "general"], visibility: "public", layoutType: "single-utility" },
  { id: "svg-path-editor", title: "SVG Path Editor", description: "Edit, transform, optimize, preview, copy, and download SVG path data visually in your browser.", href: "/tools/svg-path-editor", icon: "code", status: "ready", completion: 100, tags: ["svg", "path", "editor", "vector", "developer", "designer"], mainCategory: ["tools"], secondaryCategory: ["devtools", "design", "visual"], audiences: ["developer", "designer", "student"], featured: true, visibility: "public", layoutType: "visual-generator" },
  { id: "fake-screen", title: "Fake Screen", description: "Create safe fullscreen color screens, fake update screens, blue error screens, DVD screensavers, and animated canvas backgrounds from one clean visual tool.", href: "/tools/fake-screen", icon: "film", status: "ready", completion: 100, tags: ["fake screen", "fullscreen", "color screen", "fake update", "blue screen", "screensaver", "canvas background", "visual"], mainCategory: ["tools"], secondaryCategory: ["screens", "visual", "utilities"], audiences: ["general", "creator", "student", "developer"], featured: true, pinned: 5, visibility: "public", layoutType: "fullscreen-studio" },
];

let registry: ToolRegistry | null = null;

export function getToolRegistry(): ToolRegistry {
  if (registry) return registry;
  registry = new InMemoryToolRegistry(TOOL_DEFINITIONS);
  return registry;
}
