import type { Preset } from "./types";

export const DESIGN_PRESETS: Preset[] = [
  {
    id: "hero-section",
    label: "Hero section",
    icon: "🏔",
    description: "Landing-page headline, supporting copy, and CTA labels.",
    config: { mode: "structured", structuredBlock: "hero", outputFormat: "html", amount: 1, seed: "hero-launch" },
  },
  {
    id: "feature-cards",
    label: "Feature cards",
    icon: "🃏",
    description: "Three concise feature cards for a product grid.",
    config: { mode: "structured", structuredBlock: "card", outputFormat: "html", amount: 3, seed: "feature-grid" },
  },
  {
    id: "testimonials",
    label: "Testimonials",
    icon: "💬",
    description: "Social-proof quotes with names and roles.",
    config: { mode: "structured", structuredBlock: "testimonial", outputFormat: "html", amount: 3, seed: "customer-proof" },
  },
  {
    id: "faq-block",
    label: "FAQ",
    icon: "❓",
    description: "Question-and-answer content for accordion layouts.",
    config: { mode: "structured", structuredBlock: "faq", outputFormat: "html", amount: 4, seed: "faq-content" },
  },
  {
    id: "product-listing",
    label: "Product listing",
    icon: "🛍",
    description: "Product names, prices, descriptions, and features.",
    config: { mode: "structured", structuredBlock: "product", outputFormat: "html", amount: 2, seed: "catalog-cards" },
  },
  {
    id: "about-bio",
    label: "About / Bio",
    icon: "👤",
    description: "Profile and about-page copy in readable prose.",
    config: { mode: "structured", structuredBlock: "about", outputFormat: "plain", amount: 1, seed: "profile-bio" },
  },
  {
    id: "onboarding-steps",
    label: "Onboarding steps",
    icon: "🪜",
    description: "Ordered product setup steps for onboarding screens.",
    config: { mode: "structured", structuredBlock: "onboarding", outputFormat: "html", amount: 4, seed: "onboarding-flow" },
  },
  {
    id: "pricing-table",
    label: "Pricing table",
    icon: "💳",
    description: "Tier names, pricing, benefits, and CTA labels.",
    config: { mode: "structured", structuredBlock: "pricing", outputFormat: "html", amount: 3, seed: "pricing-tiers" },
  },
  { id: "saas-hero", label: "SaaS hero", icon: "🚀", description: "Product-led hero copy with a concise value proposition and CTA pair.", config: { mode: "structured", structuredBlock: "hero", style: "startup", outputFormat: "html", amount: 1, seed: "saas-hero" } },
  { id: "mobile-hero", label: "Mobile hero", icon: "📱", description: "Shorter hero copy for narrow mobile layouts and app landing pages.", config: { mode: "structured", structuredBlock: "hero", style: "readable", outputFormat: "html", amount: 1, blockLength: "short", seed: "mobile-hero" } },
  { id: "dashboard-cards", label: "Dashboard cards", icon: "📊", description: "Compact card copy for dashboard widgets and overview grids.", config: { mode: "structured", structuredBlock: "card", style: "startup", outputFormat: "html", amount: 4, seed: "dashboard-cards" } },
  { id: "review-quotes", label: "Review quotes", icon: "⭐", description: "Short testimonial content for ratings, carousels, and proof sections.", config: { mode: "structured", structuredBlock: "testimonial", style: "ecommerce", outputFormat: "html", amount: 4, seed: "review-quotes" } },
  { id: "support-faq", label: "Support FAQ", icon: "🛟", description: "Straightforward help-center questions and answers for support layouts.", config: { mode: "structured", structuredBlock: "faq", style: "readable", outputFormat: "html", amount: 6, seed: "support-faq" } },
  { id: "product-cards", label: "Product cards", icon: "🛒", description: "Denser product-card content for an e-commerce results grid.", config: { mode: "structured", structuredBlock: "product", style: "ecommerce", outputFormat: "html", amount: 4, seed: "product-grid" } },
  { id: "team-profile", label: "Team profile", icon: "🧑‍💻", description: "Professional profile copy for team directories and contributor pages.", config: { mode: "structured", structuredBlock: "about", style: "profile", outputFormat: "plain", amount: 1, seed: "team-profile" } },
  { id: "pricing-comparison", label: "Pricing comparison", icon: "⚖️", description: "Three pricing tiers with enough copy to test feature density and CTA alignment.", config: { mode: "structured", structuredBlock: "pricing", style: "startup", outputFormat: "html", amount: 3, seed: "pricing-comparison" } },
];

export const LENGTH_PRESETS: Preset[] = [
  {
    id: "snippet",
    label: "Snippet",
    icon: "·",
    description: "Two short sentences for compact components.",
    config: { mode: "sentences", amount: 2, blockLength: "short", seed: "short-snippet" },
  },
  {
    id: "short",
    label: "Short",
    icon: "·",
    description: "One short paragraph for cards and empty states.",
    config: { mode: "paragraphs", amount: 1, blockLength: "short", seed: "short-paragraph" },
  },
  {
    id: "medium",
    label: "Medium",
    icon: "·",
    description: "Three balanced paragraphs for standard layouts.",
    config: { mode: "paragraphs", amount: 3, blockLength: "medium", seed: "medium-copy" },
  },
  {
    id: "long",
    label: "Long",
    icon: "·",
    description: "Five paragraphs for long-form content testing.",
    config: { mode: "paragraphs", amount: 5, blockLength: "medium", seed: "long-copy" },
  },
  {
    id: "article",
    label: "Article",
    icon: "·",
    description: "Eight long paragraphs with section headings.",
    config: { mode: "paragraphs", amount: 8, blockLength: "long", includeHeadings: true, seed: "article-layout" },
  },
  { id: "microcopy", label: "Microcopy", icon: "·", description: "Eight short sentences for helper text, status copy, and compact UI states.", config: { mode: "sentences", amount: 8, blockLength: "short", seed: "microcopy-set" } },
  { id: "cms-preview", label: "CMS preview", icon: "·", description: "Six medium paragraphs with headings and a list for editorial layout testing.", config: { mode: "paragraphs", amount: 6, blockLength: "medium", includeHeadings: true, includeLists: true, seed: "cms-preview" } },
  { id: "stress-test", label: "Content stress test", icon: "·", description: "Twelve long paragraphs for overflow, rhythm, and long-page performance checks.", config: { mode: "paragraphs", amount: 12, blockLength: "long", includeHeadings: true, includeLists: true, seed: "content-stress" } },
];

export const FEATURED_PRESETS = [
  DESIGN_PRESETS[0],
  DESIGN_PRESETS[1],
  DESIGN_PRESETS[3],
  DESIGN_PRESETS[4],
  DESIGN_PRESETS[8],
  DESIGN_PRESETS[9],
  DESIGN_PRESETS[10],
  DESIGN_PRESETS[12],
  DESIGN_PRESETS[13],
  DESIGN_PRESETS[15],
  LENGTH_PRESETS[2],
  LENGTH_PRESETS[5],
];
