import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, GitBranch, Layers3, RefreshCw, Scale, ShieldCheck } from "lucide-react";
import { Badge, Card } from "@/components/ui";
import { AtlasHeroScene, MotionSection, SplitTextReveal } from "@/components/motion";
import { absoluteUrl } from "@/features/tools/seo";
import { getWaysOfWorking } from "@/features/ways-of-working";
import { WaysExplorer } from "@/features/ways-of-working/components";

export const metadata: Metadata = {
  title: "Ways of Working — Agile, Scrum, Kanban, Waterfall, DevOps, and design processes | Darma",
  description: "Compare technology and product working methods through their purpose, flow, roles, cadence, artifacts, strengths, risks, and healthy signals.",
  keywords: ["Agile vs Scrum", "Scrum vs Kanban", "ways of working", "software development methodologies", "DevOps lifecycle", "Double Diamond", "Shape Up"],
  alternates: { canonical: "/ways-of-working" },
  openGraph: { title: "Darma Ways of Working Atlas", description: "Understand how product and technology teams organize discovery, delivery, flow, quality, and learning.", url: absoluteUrl("/ways-of-working"), type: "website" },
};
const PRINCIPLES = [
  { icon: Scale, title: "Compare the operating system", text: "The same ceremony can serve different purposes. Compare decisions, flow, roles, evidence, and constraints before choosing a label." },
  { icon: RefreshCw, title: "Methods must improve outcomes", text: "A healthy approach changes how work finishes, quality improves, feedback arrives, and teams learn—not only what meetings appear on calendars." },
  { icon: ShieldCheck, title: "No universal winner", text: "Product uncertainty, regulation, support demand, organizational design, and physical dependencies change which practices are appropriate." },
];
function jsonLd() { const ways = getWaysOfWorking(); return { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", "@id": `${absoluteUrl("/ways-of-working")}#collection`, name: "Darma Ways of Working Atlas", url: absoluteUrl("/ways-of-working"), description: "Practical comparisons of product, software, design, and delivery working methods." }, { "@type": "ItemList", numberOfItems: ways.length, itemListElement: ways.map((way, index) => ({ "@type": "ListItem", position: index + 1, name: way.title, url: absoluteUrl(`/ways-of-working/${way.slug}`) })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Ways of Working", item: absoluteUrl("/ways-of-working") }] }] }; }

export default function WaysOfWorkingPage() {
  const ways = getWaysOfWorking(); const data = jsonLd();
  return <div className="pb-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} />
    <section className="visual-grid-bg border-b border-[var(--color-border-subtle)]"><div className="mx-auto grid max-w-[var(--container-wide)] gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[minmax(0,1fr)_minmax(390px,.85fr)] lg:items-center lg:px-8 lg:py-20"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><Badge variant="soft">Darma Tech Atlas</Badge><Badge variant="outline">Team operating reference</Badge></div><SplitTextReveal text="Learn why a workflow exists before copying its meetings." className="mt-5 text-4xl font-black tracking-[-0.055em] text-[var(--color-text-primary)] sm:text-5xl lg:text-7xl" /><p className="mt-6 max-w-3xl text-base leading-8 text-[var(--color-text-secondary)] sm:text-lg">Explore principles, frameworks, methods, lifecycles, design processes, predictive models, and hybrids through the problems they solve and the risks they introduce.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#ways-explorer-title" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[var(--color-primary)] px-6 text-sm font-black text-[var(--color-primary-text)] shadow-[var(--shadow-md)]">Compare approaches <ArrowRight className="h-4 w-4" aria-hidden /></a><Link href="/tech-teams" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[var(--color-primary-border)] bg-[var(--color-primary-soft)] px-6 text-sm font-black text-[var(--color-primary)]"><Layers3 className="h-4 w-4" aria-hidden />See delivery in a team</Link></div></div><AtlasHeroScene src="/atlas/workflow-loop.svg" alt="A continuous product workflow loop connecting discovery, delivery, learning, and adaptation" priority labels={[`${ways.length} approaches`, "Flow before ceremony", "Compare constraints", "Inspect and adapt"]} /></div></section>
    <section className="mx-auto max-w-[var(--container-wide)] px-4 pb-10 sm:px-6 lg:px-8"><Card padding="lg" className="border-[var(--color-primary-border)]"><div className="flex items-center gap-2 text-[var(--color-primary)]"><GitBranch className="h-5 w-5" aria-hidden /><span className="font-mono text-xs font-bold uppercase tracking-[0.14em]">The distinction beginners need first</span></div><h2 className="mt-3 text-3xl font-black text-[var(--color-text-primary)]">Agile is not Scrum.</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--color-text-secondary)]">Agile expresses values and principles. Scrum is one framework for applying empirical product development. Kanban is a flow strategy that can improve an existing process. A team can follow Scrum ceremonies and still contradict agile values, or use agile principles without Scrum.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/ways-of-working/agile" className="text-sm font-bold text-[var(--color-primary)]">Read Agile principles →</Link><Link href="/ways-of-working/scrum" className="text-sm font-bold text-[var(--color-primary)]">Understand Scrum →</Link><Link href="/ways-of-working/kanban" className="text-sm font-bold text-[var(--color-primary)]">Understand Kanban →</Link></div></Card></section>
    <MotionSection as="section" className="mx-auto max-w-[var(--container-wide)] px-4 pb-10 sm:px-6 lg:px-8" distance={18}><div className="grid gap-4 md:grid-cols-3">{PRINCIPLES.map((principle) => { const Icon = principle.icon; return <Card key={principle.title} padding="md"><Icon className="h-5 w-5 text-[var(--color-primary)]" aria-hidden /><h2 className="mt-4 text-lg font-bold text-[var(--color-text-primary)]">{principle.title}</h2><p className="mt-2 text-sm leading-6 text-[var(--color-text-secondary)]">{principle.text}</p></Card>; })}</div></MotionSection>
    <WaysExplorer ways={ways} />
  </div>;
}
