import { createDefaultFlexState, createFlexItem } from "./flexbox";
import type { FlexPreset } from "./types";

const base = createDefaultFlexState();

export const FLEX_PRESETS: FlexPreset[] = [
  {
    id: "navbar",
    name: "Navbar",
    description: "Logo, navigation, search, and actions with responsive wrapping.",
    state: base,
  },
  {
    id: "centered-content",
    name: "Centered content",
    description: "Center one or more items on both axes.",
    state: {
      ...base,
      direction: "row",
      wrap: "nowrap",
      justifyContent: "center",
      alignItems: "center",
      minHeight: 360,
      items: [
        createFlexItem({ id: "center-card", name: "Centered card", content: "Centered card", flexBasis: "320px", background: "#4f46e5" }),
      ],
      selectedItemId: "center-card",
    },
  },
  {
    id: "wrapping-cards",
    name: "Wrapping cards",
    description: "Responsive cards that wrap to new rows as space changes.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "stretch",
      alignContent: "flex-start",
      items: ["Analytics", "Orders", "Customers", "Revenue", "Tasks", "Alerts"].map((name, index) =>
        createFlexItem({
          id: `card-${index + 1}`,
          name,
          content: name,
          flexGrow: 1,
          flexShrink: 1,
          flexBasis: "220px",
          background: ["#2563eb", "#0f766e", "#9333ea", "#ea580c", "#be123c", "#0f172a"][index],
        }),
      ),
      selectedItemId: "card-1",
    },
  },
  {
    id: "pricing-cards",
    name: "Pricing cards",
    description: "Equal width pricing cards with aligned heights.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "center",
      alignItems: "stretch",
      items: ["Starter", "Pro", "Business"].map((name, index) =>
        createFlexItem({
          id: `pricing-${index + 1}`,
          name,
          content: name,
          flexGrow: 1,
          flexShrink: 1,
          flexBasis: "260px",
          background: ["#2563eb", "#7c3aed", "#0f766e"][index],
        }),
      ),
      selectedItemId: "pricing-1",
    },
  },
  {
    id: "media-object",
    name: "Media object",
    description: "Avatar or image beside flexible text content.",
    state: {
      ...base,
      wrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "center",
      items: [
        createFlexItem({ id: "avatar", name: "Avatar", content: "Image", flexBasis: "96px", width: "96px", height: "96px", background: "#4f46e5" }),
        createFlexItem({ id: "body", name: "Body", content: "Flexible content area", flexGrow: 1, flexShrink: 1, flexBasis: "0", background: "#0f766e" }),
      ],
      selectedItemId: "body",
    },
  },
  {
    id: "toolbar",
    name: "Toolbar",
    description: "Toolbar actions with one item pushed to the end using auto margin.",
    state: {
      ...base,
      justifyContent: "flex-start",
      alignItems: "center",
      items: [
        createFlexItem({ id: "filter", name: "Filter", content: "Filter", flexBasis: "110px", background: "#2563eb" }),
        createFlexItem({ id: "sort", name: "Sort", content: "Sort", flexBasis: "100px", background: "#0f766e" }),
        createFlexItem({ id: "export", name: "Export", content: "Export", flexBasis: "120px", marginLeftAuto: true, background: "#ea580c" }),
      ],
      selectedItemId: "export",
    },
  },
  {
    id: "vertical-stack",
    name: "Vertical stack",
    description: "Column layout with controlled spacing and stretch alignment.",
    state: {
      ...base,
      direction: "column",
      wrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "stretch",
      items: ["Header", "Content", "Actions"].map((name, index) =>
        createFlexItem({
          id: `stack-${index + 1}`,
          name,
          content: name,
          flexGrow: index === 1 ? 1 : 0,
          flexBasis: index === 1 ? "0" : "auto",
          background: ["#4f46e5", "#0f766e", "#ea580c"][index],
        }),
      ),
      selectedItemId: "stack-2",
    },
  },
  {
    id: "split-hero",
    name: "Split hero",
    description: "Text and visual area split across a responsive row.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "space-between",
      alignItems: "center",
      minHeight: 360,
      items: [
        createFlexItem({ id: "hero-copy", name: "Hero copy", content: "Hero copy", flexGrow: 1, flexBasis: "320px", background: "#4f46e5" }),
        createFlexItem({ id: "hero-visual", name: "Hero visual", content: "Visual", flexGrow: 1, flexBasis: "320px", height: "220px", background: "#0f766e" }),
      ],
      selectedItemId: "hero-copy",
    },
  },
  {
    id: "form-actions",
    name: "Form actions",
    description: "Cancel action on the left and primary submit action pushed to the end.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "center",
      minHeight: 180,
      items: [
        createFlexItem({ id: "cancel", name: "Cancel", content: "Cancel", flexBasis: "120px", background: "#64748b" }),
        createFlexItem({ id: "save", name: "Save", content: "Save changes", flexBasis: "160px", marginLeftAuto: true, background: "#2563eb" }),
      ],
      selectedItemId: "save",
    },
  },
  {
    id: "feature-row",
    name: "Feature row",
    description: "Responsive feature cards with equal distribution and natural wrapping.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "stretch",
      items: ["Fast", "Accessible", "Reusable", "Exportable"].map((name, index) =>
        createFlexItem({
          id: `feature-${index + 1}`,
          name,
          content: name,
          flexGrow: 1,
          flexShrink: 1,
          flexBasis: "220px",
          background: ["#2563eb", "#0f766e", "#7c3aed", "#be123c"][index],
        }),
      ),
      selectedItemId: "feature-1",
    },
  },
  {
    id: "app-shell",
    name: "App shell",
    description: "Column shell with header, growing content, and footer actions.",
    state: {
      ...base,
      direction: "column",
      wrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "stretch",
      minHeight: 420,
      items: [
        createFlexItem({ id: "shell-header", name: "Header", content: "Header", flexBasis: "auto", background: "#0f172a" }),
        createFlexItem({ id: "shell-content", name: "Main", content: "Main content", flexGrow: 1, flexShrink: 1, flexBasis: "0", background: "#2563eb" }),
        createFlexItem({ id: "shell-footer", name: "Footer", content: "Footer actions", flexBasis: "auto", background: "#0f766e" }),
      ],
      selectedItemId: "shell-content",
    },
  },
  {
    id: "profile-header",
    name: "Profile header",
    description: "Avatar, flexible identity details, and account actions on one row.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "center",
      items: [
        createFlexItem({ id: "profile-avatar", name: "Avatar", content: "Avatar", flexBasis: "88px", width: "88px", height: "88px", background: "#7c3aed" }),
        createFlexItem({ id: "profile-info", name: "Profile info", content: "Name · role · status", flexGrow: 1, flexShrink: 1, flexBasis: "260px", background: "#0f766e" }),
        createFlexItem({ id: "profile-actions", name: "Actions", content: "Edit profile", flexBasis: "150px", marginLeftAuto: true, background: "#2563eb" }),
      ],
      selectedItemId: "profile-info",
    },
  },
  {
    id: "notification-row",
    name: "Notification row",
    description: "Icon, flexible message, timestamp, and trailing action for inbox UIs.",
    state: {
      ...base,
      wrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "center",
      items: [
        createFlexItem({ id: "notice-icon", name: "Icon", content: "!", flexBasis: "52px", width: "52px", background: "#ea580c" }),
        createFlexItem({ id: "notice-copy", name: "Message", content: "Your export is ready", flexGrow: 1, flexShrink: 1, flexBasis: "0", background: "#334155" }),
        createFlexItem({ id: "notice-time", name: "Time", content: "2m", flexBasis: "64px", background: "#64748b" }),
        createFlexItem({ id: "notice-action", name: "Action", content: "Open", flexBasis: "90px", background: "#2563eb" }),
      ],
      selectedItemId: "notice-copy",
    },
  },
  {
    id: "tabs-row",
    name: "Tabs row",
    description: "Horizontal tabs with a flexible spacer and a trailing utility action.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "center",
      items: [
        createFlexItem({ id: "tab-overview", name: "Overview", content: "Overview", flexBasis: "110px", background: "#2563eb" }),
        createFlexItem({ id: "tab-activity", name: "Activity", content: "Activity", flexBasis: "100px", background: "#64748b" }),
        createFlexItem({ id: "tab-settings", name: "Settings", content: "Settings", flexBasis: "100px", background: "#64748b" }),
        createFlexItem({ id: "tab-action", name: "Action", content: "Customize", flexBasis: "120px", marginLeftAuto: true, background: "#7c3aed" }),
      ],
      selectedItemId: "tab-overview",
    },
  },
  {
    id: "button-group",
    name: "Button group",
    description: "Compact primary, secondary, and destructive actions with consistent gaps.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "center",
      minHeight: 180,
      items: [
        createFlexItem({ id: "primary-action", name: "Primary", content: "Save", flexBasis: "100px", background: "#2563eb" }),
        createFlexItem({ id: "secondary-action", name: "Secondary", content: "Duplicate", flexBasis: "120px", background: "#475569" }),
        createFlexItem({ id: "danger-action", name: "Danger", content: "Delete", flexBasis: "100px", background: "#be123c" }),
      ],
      selectedItemId: "primary-action",
    },
  },
  {
    id: "chat-message",
    name: "Chat message",
    description: "Avatar beside a flexible message body and lightweight metadata.",
    state: {
      ...base,
      wrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      items: [
        createFlexItem({ id: "chat-avatar", name: "Avatar", content: "A", flexBasis: "56px", width: "56px", height: "56px", background: "#4f46e5" }),
        createFlexItem({ id: "chat-copy", name: "Message", content: "Flexible message content", flexGrow: 1, flexShrink: 1, flexBasis: "0", background: "#0f766e" }),
        createFlexItem({ id: "chat-meta", name: "Metadata", content: "10:42", flexBasis: "80px", background: "#64748b" }),
      ],
      selectedItemId: "chat-copy",
    },
  },
  {
    id: "footer-links",
    name: "Footer link groups",
    description: "Brand column plus wrapping link groups for a responsive site footer.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "space-between",
      alignItems: "flex-start",
      items: [
        createFlexItem({ id: "footer-brand", name: "Brand", content: "Darma · useful browser tools", flexGrow: 1, flexShrink: 1, flexBasis: "260px", background: "#0f172a" }),
        createFlexItem({ id: "footer-product", name: "Product", content: "Product links", flexGrow: 1, flexShrink: 1, flexBasis: "170px", background: "#2563eb" }),
        createFlexItem({ id: "footer-company", name: "Company", content: "Company links", flexGrow: 1, flexShrink: 1, flexBasis: "170px", background: "#7c3aed" }),
        createFlexItem({ id: "footer-legal", name: "Legal", content: "Legal links", flexGrow: 1, flexShrink: 1, flexBasis: "170px", background: "#0f766e" }),
      ],
      selectedItemId: "footer-brand",
    },
  },
  {
    id: "breadcrumb-actions",
    name: "Breadcrumb + actions",
    description: "Breadcrumb trail on the left with page actions pushed to the right.",
    state: {
      ...base,
      wrap: "wrap",
      justifyContent: "flex-start",
      alignItems: "center",
      minHeight: 180,
      items: [
        createFlexItem({ id: "breadcrumbs", name: "Breadcrumbs", content: "Home / Projects / Darma", flexGrow: 1, flexShrink: 1, flexBasis: "260px", background: "#334155" }),
        createFlexItem({ id: "share", name: "Share", content: "Share", flexBasis: "100px", marginLeftAuto: true, background: "#64748b" }),
        createFlexItem({ id: "new-item", name: "New item", content: "New item", flexBasis: "120px", background: "#2563eb" }),
      ],
      selectedItemId: "breadcrumbs",
    },
  }
];
