import { Button, Input } from "@/components/ui";
import { ControlGrid, ControlSection, NumberField, PresetGallery, SegmentedControl, ToolControlPanel } from "@/features/tools/components";
import { RESPONSIVE_IMAGE_PRESETS } from "../presets";
import type { ImageCandidate, ResponsiveImageMode, ResponsiveImageState, SizesRule } from "../types";

export function ResponsiveImageControls({ state, onPatch, onLoadPreset, onUpdateCandidate, onUpdateSizeRule, onAddCandidate, onAddSizeRule }: { state: ResponsiveImageState; onPatch: (patch: Partial<ResponsiveImageState>) => void; onLoadPreset: (state: ResponsiveImageState) => void; onUpdateCandidate: (id: string, patch: Partial<ImageCandidate>) => void; onUpdateSizeRule: (id: string, patch: Partial<SizesRule>) => void; onAddCandidate: () => void; onAddSizeRule: () => void }) {
  return <ToolControlPanel title="Image settings" description="Define candidates, sizes, and output mode.">
    <ControlSection title="Presets"><PresetGallery presets={RESPONSIVE_IMAGE_PRESETS} selectedId={state.presetId} onSelect={(_, preset) => onLoadPreset(preset.state)} getId={(preset) => preset.id} getLabel={(preset) => preset.name} getDescription={(preset) => preset.description} /></ControlSection>
    <ControlSection title="Mode"><SegmentedControl ariaLabel="Responsive image output mode" value={state.mode} onChange={(mode: ResponsiveImageMode) => onPatch({ mode })} options={[{ value: "img", label: "img" }, { value: "picture", label: "picture" }, { value: "next-image", label: "Next.js" }]} /></ControlSection>
    <ControlSection title="Attributes"><ControlGrid columns={2}><NumberField label="Width" value={state.attributes.width} min={1} max={6000} unit="px" onChange={(width) => onPatch({ attributes: { ...state.attributes, width } })} /><NumberField label="Height" value={state.attributes.height} min={1} max={6000} unit="px" onChange={(height) => onPatch({ attributes: { ...state.attributes, height } })} /></ControlGrid><div className="mt-3 space-y-2"><Input size="sm" value={state.fallbackSrc} onChange={(e) => onPatch({ fallbackSrc: e.target.value })} aria-label="Fallback source" /><Input size="sm" value={state.attributes.alt} onChange={(e) => onPatch({ attributes: { ...state.attributes, alt: e.target.value } })} aria-label="Alt text" /></div></ControlSection>
    <ControlSection title="Candidates" action={<Button size="sm" variant="secondary" onClick={onAddCandidate}>Add</Button>}>{state.candidates.map((candidate) => <CandidateRow key={candidate.id} candidate={candidate} onUpdate={(patch) => onUpdateCandidate(candidate.id, patch)} />)}</ControlSection>
    <ControlSection title="Sizes rules" action={<Button size="sm" variant="secondary" onClick={onAddSizeRule}>Add</Button>}>{state.sizes.map((rule) => <SizeRuleRow key={rule.id} rule={rule} onUpdate={(patch) => onUpdateSizeRule(rule.id, patch)} />)}<Input size="sm" value={state.defaultSlotSize} onChange={(e) => onPatch({ defaultSlotSize: e.target.value })} aria-label="Default slot size" /></ControlSection>
  </ToolControlPanel>;
}
function CandidateRow({ candidate, onUpdate }: { candidate: ImageCandidate; onUpdate: (patch: Partial<ImageCandidate>) => void }) { return <div className="grid gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface-strong)] p-2 sm:grid-cols-[1fr_auto]"><Input size="sm" value={candidate.url} onChange={(e) => onUpdate({ url: e.target.value })} aria-label="Candidate URL" /><NumberField label="Width" value={candidate.width} min={1} max={8000} unit="w" onChange={(width) => onUpdate({ width })} /></div>; }
function SizeRuleRow({ rule, onUpdate }: { rule: SizesRule; onUpdate: (patch: Partial<SizesRule>) => void }) { return <div className="grid gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface-strong)] p-2 sm:grid-cols-2"><Input size="sm" value={rule.mediaCondition} onChange={(e) => onUpdate({ mediaCondition: e.target.value })} aria-label="Media condition" /><Input size="sm" value={rule.slotSize} onChange={(e) => onUpdate({ slotSize: e.target.value })} aria-label="Slot size" /></div>; }
