import type { RegexExample, RegexFlag } from "./types";

export const DEFAULT_PATTERN = "(?<name>[A-Z][a-z]+)\\s+(?<id>#[0-9]{3})";
export const DEFAULT_FLAGS = "g";
export const DEFAULT_REPLACEMENT = "$<id> - $<name>";

export const SAMPLE_TEXT = `Order Alpha #102 is ready.
Order Beta #205 is delayed.
order gamma #309 is lowercase and will not match until you enable i.`;

export const FLAG_OPTIONS: { flag: RegexFlag; label: string; description: string }[] = [
  { flag: "g", label: "g", description: "Global — find every match" },
  { flag: "i", label: "i", description: "Ignore letter case" },
  { flag: "m", label: "m", description: "Multiline anchors" },
  { flag: "s", label: "s", description: "Dot matches newlines" },
  { flag: "u", label: "u", description: "Unicode-aware matching" },
  { flag: "y", label: "y", description: "Sticky matching" },
  { flag: "d", label: "d", description: "Capture match indices" },
];

export const REGEX_EXAMPLES: RegexExample[] = [
  {
    id: "emails",
    label: "Email finder",
    pattern: "[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}",
    flags: "gi",
    text: "Contact support@example.com or admin@darma.dev for access.",
    replacement: "[email]",
    description: "Extract common email-like strings.",
    category: "extract",
  },
  {
    id: "named-date",
    label: "Date reformat",
    pattern: "(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})",
    flags: "g",
    text: "Created 2026-05-22 and updated 2026-06-01.",
    replacement: "$<day>/$<month>/$<year>",
    description: "Reuse named groups in replacement output.",
    category: "transform",
  },
  {
    id: "todo-lines",
    label: "TODO lines",
    pattern: "^TODO:.*$",
    flags: "gm",
    text: "TODO: add tests\nDone: wire UI\nTODO: review copy",
    replacement: "- $&",
    description: "Use multiline anchors to select full lines.",
    category: "extract",
  },
  {
    id: "hex-colors",
    label: "Hex colors",
    pattern: "#(?:[0-9a-fA-F]{3}){1,2}\\b",
    flags: "g",
    text: "Primary #2563eb, surface #fff, danger #dc2626.",
    replacement: "var(--color-token)",
    description: "Find short and long CSS hex colors.",
    category: "extract",
  },
  {
    id: "duplicate-spaces",
    label: "Extra spaces",
    pattern: "[ \\t]{2,}",
    flags: "g",
    text: "Clean   repeated spaces,\t\tbut keep\nline breaks intact.",
    replacement: " ",
    description: "Collapse repeated horizontal whitespace.",
    category: "cleanup",
  },
  {
    id: "username",
    label: "Username rule",
    pattern: "^[A-Za-z][A-Za-z0-9_-]{2,19}$",
    flags: "",
    text: "darma_user-26",
    replacement: "$&",
    description: "Validate a 3–20 character username.",
    category: "validate",
  },
  {
    id: "urls",
    label: "URL finder",
    pattern: "https?:\\/\\/[^\\s<>()]+",
    flags: "gi",
    text: "Docs: https://example.com/docs and status: http://status.example.com/page.",
    replacement: "[url]",
    description: "Find common HTTP and HTTPS links in free text.",
    category: "extract",
  },
  {
    id: "uuid",
    label: "UUID finder",
    pattern: "\\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\b",
    flags: "gi",
    text: "Request 550e8400-e29b-41d4-a716-446655440000 completed; legacy id ABC-12 ignored.",
    replacement: "[uuid]",
    description: "Extract common RFC 4122-style UUID strings.",
    category: "extract",
  },
  {
    id: "ipv4",
    label: "IPv4-like finder",
    pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b",
    flags: "g",
    text: "Gateway 192.168.1.1 responded; test host 10.0.0.24 timed out.",
    replacement: "[ip]",
    description: "Find IPv4-shaped values; validate numeric octets separately when correctness matters.",
    category: "extract",
  },
  {
    id: "slugs",
    label: "Slug rule",
    pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
    flags: "",
    text: "browser-only-tools",
    replacement: "$&",
    description: "Validate a lowercase kebab-case URL slug.",
    category: "validate",
  },
  {
    id: "semantic-version",
    label: "Semantic version finder",
    pattern: "\\bv?(\\d+)\\.(\\d+)\\.(\\d+)(?:-([0-9A-Za-z.-]+))?(?:\\+([0-9A-Za-z.-]+))?\\b",
    flags: "g",
    text: "Current v3.2.1, beta 4.0.0-beta.2, old release 2.9.0.",
    replacement: "version:$&",
    description: "Find common semantic-version strings including prerelease labels.",
    category: "extract",
  },
  {
    id: "markdown-links",
    label: "Markdown links",
    pattern: "\\[([^\\]]+)\\]\\((https?:\\/\\/[^)]+)\\)",
    flags: "g",
    text: "Read [Darma docs](https://example.com/docs) or [release notes](https://example.com/changelog).",
    replacement: "$1 — $2",
    description: "Capture link labels and HTTP(S) targets from basic Markdown links.",
    category: "transform",
  },
  {
    id: "quoted-values",
    label: "Quoted values",
    pattern: "([\"'])(.*?)\\1",
    flags: "g",
    text: "status='ready' owner=\"Mira\" note='review tomorrow'",
    replacement: "[$2]",
    description: "Extract simple single- or double-quoted values.",
    category: "extract",
  },
  {
    id: "currency",
    label: "Currency amounts",
    pattern: "(?:[$€£]\\s?\\d+(?:[,.]\\d{2})?)",
    flags: "g",
    text: "Starter $19.00, Pro €49.00, Enterprise £120.00.",
    replacement: "[price]",
    description: "Find simple symbol-prefixed currency amounts for cleanup or review.",
    category: "extract",
  },
  {
    id: "css-units",
    label: "CSS dimensions",
    pattern: "-?\\d*\\.?\\d+(?:px|rem|em|vh|vw|%|ch)\\b",
    flags: "gi",
    text: "padding: 1.5rem; width: 80%; transform: translateX(-12px); max-width: 72ch;",
    replacement: "[size]",
    description: "Find common CSS numeric dimensions and units.",
    category: "extract",
  },
  {
    id: "query-params",
    label: "Query parameter pairs",
    pattern: "[?&]([^=&?#]+)=([^&#]*)",
    flags: "g",
    text: "https://example.com/search?q=css+grid&page=2&sort=recent",
    replacement: "$1=$2",
    description: "Capture key/value pairs from a simple URL query string.",
    category: "extract",
  },
  {
    id: "blank-lines",
    label: "Repeated blank lines",
    pattern: "(?:\\r?\\n)[ \\t]*(?:\\r?\\n){2,}",
    flags: "g",
    text: "Heading\\n\\n\\n\\nParagraph one.\\n\\nParagraph two.",
    replacement: "\\n\\n",
    description: "Collapse runs of empty lines to one paragraph break.",
    category: "cleanup",
  },
  {
    id: "log-levels",
    label: "Log lines by level",
    pattern: "^(ERROR|WARN):\\s+(.+)$",
    flags: "gm",
    text: "INFO: server started\\nWARN: cache miss\\nERROR: request failed\\nDEBUG: retrying",
    replacement: "$1 — $2",
    description: "Select warning and error lines from a simple multiline log.",
    category: "extract",
  },
  {
    id: "html-tags",
    label: "Simple HTML tags",
    pattern: "<([A-Za-z][A-Za-z0-9-]*)(?:\\s[^>]*)?>|<\\/([A-Za-z][A-Za-z0-9-]*)\\s*>",
    flags: "g",
    text: "<article><h2>Title</h2><p class=\"lead\">Copy</p></article>",
    replacement: "[tag]",
    description: "Find simple opening and closing HTML tags for inspection, not full HTML parsing.",
    category: "extract",
  },
  {
    id: "phone-like",
    label: "Phone-like finder",
    pattern: "\\+?\\d[\\d .()-]{7,}\\d",
    flags: "g",
    text: "Office +972 59 123 4567; backup (020) 7946 0958.",
    replacement: "[phone]",
    description: "Find phone-shaped strings; use a dedicated library for country-specific validation.",
    category: "extract",
  },
];

export const CHEATSHEET = [
  { token: ".", meaning: "Any character except newline unless s is enabled" },
  { token: "\\d / \\w / \\s", meaning: "Digit / word character / whitespace" },
  { token: "^ / $", meaning: "Start / end anchor" },
  { token: "* + ?", meaning: "Zero or more / one or more / optional" },
  { token: "{2,5}", meaning: "Repeat between 2 and 5 times" },
  { token: "(...) / (?:...)", meaning: "Capture / non-capturing group" },
  { token: "(?<name>...)", meaning: "Named capture group" },
  { token: "$& / $1 / $<name>", meaning: "Replacement references" },
];
