/**
 * Starter dictionary: a curated list of common English words authored for
 * Darma so the tool works instantly with clear provenance. It is intentionally
 * small — for tournament play, load a full word list (TWL/SOWPODS) via the
 * "Load dictionary" button. This is NOT a sanctioned Scrabble word list.
 */
export const STARTER_WORDS: string[] = [
  // 2-letter
  "aa", "ab", "ad", "ae", "ag", "ah", "ai", "am", "an", "ar", "as", "at", "aw", "ax", "ay",
  "be", "bi", "bo", "by", "de", "do", "ed", "ef", "eh", "el", "em", "en", "er", "es", "et", "ex",
  "fa", "go", "ha", "he", "hi", "ho", "id", "if", "in", "is", "it", "jo", "ka", "la", "li", "lo",
  "ma", "me", "mi", "mo", "mu", "my", "na", "no", "nu", "od", "oe", "of", "oh", "oi", "om", "on",
  "op", "or", "os", "ow", "ox", "oy", "pa", "pe", "pi", "qi", "re", "sh", "si", "so", "ta", "ti",
  "to", "uh", "um", "un", "up", "us", "ut", "we", "wo", "xi", "xu", "ya", "ye", "yo", "za",
  // 3-letter
  "ace", "act", "add", "age", "ago", "aid", "aim", "air", "ale", "all", "and", "ant", "any", "ape",
  "arc", "are", "arm", "art", "ash", "ask", "ate", "awe", "axe", "bad", "bag", "ban", "bar", "bat",
  "bay", "bed", "bee", "beg", "bet", "bid", "big", "bin", "bit", "boa", "bob", "bog", "bow", "box",
  "boy", "bra", "bud", "bug", "bun", "bus", "but", "buy", "cab", "cap", "car", "cat", "cob", "cod",
  "cog", "con", "cop", "cot", "cow", "coy", "cry", "cub", "cud", "cue", "cup", "cur", "cut", "dab",
  "dam", "day", "den", "dew", "did", "die", "dig", "dim", "din", "dip", "doe", "dog", "don", "dot",
  "dry", "dub", "due", "dug", "dye", "ear", "eat", "ebb", "eel", "egg", "ego", "elf", "elk", "elm",
  "end", "era", "eve", "ewe", "eye", "fab", "fad", "fan", "far", "fat", "fax", "fed", "fee", "few",
  "fib", "fig", "fin", "fir", "fit", "fix", "flu", "fly", "foe", "fog", "for", "fox", "fry", "fun",
  "fur", "gag", "gap", "gas", "gel", "gem", "get", "gig", "gin", "god", "got", "gum", "gun", "gut",
  "guy", "gym", "had", "ham", "has", "hat", "hay", "hem", "hen", "her", "hew", "hex", "hid", "him",
  "hip", "his", "hit", "hoe", "hog", "hop", "hot", "how", "hub", "hue", "hug", "hum", "hut", "ice",
  "icy", "ill", "imp", "ink", "inn", "ion", "ire", "irk", "ivy", "jab", "jam", "jar", "jaw", "jay",
  "jet", "jig", "job", "jog", "jot", "joy", "jug", "keg", "key", "kid", "kin", "kit", "lab", "lad",
  "lag", "lap", "law", "lax", "lay", "led", "leg", "let", "lid", "lie", "lip", "lit", "lob", "log",
  "lot", "low", "mad", "man", "map", "mat", "may", "men", "met", "mix", "mob", "mod", "mom", "mop",
  "mud", "mug", "mum", "nab", "nag", "nap", "net", "new", "nib", "nil", "nip", "nod", "nor", "not",
  "now", "nub", "nut", "oak", "oar", "oat", "odd", "off", "oil", "old", "one", "opt", "orb", "ore",
  "our", "out", "owe", "owl", "own", "pad", "pan", "par", "pat", "paw", "pay", "pea", "peg", "pen",
  "pet", "pew", "pie", "pig", "pin", "pit", "ply", "pod", "pop", "pot", "pro", "pry", "pub", "pug",
  "pun", "pup", "put", "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "rib", "rid", "rig",
  "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub", "rug", "rum", "run", "rut", "rye", "sad",
  "sag", "sap", "sat", "saw", "say", "sea", "see", "set", "sew", "she", "shy", "sin", "sip", "sir",
  "sit", "six", "ski", "sky", "sly", "sob", "sod", "son", "sow", "soy", "spa", "spy", "sty", "sub",
  "sue", "sum", "sun", "tab", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the", "thy", "tic",
  "tie", "tin", "tip", "toe", "ton", "too", "top", "tot", "tow", "toy", "try", "tub", "tug", "tux",
  "two", "urn", "use", "van", "vat", "vet", "via", "vie", "vim", "vow", "wad", "wag", "war", "was",
  "wax", "way", "web", "wed", "wee", "wet", "who", "why", "wig", "win", "wit", "woe", "wok", "won",
  "wry", "yak", "yam", "yap", "yaw", "yea", "yen", "yes", "yet", "yew", "yin", "you", "zag", "zap",
  "zed", "zen", "zig", "zip", "zit", "zoo",
  // 4-letter
  "able", "acid", "aged", "also", "area", "army", "atom", "aunt", "auto", "away", "baby", "back",
  "bake", "ball", "band", "bank", "bare", "barn", "base", "bath", "beam", "bean", "bear", "beat",
  "beer", "bell", "belt", "bend", "best", "bird", "bite", "blue", "boat", "body", "bold", "bolt",
  "bone", "book", "boot", "born", "boss", "both", "bowl", "brew", "bulk", "burn", "bush", "busy",
  "cafe", "cage", "cake", "calm", "came", "camp", "card", "care", "cart", "case", "cash", "cast",
  "cave", "cell", "chat", "chef", "chip", "city", "clap", "claw", "clay", "clip", "club", "clue",
  "coal", "coat", "code", "coin", "cold", "come", "cook", "cool", "cope", "copy", "cord", "core",
  "corn", "cost", "crew", "crop", "cube", "cure", "cute", "damp", "dark", "dash", "data", "date",
  "dawn", "days", "dead", "deaf", "deal", "dear", "debt", "deck", "deep", "deer", "desk", "dial",
  "dice", "diet", "dine", "dirt", "dish", "dive", "dock", "does", "dome", "done", "door", "dose",
  "down", "drag", "draw", "drip", "drop", "drum", "dual", "duck", "dull", "dumb", "dune", "dusk",
  "dust", "duty", "each", "earl", "earn", "ease", "east", "easy", "echo", "edge", "edit", "envy",
  "epic", "even", "ever", "evil", "exam", "exit", "face", "fact", "fade", "fail", "fair", "fall",
  "fame", "farm", "fast", "fate", "fear", "feat", "feed", "feel", "feet", "fell", "felt", "file",
  "fill", "film", "find", "fine", "fire", "firm", "fish", "fist", "five", "flag", "flat", "flaw",
  "flee", "flew", "flip", "flow", "foam", "fold", "folk", "font", "food", "fool", "foot", "ford",
  "fork", "form", "fort", "four", "free", "frog", "fuel", "full", "fund", "fury", "fuse", "gain",
  "gale", "game", "gang", "gate", "gaze", "gear", "gene", "gift", "girl", "give", "glad", "glow",
  "glue", "goal", "goat", "gold", "golf", "gone", "good", "gown", "grab", "gray", "grew", "grid",
  "grim", "grin", "grip", "grow", "gulf", "hail", "hair", "half", "hall", "halt", "hand", "hang",
  "hard", "harm", "hate", "have", "hawk", "haze", "head", "heal", "heap", "hear", "heat", "heel",
  "held", "hell", "helm", "help", "herb", "herd", "here", "hero", "hide", "high", "hill", "hint",
  "hire", "hold", "hole", "holy", "home", "hood", "hook", "hope", "horn", "hose", "host", "hour",
  "huge", "hull", "hunt", "hurt", "hymn", "icon", "idea", "idle", "inch", "into", "iron", "isle",
  "item", "jade", "jail", "jazz", "jeep", "jerk", "join", "joke", "jump", "junk", "jury", "just",
  "keen", "keep", "kelp", "kick", "kill", "kind", "king", "kiss", "kite", "knee", "knew", "knit",
  "knob", "knot", "know", "lace", "lack", "lady", "lake", "lamb", "lamp", "land", "lane", "last",
  "late", "lawn", "lazy", "lead", "leaf", "leak", "lean", "leap", "left", "lend", "lens", "less",
  "life", "lift", "like", "limb", "lime", "line", "link", "lion", "list", "live", "load", "loaf",
  "loan", "lock", "loft", "lone", "long", "look", "loop", "lord", "lose", "loss", "lost", "loud",
  "love", "luck", "lump", "lung", "lure", "lush", "mace", "made", "mail", "main", "make", "male",
  "mall", "many", "mask", "mass", "mate", "maze", "meal", "mean", "meat", "meet", "melt", "mend",
  "menu", "mere", "mesh", "mild", "mile", "milk", "mill", "mind", "mine", "mint", "miss", "mist",
  "mode", "mold", "mole", "monk", "mood", "moon", "more", "moss", "most", "moth", "move", "much",
  "mule", "muse", "must", "mute", "myth", "nail", "name", "navy", "near", "neat", "neck", "need",
  "nest", "news", "next", "nice", "nine", "node", "none", "noon", "nose", "note", "noun", "numb",
  "oath", "obey", "odor", "okay", "once", "only", "onto", "open", "oral", "oven", "over", "pace",
  "pack", "page", "paid", "pain", "pair", "pale", "palm", "pane", "park", "part", "pass", "past",
  "path", "peak", "pear", "peel", "peer", "pest", "pick", "pier", "pile", "pill", "pine", "pink",
  "pint", "pipe", "plan", "play", "plea", "plot", "plow", "plug", "plum", "plus", "poem", "poet",
  "poke", "pole", "poll", "pond", "pony", "pool", "poor", "pope", "pore", "port", "pose", "post",
  "pour", "pray", "prey", "prop", "pull", "pulp", "pump", "punk", "pure", "push", "quit", "quiz",
  "race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "rank", "rare", "rate", "read",
  "real", "reap", "rear", "reed", "reef", "reel", "rely", "rent", "rest", "rice", "rich", "ride",
  "ring", "riot", "ripe", "rise", "risk", "road", "roam", "roar", "robe", "rock", "role", "roll",
  "roof", "room", "root", "rope", "rose", "ruby", "rude", "ruin", "rule", "rung", "rush",
  "rust", "sack", "safe", "sage", "said", "sail", "sake", "salt", "same", "sand", "save", "scan",
  "scar", "seal", "seam", "seat", "seed", "seek", "seem", "seen", "self", "sell", "send", "sent",
  "ship", "shoe", "shop", "shot", "show", "shut", "sick", "side", "sigh", "sign", "silk", "sill",
  "sing", "sink", "site", "size", "skin", "skip", "slab", "slam", "slap", "sled", "slid", "slim",
  "slip", "slot", "slow", "snap", "snow", "soap", "sock", "soft", "soil", "sold", "sole", "solo",
  "some", "song", "soon", "sort", "soul", "soup", "sour", "span", "spin", "spot", "spun", "spur",
  "star", "stay", "stem", "step", "stir", "stop", "stub", "stud", "such", "suit", "sung", "sunk",
  "sure", "surf", "swam", "swan", "swap", "sway", "swim", "tail", "take", "tale", "talk", "tall",
  "tank", "tape", "task", "taxi", "teal", "team", "tear", "tell", "tend", "tent", "term", "test",
  "text", "than", "that", "thaw", "them", "then", "they", "thin", "this", "thus", "tick", "tide",
  "tidy", "tier", "tile", "till", "time", "tiny", "tire", "toad", "toil", "told", "toll", "tomb",
  "tone", "tool", "torn", "tour", "town", "trap", "tray", "tree", "trek", "trim", "trip", "trot",
  "true", "tube", "tuck", "tuna", "tune", "turf", "turn", "twin", "type", "ugly", "undo", "unit",
  "upon", "urge", "used", "user", "vain", "vale", "vary", "vase", "vast", "veal", "veil", "vein",
  "verb", "very", "vest", "vibe", "vice", "view", "vine", "visa", "void", "vote", "wade", "wage",
  "wait", "wake", "walk", "wall", "wand", "want", "ward", "ware", "warm", "warn", "wart", "wash",
  "wasp", "wave", "wavy", "waxy", "weak", "wear", "weed", "week", "well", "went", "were", "west",
  "wharf", "what", "when", "whip", "whom", "wide", "wife", "wild", "will", "wind", "wine", "wing",
  "wink", "wipe", "wire", "wise", "wish", "with", "wolf", "wood", "wool", "word", "wore", "work",
  "worm", "worn", "wrap", "yard", "yarn", "yawn", "yeah", "year", "yell", "yoga", "yolk", "your",
  "zeal", "zero", "zone", "zoom",
  // 5-8 letter (common)
  "about", "above", "actor", "adapt", "admit", "adopt", "adult", "after", "again", "agent", "agree",
  "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along", "aloud", "alpha",
  "alter", "amber", "amend", "among", "angel", "anger", "angle", "angry", "apart", "apple", "apply",
  "arena", "argue", "arise", "armor", "aroma", "array", "arrow", "aside", "asset", "audio", "audit",
  "avoid", "awake", "award", "aware", "badge", "baker", "basic", "batch", "beach", "beard", "beast",
  "begin", "being", "below", "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
  "blaze", "bleak", "blend", "bless", "blind", "block", "blond", "blood", "bloom", "board", "boast",
  "bonus", "boost", "booth", "brain", "brake", "brand", "brave", "bread", "break", "breed", "brick",
  "bride", "brief", "bring", "brink", "brisk", "broad", "brook", "brown", "brush", "build", "built",
  "bunch", "burst", "cabin", "cable", "camel", "canal", "candy", "cargo", "carve", "catch", "cause",
  "cease", "chain", "chair", "chalk", "charm", "chart", "chase", "cheap", "cheat", "check", "cheek",
  "cheer", "chess", "chest", "chief", "child", "chill", "china", "choir", "chord", "chose", "civil",
  "claim", "clamp", "clash", "class", "clean", "clear", "clerk", "click", "cliff", "climb", "cloak",
  "clock", "close", "cloth", "cloud", "clown", "coach", "coast", "color", "couch", "cough", "could",
  "count", "court", "cover", "crack", "craft", "crane", "crash", "crawl", "crazy", "cream", "creek",
  "crest", "crime", "crisp", "cross", "crowd", "crown", "crude", "cruel", "crush", "crust", "curve",
  "cycle", "daily", "dairy", "dance", "dealt", "death", "debut", "decay", "delay", "delta", "dense",
  "depth", "diary", "digit", "dirty", "ditch", "diver", "dizzy", "dodge", "donor", "doubt", "dough",
  "dozen", "draft", "drain", "drama", "drank", "dream", "dress", "dried", "drift", "drill", "drink",
  "drive", "drone", "drove", "drown", "dwell", "eager", "eagle", "early", "earth", "easel", "eaten",
  "ebony", "eight", "elbow", "elder", "elect", "elite", "email", "ember", "empty", "enact", "endow",
  "enemy", "enjoy", "enter", "entry", "equal", "erase", "error", "essay", "event", "every", "exact",
  "excel", "exist", "extra", "fable", "faith", "false", "fancy", "fatal", "fault", "favor", "feast",
  "fetch", "fever", "fiber", "field", "fiery", "fifth", "fifty", "fight", "final", "first", "flame",
  "flash", "fleet", "flesh", "float", "flock", "flood", "floor", "flour", "fluid", "flush", "focus",
  "force", "forge", "forth", "forty", "forum", "found", "frame", "frank", "fraud", "fresh", "front",
  "frost", "fruit", "fully", "funny", "genre", "ghost", "giant", "given", "glass", "gleam", "globe",
  "glory", "glove", "grace", "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass",
  "grave", "great", "greed", "green", "greet", "grief", "grill", "gross", "group", "grove", "guard",
  "guess", "guest", "guide", "guilt", "habit", "hairy", "happy", "harsh", "haste", "haven", "heart",
  "heavy", "hedge", "hello", "hence", "hobby", "honor", "horse", "hotel", "house", "hover", "human",
  "humid", "humor", "hurry", "ideal", "image", "index", "inner", "input", "issue", "ivory", "jelly",
  "jewel", "joint", "jolly", "judge", "juice", "known", "label", "labor", "large", "laser", "later",
  "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon", "level", "light", "limit",
  "liver", "lobby", "local", "logic", "loose", "lorry", "loser", "lower", "loyal", "lucky", "lunar",
  "lunch", "lying", "magic", "major", "maker", "mango", "maple", "march", "marsh", "match", "mayor",
  "medal", "media", "melon", "mercy", "merge", "merit", "metal", "meter", "midst", "might", "minor",
  "minus", "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth", "movie",
  "music", "naive", "naked", "nasty", "naval", "nerve", "never", "newer", "night", "noble", "noise",
  "north", "novel", "nurse", "occur", "ocean", "offer", "often", "olive", "onion", "onset", "opera",
  "orbit", "order", "organ", "other", "ought", "ounce", "outer", "owner", "paint", "panel", "panic",
  "paper", "party", "pasta", "patch", "pause", "peace", "pearl", "penny", "perch", "phase", "phone",
  "photo", "piano", "piece", "pilot", "pinch", "pitch", "pixel", "pizza", "place", "plain", "plane",
  "plant", "plate", "plaza", "plead", "plot", "plumb", "point", "polar", "porch", "pound", "power",
  "press", "price", "pride", "prime", "print", "prior", "prize", "probe", "proof", "proud", "prove",
  "pulse", "punch", "pupil", "purse", "queen", "query", "quest", "queue", "quick", "quiet", "quilt",
  "quite", "quota", "quote", "radar", "radio", "raise", "rally", "ranch", "range", "rapid", "ratio",
  "reach", "react", "ready", "realm", "rebel", "refer", "reign", "relax", "relay", "reply", "rider",
  "ridge", "rifle", "right", "rigid", "risky", "rival", "river", "roast", "robin", "robot", "rocky",
  "rogue", "roman", "rough", "round", "route", "royal", "rugby", "ruler", "rumor", "rural", "salad",
  "sauce", "scale", "scare", "scene", "scent", "scope", "score", "scout", "scrap", "screw", "seize",
  "sense", "serve", "seven", "shade", "shaft", "shake", "shall", "shame", "shape", "share", "shark",
  "sharp", "sheep", "sheet", "shelf", "shell", "shift", "shine", "shiny", "shirt", "shock", "shoot",
  "shore", "short", "shout", "shown", "sight", "silly", "since", "siren", "sixth", "sixty", "skate",
  "skill", "skull", "slack", "slate", "sleep", "slice", "slide", "slope", "small", "smart", "smell",
  "smile", "smoke", "snack", "snake", "sneak", "solar", "solid", "solve", "sonic", "sorry", "sound",
  "south", "space", "spade", "spare", "spark", "speak", "spear", "speed", "spell", "spend", "spent",
  "spice", "spicy", "spike", "spine", "split", "spoke", "spoon", "sport", "spray", "spread", "squad",
  "stack", "staff", "stage", "stain", "stair", "stake", "stall", "stamp", "stand", "stare", "start",
  "state", "steak", "steam", "steel", "steep", "steer", "stern", "stick", "stiff", "still", "sting",
  "stock", "stone", "stood", "stool", "store", "storm", "story", "stove", "strap", "straw", "strip",
  "study", "stuff", "style", "sugar", "suite", "sunny", "super", "surge", "swamp", "swarm", "swear",
  "sweat", "sweep", "sweet", "swell", "swift", "swing", "sword", "table", "taken", "tally", "tango",
  "taper", "taste", "teach", "tempo", "tenth", "thank", "theft", "their", "theme", "there", "these",
  "thick", "thief", "thing", "think", "third", "those", "three", "threw", "throw", "thumb", "tiger",
  "tight", "timer", "title", "toast", "today", "token", "tooth", "topic", "torch", "total", "touch",
  "tough", "tower", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash", "treat",
  "trend", "trial", "tribe", "trick", "tried", "troop", "trout", "truck", "truly", "trunk", "trust",
  "truth", "tulip", "tutor", "twice", "twist", "ultra", "uncle", "under", "undue", "unify", "union",
  "unite", "unity", "until", "upper", "upset", "urban", "usage", "usher", "usual", "vague", "valid",
  "value", "valve", "vapor", "vault", "venue", "verse", "video", "villa", "vinyl", "viral", "virus",
  "visit", "vital", "vivid", "vocal", "vodka", "voice", "vowel", "wagon", "waist", "waste", "watch",
  "water", "weary", "weave", "wedge", "weigh", "weird", "whale", "wharf", "wheat", "wheel", "where",
  "which", "while", "white", "whole", "whose", "widen", "wider", "widow", "width", "wield", "witch",
  "woman", "world", "worry", "worse", "worst", "worth", "would", "wound", "woven", "wrist", "write",
  "wrong", "wrote", "yacht", "yeast", "yield", "young", "youth", "zebra",
  "ability", "absence", "academy", "account", "accuse", "achieve", "acquire", "address", "advance",
  "adventure", "already", "amazing", "analyze", "ancient", "another", "anxiety", "anymore", "anytime",
  "balance", "battery", "because", "believe", "benefit", "between", "brother", "capable", "capital",
  "captain", "capture", "careful", "century", "certain", "chamber", "channel", "chapter", "charity",
  "citizen", "clarity", "climate", "clothes", "collect", "college", "combine", "comfort", "command",
  "comment", "compact", "company", "compare", "compete", "complex", "concept", "concern", "confirm",
  "connect", "consist", "contact", "contain", "content", "contest", "context", "control", "convert",
  "cottage", "council", "counter", "country", "courage", "crystal", "curious", "current", "cushion",
  "declare", "default", "deliver", "deposit", "descend", "deserve", "despite", "destroy", "develop",
  "diamond", "digital", "dismiss", "display", "distant", "diverse", "dolphin", "drawing", "dynamic",
  "eastern", "economy", "edition", "element", "embrace", "emotion", "enhance", "example", "explain",
  "explore", "express", "extreme", "factory", "fantasy", "fashion", "feature", "federal", "finance",
  "fitness", "foreign", "fortune", "forward", "freedom", "gallery", "general", "genuine", "gesture",
  "grocery", "harmony", "harvest", "healthy", "hearing", "history", "holiday", "horizon", "however",
  "imagine", "improve", "include", "inspire", "install", "instant", "invest", "journal", "journey",
  "justice", "kingdom", "kitchen", "landing", "lantern", "leading", "leather", "lecture", "library",
  "machine", "manager", "measure", "medical", "meeting", "mention", "message", "million", "mineral",
  "minimum", "mission", "mixture", "monster", "morning", "musical", "mystery", "natural", "network",
  "neutral", "nothing", "nuclear", "observe", "obvious", "operate", "opinion", "organic", "outcome",
  "outdoor", "outlook", "package", "pancake", "partner", "passage", "pattern", "payment", "penalty",
  "perfect", "perform", "picture", "pioneer", "pointer", "popular", "portion", "poverty", "precise",
  "predict", "prepare", "present", "prevent", "primary", "printer", "privacy", "problem", "process",
  "produce", "product", "profile", "program", "project", "promise", "protect", "protein", "provide",
  "publish", "purpose", "pyramid", "quality", "quarter", "radical", "rainbow", "reality", "receive",
  "recover", "reflect", "regular", "reserve", "resolve", "respect", "respond", "restore", "reunion",
  "reverse", "routine", "satisfy", "science", "section", "segment", "service", "session", "setting",
  "several", "shelter", "silence", "similar", "society", "special", "station", "stomach", "storage",
  "strange", "student", "subject", "success", "suggest", "summary", "support", "suppose", "supreme",
  "surface", "surgery", "survive", "suspect", "sustain", "teacher", "theater", "theory", "thought",
  "through", "tonight", "tourist", "traffic", "trouble", "typical", "uniform", "unusual", "upgrade",
  "utility", "vaccine", "variety", "vehicle", "venture", "version", "veteran", "victory", "village",
  "vintage", "virtual", "visible", "visitor", "voltage", "warning", "warrior", "weather", "webpage",
  "wedding", "weekend", "welcome", "western", "whisper", "willing", "wisdom", "witness", "workout",
];
