"use client";

import { useMemo, useState } from "react";
import { Button, CopyButton, Input, Select } from "@/components/ui";
import { CodeOutputPanel, ControlSection, ResultPanel, ToolControlPanel, WarningPanel } from "@/features/tools/components";
import { ToolLayoutTextWorkbench } from "@/features/tools/layouts";
import { downloadText } from "../_shared/clientUtils";
import { generateMetaTags, getPreviewModel, validateMetaTagInput } from "./meta";
import { DEFAULT_META_INPUT, EMPTY_META_INPUT, META_PRESETS, OG_TYPE_OPTIONS, TWITTER_CARD_OPTIONS } from "./presets";
import type { MetaTagInput, MetaTagSection, OgType, TwitterCardType } from "./types";

export default function MetaTagClient() {
  const [input, setInput] = useState<MetaTagInput>(DEFAULT_META_INPUT);
  const [section, setSection] = useState<MetaTagSection>("all");
  const code = useMemo(() => generateMetaTags(input, section), [input, section]);
  const preview = useMemo(() => getPreviewModel(input), [input]);
  const warnings = useMemo(() => validateMetaTagInput(input), [input]);
  function patch(next: Partial<MetaTagInput>) { setInput((current) => ({ ...current, ...next })); }
  return <ToolLayoutTextWorkbench
    inputSlot={<ToolControlPanel title="Meta tag fields"><ControlSection title="Basic SEO"><div className="space-y-3"><label className="text-xs font-semibold text-[var(--color-text-muted)]">Title<Input className="mt-1" value={input.title} onChange={(e) => patch({ title: e.target.value })} /></label><label className="text-xs font-semibold text-[var(--color-text-muted)]">Description<Input className="mt-1" value={input.description} onChange={(e) => patch({ description: e.target.value })} /></label><label className="text-xs font-semibold text-[var(--color-text-muted)]">Canonical URL<Input className="mt-1" value={input.canonicalUrl} onChange={(e) => patch({ canonicalUrl: e.target.value })} /></label></div></ControlSection><ControlSection title="Open Graph and social"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-[var(--color-text-muted)]">Site name<Input className="mt-1" value={input.siteName} onChange={(e) => patch({ siteName: e.target.value })} /></label><label className="text-xs font-semibold text-[var(--color-text-muted)]">OG type<Select size="sm" className="mt-1" value={input.ogType} onChange={(e) => patch({ ogType: e.target.value as OgType })}>{OG_TYPE_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</Select></label><label className="text-xs font-semibold text-[var(--color-text-muted)]">Image URL<Input className="mt-1" value={input.imageUrl} onChange={(e) => patch({ imageUrl: e.target.value })} /></label><label className="text-xs font-semibold text-[var(--color-text-muted)]">Twitter card<Select size="sm" className="mt-1" value={input.twitterCard} onChange={(e) => patch({ twitterCard: e.target.value as TwitterCardType })}>{TWITTER_CARD_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</Select></label></div></ControlSection><ControlSection title="Presets"><div className="flex flex-wrap gap-2">{META_PRESETS.map((preset) => <Button key={preset.label} size="sm" variant="secondary" onClick={() => setInput(preset.input)}>{preset.label}</Button>)}<Button size="sm" variant="ghost" onClick={() => setInput(EMPTY_META_INPUT)}>Clear</Button></div></ControlSection></ToolControlPanel>}
    outputSlot={<CodeOutputPanel title="Generated meta tags" tabs={[{ id: "all", label: "All", code: generateMetaTags(input, "all"), language: "html" }, { id: "seo", label: "SEO", code: generateMetaTags(input, "seo"), language: "html" }, { id: "og", label: "Open Graph", code: generateMetaTags(input, "openGraph"), language: "html" }, { id: "twitter", label: "Twitter/X", code: generateMetaTags(input, "twitter"), language: "html" }]} defaultTab={section === "openGraph" ? "og" : section} onDownload={(tab) => downloadText("meta-tags.html", tab.code, "text/html;charset=utf-8")} />}
    actionsSlot={<><Select size="sm" width="medium" value={section} onChange={(e) => setSection(e.target.value as MetaTagSection)} aria-label="Meta section"><option value="all">All tags</option><option value="seo">SEO</option><option value="openGraph">Open Graph</option><option value="twitter">Twitter/X</option></Select><CopyButton text={code} size="sm">Copy selected</CopyButton></>}
    statsSlot={<><ResultPanel title="Social preview" value={<div className="text-left"><p className="text-sm font-bold">{preview.title || "Untitled page"}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{preview.description || "Description preview"}</p><p className="mt-2 text-[11px] uppercase tracking-wide text-[var(--color-text-soft)]">{preview.domain || preview.siteName}</p></div>} /><WarningPanel messages={warnings.length ? warnings.map((w, i) => ({ id: `${w.field}-${i}`, severity: w.level === "error" ? "danger" : w.level, title: String(w.field), message: w.message })) : [{ id: "ok", severity: "success", title: "Looks ready", message: "Review final tags in production and check social previews after deployment." }]} /></>}
  />;
}
