import type { GameDefinition } from "../domain/game";

const PRIVACY_NOTE =
  "This game runs in your browser. No signup is required. If progress is saved in the future, it should use local storage only.";

const GAME_DEFINITIONS: GameDefinition[] = [
  {
    id: "2048",
    slug: "2048",
    title: "2048 Classic",
    description: "Slide and merge numbered tiles to reach 2048 in the original browser game.",
    longDescription:
      "2048 is a single-player sliding puzzle. Combine matching number tiles to grow them, keep the board tidy, and chase the elusive 2048 tile. This Darma integration embeds the original browser game locally, preserving keyboard controls, swipe input, score tracking, and the classic visual style.",
    href: "/games/2048",
    categories: ["puzzle", "brain", "classic"],
    tags: ["numbers", "merge", "sliding", "strategy"],
    thumbnail: "🔢",
    thumbnailType: "gradient",
    accent: "amber",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Use arrow keys or swipe to slide all tiles. Matching tiles merge into one.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play 2048 Classic Online Free | Darma Games",
    seoDescription:
      "Play 2048 in your browser for free. Slide and merge numbered tiles to reach 2048. No signup, no downloads — just a quick numbers puzzle.",
    pinned: 1,
    createdAt: "2026-05-10",
  },
  {
    id: "snake",
    slug: "snake",
    title: "Snake Pro",
    description: "Arcade snake upgraded with modes, speed control, golden food, local records, keyboard, and swipe play.",
    longDescription:
      "Snake Pro keeps the familiar eat-and-grow loop but upgrades it into a polished browser arcade game: classic walls, portal wrap, maze mode, chill-to-insane speed settings, golden bonus food, local high scores, touch swipes, keyboard controls, and a professional game-over flow.",
    href: "/games/snake",
    categories: ["arcade", "classic", "quick-break"],
    tags: ["retro", "snake", "reflex", "score", "pro"],
    thumbnail: "🐍",
    thumbnailType: "gradient",
    accent: "emerald",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "5–10 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Use arrows or WASD, swipe on mobile, or tap the on-screen controls. Choose Classic, Wrap, or Maze mode and chase high scores.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Snake Pro Online Free | Darma Games",
    seoDescription:
      "Play Snake Pro free in your browser with classic, wrap, and maze modes, golden food, local high scores, keyboard controls, and mobile swipes. No signup.",
    pinned: 2,
    createdAt: "2026-05-08",
  },
  {
    id: "tic-tac-toe",
    slug: "tic-tac-toe",
    title: "Tic Tac Toe Pro",
    description: "A polished XO strategy board with AI, 4×4 mode, threat highlights, local stats, and board sharing.",
    longDescription:
      "Tic Tac Toe Pro turns the simple XO board into a more useful strategy game: play local 2-player or against an AI opponent, choose casual, smart, or unbeatable 3×3 difficulty, switch to a 4×4 pro board, see tactical threat highlights, track local stats, and copy the board state.",
    href: "/games/tic-tac-toe",
    categories: ["classic", "casual", "2-players", "quick-break", "brain"],
    tags: ["xo", "grid", "two player", "casual", "ai", "strategy"],
    thumbnail: "⭕",
    thumbnailType: "gradient",
    accent: "rose",
    popular: true,
    difficulty: "medium",
    playTime: "1–5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap or click an empty cell. Play local two-player or against the AI; threat highlights help you block and build lines.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Tic Tac Toe Pro Online Free | Darma Games",
    seoDescription:
      "Play Tic Tac Toe Pro free in your browser with AI, 4x4 mode, threat highlights, local stats, and quick board sharing. No signup needed.",
    createdAt: "2026-04-28",
  },
  {
    id: "memory-cards",
    slug: "memory-cards",
    title: "Memory Cards Pro",
    description: "A polished concentration game with preview, streaks, hints, scalable boards, and local best scores.",
    longDescription:
      "Memory Cards Pro upgrades the classic matching game into a focused training board. Choose card count and theme, preview the layout, use limited hints, protect your streak, track moves and time, and store best scores locally without signup.",
    href: "/games/memory-cards",
    categories: ["casual", "brain", "quick-break", "mobile-friendly"],
    tags: ["memory", "matching", "concentration", "pairs", "focus", "streaks"],
    thumbnail: "🃏",
    thumbnailType: "gradient",
    accent: "violet",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Preview the board, then click or tap cards to flip them. Match pairs, use hints carefully, and clear the board in fewer moves.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Memory Cards Pro Online Free | Darma Games",
    seoDescription:
      "Play Memory Cards Pro free in your browser with preview mode, hints, streaks, difficulty levels, themes, and local best scores. No signup needed.",
    createdAt: "2026-05-02",
  },
  {
    id: "word-match",
    slug: "word-match",
    title: "Word Match Pro",
    description: "A polished vocabulary matcher with synonyms, opposites, categories, Arabic mode, hints, streaks, and scoring.",
    longDescription:
      "Word Match Pro turns a simple matching idea into a useful language puzzle. Choose synonyms, opposites, categories, English-Arabic, or mixed rounds; tap-to-match cards on mobile or desktop; build streak bonuses; use hints carefully; review missed pairs; and save best scores locally.",
    href: "/games/word-match",
    categories: ["brain", "casual", "puzzle", "mobile-friendly"],
    tags: ["words", "vocabulary", "matching", "language", "english", "arabic", "streaks"],
    thumbnail: "🔤",
    thumbnailType: "gradient",
    accent: "cyan",
    featured: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap a word, then tap its matching card. Correct pairs build streaks, wrong attempts appear in mistake review, and hints reveal learning clues.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Word Match Pro Online Free | Darma Games",
    seoDescription:
      "Play Word Match Pro free in your browser with synonyms, opposites, categories, English-Arabic pairs, hints, streaks, scoring, and local best scores. No signup.",
    createdAt: "2026-04-20",
  },
  {
    id: "sudoku-mini",
    slug: "sudoku-mini",
    title: "Sudoku Mini",
    description: "A polished 4×4 and 6×6 Sudoku with notes, hints, timer, undo, and best times.",
    longDescription:
      "Sudoku Mini is a fast professional logic game with 4×4 beginner and 6×6 mini boards, generated puzzles with unique solutions, notes mode, hints, undo/redo, keyboard controls, mistake-limit and zen modes, local autosave, and a satisfying win screen.",
    href: "/games/sudoku-mini",
    categories: ["puzzle", "brain"],
    tags: ["sudoku", "numbers", "logic", "grid", "notes", "keyboard"],
    thumbnail: "🧮",
    thumbnailType: "gradient",
    accent: "indigo",
    featured: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Select a cell, then type or tap a number. Use notes, hints, undo/redo, keyboard arrows, and erase to solve each row, column, and box.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Sudoku Mini Online Free | Darma Games",
    seoDescription:
      "Play Sudoku Mini free in your browser. Solve 4×4 and 6×6 Sudoku puzzles with notes, hints, timer, keyboard controls, autosave, and best times. No signup required.",
    createdAt: "2026-04-15",
  },
  {
    id: "color-switch",
    slug: "color-switch",
    title: "Color Orbit Switch",
    description: "Tap through matching color gates, collect stars, switch colors, and clear levels.",
    longDescription:
      "Color Orbit Switch is an original Darma arcade build inspired by color-matching one-tap games. Jump through obstacle segments that match your orb color, collect stars, trigger color switches, build streak multipliers, clear 10 handcrafted levels, or chase an endless high score. It includes canvas gameplay, sounds, success/fail trails, pause, win, and game over flows.",
    href: "/games/color-switch",
    categories: ["arcade", "quick-break", "mobile-friendly"],
    tags: ["reflex", "color", "tap", "levels", "endless", "canvas", "mobile"],
    thumbnail: "🎨",
    thumbnailType: "gradient",
    accent: "fuchsia",
    featured: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["touch", "mouse", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap, click, press Space, Arrow Up, or W to jump. Pass only through segments matching your orb color. P or Esc pauses.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Color Orbit Switch — Free Color Matching Arcade Game | Darma Games",
    seoDescription:
      "Play Color Orbit Switch free in your browser. Tap through matching color gates, collect stars, clear levels, and chase an endless high score. No signup.",
    createdAt: "2026-06-12",
  },
  {
    id: "color-brain-rush",
    slug: "color-brain-rush",
    title: "Color Brain Rush",
    description: "Choose the visible text color, not the word you read — a focus game for English colors.",
    longDescription:
      "Color Brain Rush is a polished Stroop-style color reaction game for all ages. Kids Learning mode teaches English color names with friendly feedback, while Classic Challenge adds timers, streaks, multipliers, penalties, win thresholds, and detailed results. Beginner uses 3 basic colors, Intermediate uses 5 common colors, and Advanced uses 8 known colors.",
    href: "/games/color-brain-rush",
    categories: ["brain", "casual", "quick-break", "mobile-friendly"],
    tags: ["colors", "english", "kids", "learning", "reaction", "stroop", "focus", "education"],
    thumbnail: "🌈",
    thumbnailType: "gradient",
    accent: "cyan",
    featured: true,
    isNew: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["touch", "mouse", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Look at the visible text color, ignore the word meaning, then tap the matching color button. Number keys 1–8 also work during gameplay.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Color Brain Rush — English Color Learning Reaction Game | Darma Games",
    seoDescription:
      "Play Color Brain Rush free in your browser. A kids-friendly English colors game and Stroop reaction challenge with levels, scoring, sounds, win, and game over screens.",
    createdAt: "2026-06-30",
  },
  {
    id: "reaction-timer",
    slug: "reaction-timer",
    title: "Reaction Timer Pro",
    description: "Play classic reaction, precision timing, target hunting, levels, daily goals, and local battles.",
    longDescription:
      "A local reflex-training suite with classic reaction rounds, Precision Timer, Target Hunter, Level Challenge, Daily Challenge, Local Battle, achievements, educational insights, and browser-only progress. Results are useful for practice and personal comparison, not medical measurement.",
    href: "/games/reaction-timer",
    categories: ["arcade", "quick-break", "casual"],
    tags: ["reflex", "speed", "reaction", "timing", "reaction time test", "reaction timer", "browser reaction game", "no signup"],
    thumbnail: "⚡",
    thumbnailType: "gradient",
    accent: "lime",
    isNew: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Choose a mode, follow the on-screen objective, then click, tap, press Space, or press Enter where supported. Pointer/touch is recommended for target-heavy modes.",
    privacyNote: `${PRIVACY_NOTE} Reaction Timer Pro stores progress locally and is not a medical or diagnostic test.`,
    seoTitle: "Reaction Timer Pro — Free Browser Reaction Time Test | Darma Games",
    seoDescription:
      "Play Reaction Timer Pro free in your browser: classic reaction time test, precision timer, target hunter, level challenge, daily local goals, achievements, and no signup.",
    createdAt: "2026-06-18",
  },
  {
    id: "tetris",
    slug: "tetris",
    title: "Tetris",
    description: "Play a clean classic Tetris block puzzle game inside Darma Games.",
    longDescription:
      "The timeless block puzzle. Rotate and drop the seven tetrominoes to complete full rows and clear them before the stack reaches the top. The board speeds up every ten lines — keep a tidy stack, plan your next pieces, and chase a new high score. Keyboard and on-screen touch controls, instant restart, and a local high score.",
    href: "/games/tetris",
    categories: ["puzzle", "classic", "brain"],
    tags: ["tetris", "puzzle", "blocks", "keyboard", "classic"],
    thumbnail: "🟪",
    thumbnailType: "gradient",
    accent: "violet",
    featured: true,
    isNew: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["keyboard", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Arrow Left/Right to move, Arrow Up to rotate, Arrow Down to soft drop, Space to hard drop, P to pause, Q or Esc to quit. On touch devices, use the on-screen buttons below the board.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Tetris Game | Darma Games",
    seoDescription:
      "Play a polished classic Tetris block puzzle game with keyboard and mobile controls. Free in your browser, no signup.",
    createdAt: "2026-06-28",
  },

  {
    id: "hextris",
    slug: "hextris",
    title: "Hextris",
    description: "Rotate the hexagon, catch falling color blocks, and clear matching lines.",
    longDescription:
      "Hextris is a fast arcade puzzle inspired by falling-block classics. Blocks fall toward a central hexagon from six directions. Rotate the hexagon, stack matching colors, trigger combos, and survive as the speed climbs. This Darma integration keeps the original Hextris game logic and local assets inside the Darma Games player shell.",
    href: "/games/hextris",
    categories: ["arcade", "puzzle", "classic", "quick-break"],
    tags: ["hextris", "arcade", "puzzle", "blocks", "colors", "falling blocks", "keyboard", "mobile"],
    thumbnail: "⬢",
    thumbnailType: "gradient",
    accent: "orange",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Use Left/Right arrows or A/D to rotate the hexagon. On touch devices, tap or swipe inside the game area. Match same-colored blocks to clear stacks and build combos before the hexagon fills up.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Hextris Online Free | Darma Games",
    seoDescription:
      "Play Hextris free inside Darma Games. Rotate the hexagon, match colors, clear falling blocks, and chase high scores in your browser with no signup.",
    createdAt: "2026-06-30",
  },
  {
    id: "minesweeper",
    slug: "minesweeper",
    title: "Minesweeper",
    description: "Clear a polished minefield with safe first-click logic, flags, score, sounds, and result screens.",
    longDescription:
      "Minesweeper is a production-ready Darma puzzle build converted from a tiny vanilla JavaScript game into a responsive React player. Choose Easy, Classic, or Expert, reveal safe squares, flag suspected mines, chase a clear score, save local bests, and finish with dedicated win or game over screens. It includes first-click protection, touch-friendly flag mode, long-press flagging, synthesized sound effects, and an instruction panel.",
    href: "/games/minesweeper",
    categories: ["puzzle", "classic", "brain", "mobile-friendly"],
    tags: ["mines", "logic", "grid", "strategy", "score", "flags", "touch"],
    thumbnail: "💣",
    thumbnailType: "gradient",
    accent: "blue",
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Click or tap to reveal a square. Right-click, long-press, or enable Flag mode to mark suspected mines. Numbers show how many mines touch each revealed square. The first reveal is always safe.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Minesweeper Online Free | Darma Games",
    seoDescription:
      "Play a polished Minesweeper game free in your browser. Safe first click, score, flags, sounds, mobile controls, win and game over screens. No signup.",
    createdAt: "2026-06-30",
  },
  {
    id: "connect-four",
    slug: "connect-four",
    title: "Connect Four Pro",
    description: "Drop discs, read threats, use hints, and play local or against a smarter AI opponent.",
    longDescription:
      "Connect Four Pro turns the classic grid into a stronger strategy experience. Play local two-player or vs computer, choose AI difficulty, get tactical hinting, see winning and blocking columns, undo moves, track local stats, and win by connecting four horizontally, vertically, or diagonally.",
    href: "/games/connect-four",
    categories: ["classic", "2-players", "brain", "mobile-friendly"],
    tags: ["strategy", "two player", "grid", "connect", "ai", "tactics"],
    thumbnail: "🔴",
    thumbnailType: "gradient",
    accent: "orange",
    popular: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Click, tap, or press 1–7 to drop your disc. Green columns can win now; amber columns warn about threats you should block.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Connect Four Pro Online Free | Darma Games",
    seoDescription:
      "Play Connect Four Pro free in your browser with AI difficulty, hints, threat highlights, undo, local stats, and mobile controls. No signup required.",
    createdAt: "2026-04-22",
  },
  {
    id: "chess-mini",
    slug: "chess-mini",
    title: "Chess Mini",
    description: "A polished player-vs-computer chess game with standard rules, AI difficulty, timers, and promotion choice.",
    longDescription:
      "Chess Mini is a production-ready player-vs-computer chess experience built for Darma Games. Choose White or Black, play against a computer opponent with beginner/intermediate/pro difficulty, and use legal move highlighting, check/checkmate/stalemate detection, castling, en passant, promotion choice, undo, board flip, draw/resign actions, optional clocks, captured pieces, board themes, sound, and move notation.",
    href: "/games/chess-mini",
    categories: ["classic", "brain", "quick-break"],
    tags: ["chess", "strategy", "board", "computer opponent", "single player", "classic game"],
    thumbnail: "♟️",
    thumbnailType: "gradient",
    accent: "teal",
    difficulty: "hard",
    playTime: "15 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Choose your side and difficulty, then click or tap one of your pieces and choose a highlighted legal square. The computer replies automatically. Supports castling, en passant, promotion choice, undo, board flip, draw, resign, optional clocks, board themes, sound, and coordinate toggle. Keyboard users can tab to the board and use arrow keys between squares.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Chess Mini Online Free | Darma Games",
    seoDescription:
      "Play Chess Mini free in your browser. A polished chess game against a computer opponent with difficulty levels, legal move highlights, timers, promotion, castling, en passant, and no signup.",
    createdAt: "2026-04-05",
  },
  {
    id: "floppy-bird",
    slug: "floppy-bird",
    title: "Floppy Bird",
    description: "A retro one-tap arcade flyer with real sprite and sound assets.",
    longDescription:
      "Floppy Bird is a focused arcade flyer built for Darma Games. Tap, click, or press Space to flap through pipe gaps, score points, beat your saved best, and earn medals at 10, 20, 30, and 40 points. The playable uses a crisp 288 × 512 retro canvas frame with local sprite and sound assets, so it feels like a real arcade game instead of a dashboard.",
    href: "/games/floppy-bird",
    categories: ["arcade", "quick-break", "mobile-friendly", "casual"],
    tags: ["arcade", "floppy", "bird", "flyer", "one-tap", "reflex", "endless"],
    thumbnail: "🐤",
    thumbnailType: "gradient",
    accent: "sky",
    isNew: true,
    popular: true,
    difficulty: "easy",
    playTime: "1 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Tap, click, or press Space / Up to flap through the pipe gaps. P pauses, Enter starts or restarts. Each cleared pipe scores a point; earn bronze, silver, gold, and platinum medals at 10, 20, 30, and 40 points.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Floppy Bird Online Free | Darma Games",
    seoDescription:
      "Play Floppy Bird free in your browser. A retro one-tap arcade flyer with crisp sprites, real sound effects, saved best score, and mobile-friendly controls. No signup required.",
    createdAt: "2026-06-30",
  },
  {
    id: "math-sprint",
    slug: "math-sprint",
    title: "Math Sprint",
    description: "Fast arithmetic practice — answer as many as you can.",
    longDescription:
      "Math Sprint is a quick mental-maths workout for kids, students, and adults. Choose your operations — addition, subtraction, multiplication, division, and decimals — then drill them in Practice, a 60-second Sprint, or a calmer Kids mode with bigger buttons. Get instant feedback, build streaks, track your average answer time, and beat your best score. An on-screen keypad keeps it smooth on mobile.",
    href: "/games/math-sprint",
    categories: ["brain", "quick-break", "casual", "mobile-friendly"],
    tags: ["math", "arithmetic", "mental maths", "education", "kids", "practice", "numbers"],
    thumbnail: "➗",
    thumbnailType: "gradient",
    accent: "violet",
    isNew: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Type your answer and press Enter, or use the on-screen keypad. Choose operations and a mode (Practice, 60-second Sprint, or Kids) on the setup screen. Decimals accept a dot or comma. Best score and streak are saved on your device.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Math Sprint Online Free | Darma Games",
    seoDescription:
      "Play Math Sprint free in your browser. Fast arithmetic practice with addition, subtraction, multiplication, division, and decimals — Practice, 60-second Sprint, and Kids modes. No signup, mobile-friendly.",
    createdAt: "2026-06-30",
  },
  {
    id: "pacman-canvas",
    slug: "pacman-canvas",
    title: "Pacman Canvas",
    description: "A polished Darma integration of the classic Pacman canvas game with original local assets, sounds, and mobile controls.",
    longDescription:
      "Pacman Canvas preserves the original mini Pacman maze, ghost SVG assets, pills, power pills, arcade sound files, scoring, lives, and level progression, then wraps it in a production Darma player with responsive canvas scaling, keyboard, swipe, D-pad controls, pause, restart, mute, focus mode, local best score, and clear win/game-over overlays.",
    href: "/games/pacman-canvas",
    categories: ["arcade", "classic", "quick-break", "mobile-friendly"],
    tags: ["pacman", "canvas", "arcade", "retro", "ghosts", "maze", "keyboard", "mobile"],
    thumbnail: "🟡",
    thumbnailType: "gradient",
    accent: "amber",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Use Arrow keys or WASD to move Pacman. On mobile, swipe on the canvas or use the D-pad. Space/Enter starts the game, P or Esc pauses. Eat power pills to catch vulnerable ghosts.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Pacman Canvas Online Free | Darma Games",
    seoDescription:
      "Play Pacman Canvas free in your browser with local retro assets, ghosts, power pills, score, lives, keyboard controls, mobile swipes, and no signup.",
    createdAt: "2026-07-01",
  },

  {
    id: "endless-runner",
    slug: "endless-runner",
    title: "Endless Runner",
    description: "A polished canvas runner with the original parallax backgrounds, an animated sprite character, fair speed-aware obstacles, and mobile controls.",
    longDescription:
      "Endless Runner keeps the original project’s two parallax background images, then upgrades the demo into a Darma-ready canvas arcade game. The player is a real animated sprite (idle, run, jump, fall, slide, hurt), obstacles are pooled and fairly spaced based on current speed and reaction time, and the game stays responsive for long sessions. Rocks, spikes, crates, and logs require a jump; a flying bird and a hanging branch require a slide. Includes lives with a brief shield after each hit, score, local best score, start/pause/restart, responsive sizing, keyboard controls, and tap-to-jump mobile play.",
    href: "/games/endless-runner",
    categories: ["arcade", "quick-break", "mobile-friendly", "casual"],
    tags: ["runner", "endless", "canvas", "jump", "parallax", "obstacles", "mobile", "score"],
    thumbnail: "🏃",
    thumbnailType: "gradient",
    accent: "orange",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Press Space, Arrow Up, W, or tap the canvas to jump. Press Arrow Down or S, or the Slide button, to slide under head-height obstacles. Use P or Esc to pause. On mobile, tap the canvas or the Jump/Slide buttons to play.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Endless Runner Online Free | Darma Games",
    seoDescription:
      "Play Endless Runner free in your browser. Jump over obstacles, slide under birds and branches, collect coins, enjoy parallax canvas backgrounds, mobile controls, and local best score. No signup required.",
    createdAt: "2026-07-01",
  },

  {
    id: "typing-speed",
    slug: "typing-speed",
    title: "Typing Speed Pro",
    description: "A professional typing trainer with WPM, raw WPM, accuracy, mistake patterns, history, and multiple modes.",
    longDescription:
      "Typing Speed Pro upgrades the basic WPM test into a browser-only typing trainer. Choose quick tests, practice, accuracy mode, or challenge text; track corrected WPM, raw WPM, accuracy, mistakes, repeated missed characters, best scores, and local history; then copy your result after each round.",
    href: "/games/typing-speed",
    categories: ["arcade", "brain", "quick-break"],
    tags: ["typing", "wpm", "speed", "keyboard", "accuracy", "trainer", "history"],
    thumbnail: "⌨️",
    thumbnailType: "gradient",
    accent: "sky",
    isNew: true,
    featured: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard"],
    devices: ["desktop", "tablet"],
    controls: "Choose a mode, then start typing. The timer begins on the first character; paste is disabled; results show WPM, raw WPM, accuracy, mistakes, and local history.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Typing Speed Pro Online Free | Darma Games",
    seoDescription:
      "Test and improve typing speed free in your browser with WPM, raw WPM, accuracy, mistake patterns, modes, local history, and copyable results. No signup.",
    createdAt: "2026-06-20",
  },
];

let publicGames: GameDefinition[] | null = null;
let gamesBySlug: Map<string, GameDefinition> | null = null;

export function getGames(): GameDefinition[] {
  if (!publicGames) {
    publicGames = GAME_DEFINITIONS.filter((game) => (game.visibility ?? "public") === "public");
  }
  return publicGames;
}

export function getGameBySlug(slug: string): GameDefinition | null {
  if (!gamesBySlug) {
    gamesBySlug = new Map(GAME_DEFINITIONS.map((game) => [game.slug, game]));
  }
  return gamesBySlug.get(slug) ?? null;
}

export function getGameSlugs(): string[] {
  return getGames().map((game) => game.slug);
}
