import type { GameDefinition } from "../domain/game";

const NO_SAVE_NOTE =
  "This game runs entirely in your browser. No signup is required, and Darma does not send gameplay data to a backend.";
const LOCAL_SCORE_NOTE =
  "This game runs entirely in your browser. No signup is required. High scores and lightweight preferences are saved only in local storage on this device.";
const LOCAL_STATS_NOTE =
  "This game runs entirely in your browser. No signup is required. Results, records, and preferences are saved only in local storage on this device.";
const LOCAL_PROGRESS_NOTE =
  "This game runs entirely in your browser. No signup is required. Progress, records, and settings are saved only in local storage on this device.";

const GAME_DEFINITIONS: GameDefinition[] = [
  {
    id: "gridland",
    slug: "gridland",
    title: "Gridland",
    description: "Match resources by day, build your settlement, and survive the creatures that emerge at night.",
    longDescription:
      "Gridland is the original match-and-build survival game preserved inside Darma. Daytime matches gather resources and grow your settlement; nighttime matches become weapons, shields, and monsters. This integration keeps the original visual language, game flow, CSS animations, local saves, music, and sound effects while self-hosting the runtime and assets in an isolated browser frame.",
    href: "/games/gridland",
    categories: ["puzzle", "brain", "classic", "mobile-friendly"],
    tags: ["match-3", "strategy", "survival", "building", "resources", "day and night", "original"],
    thumbnail: "/darma-games/gridland/img/badge.png",
    thumbnailType: "image",
    accent: "amber",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "hard",
    playTime: "15 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Swap adjacent tiles to make groups of three or more. Gather and build during the day; create weapons and shields at night. Use the in-game menu for sound, save export/import, and other options.",
    tips: [
      "Use daytime matches to prepare resources before night changes the board.",
      "Avoid spending every resource immediately; balanced building gives you more survival options.",
      "Export a save from the in-game menu before experimenting with a risky strategy.",
    ],
    privacyNote:
      "Gridland runs entirely in your browser with self-hosted assets. Progress and settings stay in namespaced local storage on this device; no signup is required.",
    seoTitle: "Play Gridland Online Free | Darma Games",
    seoDescription:
      "Play Gridland in your browser: match resources, build by day, and survive monsters at night. Original visuals, music, local saves, and no signup.",
    credits: {
      author: "Michael Townsend (Doublespeak Games)",
      authorUrl: "https://www.doublespeakgames.com",
      additional: [{ role: "Music", name: "Vince Nitro" }],
      license: "MPL 2.0",
      licenseUrl: "/darma-games/gridland/LICENSE",
      integrationNote:
        "Gridland was created by Doublespeak Games, not by Darma. Darma self-hosts the original runtime, artwork, and audio unchanged, and adds only the surrounding player shell, namespaced saves, and a read-only status bridge.",
    },
    pinned: 0,
    createdAt: "2026-07-16",
  },
  {
    id: "2048",
    slug: "2048",
    title: "2048 Classic",
    description: "Slide and merge numbered tiles to reach 2048 in the original browser game.",
    longDescription:
      "2048 is a single-player sliding puzzle. Combine matching number tiles to grow them, keep the board tidy, and chase the elusive 2048 tile. This Darma integration embeds the original browser game locally, preserving keyboard controls, swipe input, score tracking, and the classic visual style.",
    href: "/games/2048",
    categories: ["puzzle", "brain", "classic"],
    tags: ["numbers", "merge", "sliding", "strategy"],
    thumbnail: "🔢",
    thumbnailType: "gradient",
    accent: "amber",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Use arrow keys or swipe to slide all tiles. Matching tiles merge into one.",
    tips: [
      "Keep your highest-value tile anchored in one corner.",
      "Prefer moves that preserve an ordered row instead of filling every empty space.",
      "Pause before each swipe and check whether it creates a useful follow-up merge.",
    ],
    privacyNote: LOCAL_PROGRESS_NOTE,
    seoTitle: "Play 2048 Classic Online Free | Darma Games",
    seoDescription:
      "Play 2048 in your browser for free. Slide and merge numbered tiles to reach 2048. No signup, no downloads — just a quick numbers puzzle.",
    pinned: 1,
    createdAt: "2026-05-10",
  },
  {
    id: "snake",
    slug: "snake",
    title: "Snake Pro",
    description: "Arcade snake upgraded with modes, speed control, golden food, local records, keyboard, and swipe play.",
    longDescription:
      "Snake Pro keeps the familiar eat-and-grow loop but upgrades it into a polished browser arcade game: classic walls, portal wrap, maze mode, chill-to-insane speed settings, golden bonus food, local high scores, touch swipes, keyboard controls, and a professional game-over flow.",
    href: "/games/snake",
    categories: ["arcade", "classic", "quick-break"],
    tags: ["retro", "snake", "reflex", "score", "pro"],
    thumbnail: "🐍",
    thumbnailType: "gradient",
    accent: "emerald",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Use arrows or WASD, swipe on mobile, or tap the on-screen controls. Choose Classic, Wrap, or Maze mode and chase high scores.",
    tips: [
      "Leave yourself an escape route instead of circling food too tightly.",
      "Use slower speeds while learning maze or wrap behavior.",
      "Golden food is valuable, but skip it when the route would trap your tail.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Snake Pro Online Free | Darma Games",
    seoDescription:
      "Play Snake Pro free in your browser with classic, wrap, and maze modes, golden food, local high scores, keyboard controls, and mobile swipes. No signup.",
    pinned: 2,
    createdAt: "2026-05-08",
  },
  {
    id: "tic-tac-toe",
    slug: "tic-tac-toe",
    title: "Tic Tac Toe Pro",
    description: "A polished XO strategy board with AI, 4×4 mode, threat highlights, local stats, and board sharing.",
    longDescription:
      "Tic Tac Toe Pro turns the simple XO board into a more useful strategy game: play local 2-player or against an AI opponent, choose casual, smart, or unbeatable 3×3 difficulty, switch to a 4×4 pro board, see tactical threat highlights, track local stats, and copy the board state.",
    href: "/games/tic-tac-toe",
    categories: ["classic", "casual", "2-players", "quick-break", "brain"],
    tags: ["xo", "grid", "two player", "casual", "ai", "strategy"],
    thumbnail: "⭕",
    thumbnailType: "gradient",
    accent: "rose",
    popular: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap or click an empty cell. Play local two-player or against the AI; threat highlights help you block and build lines.",
    tips: [
      "Control the center when it is available.",
      "Look for moves that create two winning threats at once.",
      "In 4×4 mode, scan rows, columns, and diagonals before committing to an attack.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Tic Tac Toe Pro Online Free | Darma Games",
    seoDescription:
      "Play Tic Tac Toe Pro free in your browser with AI, 4x4 mode, threat highlights, local stats, and quick board sharing. No signup needed.",
    createdAt: "2026-04-28",
  },
  {
    id: "memory-cards",
    slug: "memory-cards",
    title: "Memory Cards Pro",
    description: "A polished concentration game with preview, streaks, hints, scalable boards, and local best scores.",
    longDescription:
      "Memory Cards Pro upgrades the classic matching game into a focused training board. Choose card count and theme, preview the layout, use limited hints, protect your streak, track moves and time, and store best scores locally without signup.",
    href: "/games/memory-cards",
    categories: ["casual", "brain", "quick-break", "mobile-friendly"],
    tags: ["memory", "matching", "concentration", "pairs", "focus", "streaks"],
    thumbnail: "🃏",
    thumbnailType: "gradient",
    accent: "violet",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Preview the board, then click or tap cards to flip them. Match pairs, use hints carefully, and clear the board in fewer moves.",
    tips: [
      "Use the preview to group card positions into small mental zones.",
      "Flip a known card first so the second choice can complete a pair.",
      "Save hints for larger boards or late-round uncertainty.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Memory Cards Pro Online Free | Darma Games",
    seoDescription:
      "Play Memory Cards Pro free in your browser with preview mode, hints, streaks, difficulty levels, themes, and local best scores. No signup needed.",
    createdAt: "2026-05-02",
  },
  {
    id: "word-match",
    slug: "word-match",
    title: "Word Match Pro",
    description: "A polished vocabulary matcher with synonyms, opposites, categories, Arabic mode, hints, streaks, and scoring.",
    longDescription:
      "Word Match Pro turns a simple matching idea into a useful language puzzle. Choose synonyms, opposites, categories, English-Arabic, or mixed rounds; tap-to-match cards on mobile or desktop; build streak bonuses; use hints carefully; review missed pairs; and save best scores locally.",
    href: "/games/word-match",
    categories: ["brain", "casual", "puzzle", "mobile-friendly"],
    tags: ["words", "vocabulary", "matching", "language", "english", "arabic", "streaks"],
    thumbnail: "🔤",
    thumbnailType: "gradient",
    accent: "cyan",
    featured: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap a word, then tap its matching card. Correct pairs build streaks, wrong attempts appear in mistake review, and hints reveal learning clues.",
    tips: [
      "Start with one category before switching to mixed rounds.",
      "Use hints only after comparing every visible pair.",
      "Review missed pairs after the round and replay the same mode to reinforce them.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Word Match Pro Online Free | Darma Games",
    seoDescription:
      "Play Word Match Pro free in your browser with synonyms, opposites, categories, English-Arabic pairs, hints, streaks, scoring, and local best scores. No signup.",
    createdAt: "2026-04-20",
  },
  {
    id: "sudoku-mini",
    slug: "sudoku-mini",
    title: "Sudoku Mini",
    description: "A polished 4×4 and 6×6 Sudoku with notes, hints, timer, undo, and best times.",
    longDescription:
      "Sudoku Mini is a fast professional logic game with 4×4 beginner and 6×6 mini boards, generated puzzles with unique solutions, notes mode, hints, undo/redo, keyboard controls, mistake-limit and zen modes, local autosave, and a satisfying win screen.",
    href: "/games/sudoku-mini",
    categories: ["puzzle", "brain"],
    tags: ["sudoku", "numbers", "logic", "grid", "notes", "keyboard"],
    thumbnail: "🧮",
    thumbnailType: "gradient",
    accent: "indigo",
    featured: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Select a cell, then type or tap a number. Use notes, hints, undo/redo, keyboard arrows, and erase to solve each row, column, and box.",
    tips: [
      "Fill cells with only one possible value before guessing.",
      "Use notes to track candidates instead of holding them in memory.",
      "Check each row, column, and box after every correction to avoid repeated mistakes.",
    ],
    privacyNote: LOCAL_PROGRESS_NOTE,
    seoTitle: "Play Sudoku Mini Online Free | Darma Games",
    seoDescription:
      "Play Sudoku Mini free in your browser. Solve 4×4 and 6×6 Sudoku puzzles with notes, hints, timer, keyboard controls, autosave, and best times. No signup required.",
    createdAt: "2026-04-15",
  },
  {
    id: "color-switch",
    slug: "color-switch",
    title: "Color Orbit Switch",
    description: "Tap through matching color gates, collect stars, switch colors, and clear levels.",
    longDescription:
      "Color Orbit Switch is an original Darma arcade build inspired by color-matching one-tap games. Jump through obstacle segments that match your orb color, collect stars, trigger color switches, build streak multipliers, clear 10 handcrafted levels, or chase an endless high score. It includes canvas gameplay, sounds, success/fail trails, pause, win, and game over flows.",
    href: "/games/color-switch",
    categories: ["arcade", "quick-break", "mobile-friendly"],
    tags: ["reflex", "color", "tap", "levels", "endless", "canvas", "mobile"],
    thumbnail: "🎨",
    thumbnailType: "gradient",
    accent: "fuchsia",
    featured: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["touch", "mouse", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap, click, press Space, Arrow Up, or W to jump. Pass only through segments matching your orb color. P or Esc pauses.",
    tips: [
      "Watch the next gate before jumping; the current obstacle is only half the decision.",
      "Use short controlled taps instead of rapid repeated input.",
      "Collect stars only when the route still matches your current orb color.",
    ],
    privacyNote: LOCAL_SCORE_NOTE,
    seoTitle: "Color Orbit Switch — Free Color Matching Arcade Game | Darma Games",
    seoDescription:
      "Play Color Orbit Switch free in your browser. Tap through matching color gates, collect stars, clear levels, and chase an endless high score. No signup.",
    createdAt: "2026-06-12",
  },
  {
    id: "color-brain-rush",
    slug: "color-brain-rush",
    title: "Color Brain Rush",
    description: "Choose the visible text color, not the word you read — a focus game for English colors.",
    longDescription:
      "Color Brain Rush is a polished Stroop-style color reaction game for all ages. Kids Learning mode teaches English color names with friendly feedback, while Classic Challenge adds timers, streaks, multipliers, penalties, win thresholds, and detailed results. Beginner uses 3 basic colors, Intermediate uses 5 common colors, and Advanced uses 8 known colors.",
    href: "/games/color-brain-rush",
    categories: ["brain", "casual", "quick-break", "mobile-friendly"],
    tags: ["colors", "english", "kids", "learning", "reaction", "stroop", "focus", "education"],
    thumbnail: "🌈",
    thumbnailType: "gradient",
    accent: "cyan",
    featured: true,
    isNew: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["touch", "mouse", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Look at the visible text color, ignore the word meaning, then tap the matching color button. Number keys 1–8 also work during gameplay.",
    tips: [
      "Say the visible color silently and ignore the written word.",
      "Begin with fewer colors, then increase difficulty after accuracy stabilizes.",
      "Prioritize correct answers first; speed improves naturally with repetition.",
    ],
    privacyNote: NO_SAVE_NOTE,
    seoTitle: "Color Brain Rush — English Color Learning Reaction Game | Darma Games",
    seoDescription:
      "Play Color Brain Rush free in your browser. A kids-friendly English colors game and Stroop reaction challenge with levels, scoring, sounds, win, and game over screens.",
    createdAt: "2026-06-30",
  },
  {
    id: "reaction-timer",
    slug: "reaction-timer",
    title: "Reaction Timer Pro",
    description: "Play classic reaction, precision timing, target hunting, levels, daily goals, and local battles.",
    longDescription:
      "A local reflex-training suite with classic reaction rounds, Precision Timer, Target Hunter, Level Challenge, Daily Challenge, Local Battle, achievements, educational insights, and browser-only progress. Results are useful for practice and personal comparison, not medical measurement.",
    href: "/games/reaction-timer",
    categories: ["arcade", "quick-break", "casual"],
    tags: ["reflex", "speed", "reaction", "timing", "reaction time test", "reaction timer", "browser reaction game", "no signup"],
    thumbnail: "⚡",
    thumbnailType: "gradient",
    accent: "lime",
    isNew: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Choose a mode, follow the on-screen objective, then click, tap, press Space, or press Enter where supported. Pointer/touch is recommended for target-heavy modes.",
    tips: [
      "Begin with Classic Reaction before opening the advanced modes.",
      "Keep your hand relaxed and focus near the center of the arena.",
      "Compare averages across several rounds instead of judging one unusually fast result.",
    ],
    privacyNote: `${LOCAL_PROGRESS_NOTE} Reaction Timer Pro is a practice game, not a medical or diagnostic test.`,
    seoTitle: "Reaction Timer Pro — Free Browser Reaction Time Test | Darma Games",
    seoDescription:
      "Play Reaction Timer Pro free in your browser: classic reaction time test, precision timer, target hunter, level challenge, daily local goals, achievements, and no signup.",
    createdAt: "2026-06-18",
  },
  {
    id: "tetris",
    slug: "tetris",
    title: "Tetris",
    description: "Play a clean classic Tetris block puzzle game inside Darma Games.",
    longDescription:
      "The timeless block puzzle. Rotate and drop the seven tetrominoes to complete full rows and clear them before the stack reaches the top. The board speeds up every ten lines — keep a tidy stack, plan your next pieces, and chase a new high score. Keyboard and on-screen touch controls, instant restart, and a local high score.",
    href: "/games/tetris",
    categories: ["puzzle", "classic", "brain"],
    tags: ["tetris", "puzzle", "blocks", "keyboard", "classic"],
    thumbnail: "🟪",
    thumbnailType: "gradient",
    accent: "violet",
    featured: true,
    isNew: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["keyboard", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Arrow Left/Right to move, Arrow Up to rotate, Arrow Down to soft drop, Space to hard drop, P to pause, Q or Esc to quit. On touch devices, use the on-screen buttons below the board.",
    tips: [
      "Keep the stack low and avoid creating covered holes.",
      "Use the next-piece preview to prepare a landing area early.",
      "Save long vertical gaps for the straight piece only when the board remains stable.",
    ],
    privacyNote: LOCAL_SCORE_NOTE,
    seoTitle: "Tetris Game | Darma Games",
    seoDescription:
      "Play a polished classic Tetris block puzzle game with keyboard and mobile controls. Free in your browser, no signup.",
    createdAt: "2026-06-28",
  },

  {
    id: "hextris",
    slug: "hextris",
    title: "Hextris",
    description: "Rotate the hexagon, catch falling color blocks, and clear matching lines.",
    longDescription:
      "Hextris is a fast arcade puzzle inspired by falling-block classics. Blocks fall toward a central hexagon from six directions. Rotate the hexagon, stack matching colors, trigger combos, and survive as the speed climbs. This Darma integration keeps the original Hextris game logic and local assets inside the Darma Games player shell.",
    href: "/games/hextris",
    categories: ["arcade", "puzzle", "classic", "quick-break"],
    tags: ["hextris", "arcade", "puzzle", "blocks", "colors", "falling blocks", "keyboard", "mobile"],
    thumbnail: "⬢",
    thumbnailType: "gradient",
    accent: "orange",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Use Left/Right arrows or A/D to rotate the hexagon. On touch devices, tap or swipe inside the game area. Match same-colored blocks to clear stacks and build combos before the hexagon fills up.",
    tips: [
      "Rotate early so the target side is ready before the block reaches the center.",
      "Build short same-color groups instead of tall mixed stacks.",
      "Use chain clears to recover space when the speed increases.",
    ],
    privacyNote: LOCAL_SCORE_NOTE,
    seoTitle: "Play Hextris Online Free | Darma Games",
    seoDescription:
      "Play Hextris free inside Darma Games. Rotate the hexagon, match colors, clear falling blocks, and chase high scores in your browser with no signup.",
    createdAt: "2026-06-30",
  },
  {
    id: "minesweeper",
    slug: "minesweeper",
    title: "Minesweeper",
    description: "Clear a polished minefield with safe first-click logic, flags, score, sounds, and result screens.",
    longDescription:
      "Minesweeper is a production-ready Darma puzzle build converted from a tiny vanilla JavaScript game into a responsive React player. Choose Easy, Classic, or Expert, reveal safe squares, flag suspected mines, chase a clear score, save local bests, and finish with dedicated win or game over screens. It includes first-click protection, touch-friendly flag mode, long-press flagging, synthesized sound effects, and an instruction panel.",
    href: "/games/minesweeper",
    categories: ["puzzle", "classic", "brain", "mobile-friendly"],
    tags: ["mines", "logic", "grid", "strategy", "score", "flags", "touch"],
    thumbnail: "💣",
    thumbnailType: "gradient",
    accent: "blue",
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Click or tap to reveal a square. Right-click, long-press, or enable Flag mode to mark suspected mines. Numbers show how many mines touch each revealed square. The first reveal is always safe.",
    tips: [
      "Start from open areas and use revealed numbers as exact constraints.",
      "Flag only when every remaining covered neighbor must be a mine.",
      "When uncertain, compare overlapping number groups before making a guess.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Minesweeper Online Free | Darma Games",
    seoDescription:
      "Play a polished Minesweeper game free in your browser. Safe first click, score, flags, sounds, mobile controls, win and game over screens. No signup.",
    createdAt: "2026-06-30",
  },
  {
    id: "connect-four",
    slug: "connect-four",
    title: "Connect Four Pro",
    description: "Drop discs, read threats, use hints, and play local or against a smarter AI opponent.",
    longDescription:
      "Connect Four Pro turns the classic grid into a stronger strategy experience. Play local two-player or vs computer, choose AI difficulty, get tactical hinting, see winning and blocking columns, undo moves, track local stats, and win by connecting four horizontally, vertically, or diagonally.",
    href: "/games/connect-four",
    categories: ["classic", "2-players", "brain", "mobile-friendly"],
    tags: ["strategy", "two player", "grid", "connect", "ai", "tactics"],
    thumbnail: "🔴",
    thumbnailType: "gradient",
    accent: "orange",
    popular: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Click, tap, or press 1–7 to drop your disc. Green columns can win now; amber columns warn about threats you should block.",
    tips: [
      "Favor the center columns because they participate in more winning lines.",
      "Check the opponent’s immediate threat before extending your own sequence.",
      "Create two possible winning drops so one cannot be blocked.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Connect Four Pro Online Free | Darma Games",
    seoDescription:
      "Play Connect Four Pro free in your browser with AI difficulty, hints, threat highlights, undo, local stats, and mobile controls. No signup required.",
    createdAt: "2026-04-22",
  },
  {
    id: "chess-mini",
    slug: "chess-mini",
    title: "Chess Mini",
    description: "A polished player-vs-computer chess game with standard rules, AI difficulty, timers, and promotion choice.",
    longDescription:
      "Chess Mini is a production-ready player-vs-computer chess experience built for Darma Games. Choose White or Black, play against a computer opponent with beginner/intermediate/pro difficulty, and use legal move highlighting, check/checkmate/stalemate detection, castling, en passant, promotion choice, undo, board flip, draw/resign actions, optional clocks, captured pieces, board themes, sound, and move notation.",
    href: "/games/chess-mini",
    categories: ["classic", "brain", "quick-break"],
    tags: ["chess", "strategy", "board", "computer opponent", "single player", "classic game"],
    thumbnail: "♟️",
    thumbnailType: "gradient",
    accent: "teal",
    difficulty: "hard",
    playTime: "15 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Choose your side and difficulty, then click or tap one of your pieces and choose a highlighted legal square. The computer replies automatically. Supports castling, en passant, promotion choice, undo, board flip, draw, resign, optional clocks, board themes, sound, and coordinate toggle. Keyboard users can tab to the board and use arrow keys between squares.",
    tips: [
      "Develop pieces toward the center before launching an early attack.",
      "Check captures, checks, and threats for both sides before every move.",
      "When ahead, trade pieces carefully instead of opening unnecessary risks.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Chess Mini Online Free | Darma Games",
    seoDescription:
      "Play Chess Mini free in your browser. A polished chess game against a computer opponent with difficulty levels, legal move highlights, timers, promotion, castling, en passant, and no signup.",
    createdAt: "2026-04-05",
  },
  {
    id: "floppy-bird",
    slug: "floppy-bird",
    title: "Floppy Bird",
    description: "A retro one-tap arcade flyer with real sprite and sound assets.",
    longDescription:
      "Floppy Bird is a focused arcade flyer built for Darma Games. Tap, click, or press Space to flap through pipe gaps, score points, beat your saved best, and earn medals at 10, 20, 30, and 40 points. The playable uses a crisp 288 × 512 retro canvas frame with local sprite and sound assets, so it feels like a real arcade game instead of a dashboard.",
    href: "/games/floppy-bird",
    categories: ["arcade", "quick-break", "mobile-friendly", "casual"],
    tags: ["arcade", "floppy", "bird", "flyer", "one-tap", "reflex", "endless"],
    thumbnail: "🐤",
    thumbnailType: "gradient",
    accent: "sky",
    isNew: true,
    popular: true,
    difficulty: "easy",
    playTime: "1 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Tap, click, or press Space / Up to flap through the pipe gaps. P pauses, Enter starts or restarts. Each cleared pipe scores a point; earn bronze, silver, gold, and platinum medals at 10, 20, 30, and 40 points.",
    tips: [
      "Use small taps to control altitude instead of large corrections.",
      "Focus on the opening between pipes, not on the bird itself.",
      "Establish a steady rhythm before trying to chase the high score.",
    ],
    privacyNote: LOCAL_SCORE_NOTE,
    seoTitle: "Play Floppy Bird Online Free | Darma Games",
    seoDescription:
      "Play Floppy Bird free in your browser. A retro one-tap arcade flyer with crisp sprites, real sound effects, saved best score, and mobile-friendly controls. No signup required.",
    createdAt: "2026-06-30",
  },
  {
    id: "math-sprint",
    slug: "math-sprint",
    title: "Math Sprint",
    description: "Fast arithmetic practice — answer as many as you can.",
    longDescription:
      "Math Sprint is a quick mental-maths workout for kids, students, and adults. Choose your operations — addition, subtraction, multiplication, division, and decimals — then drill them in Practice, a 60-second Sprint, or a calmer Kids mode with bigger buttons. Get instant feedback, build streaks, track your average answer time, and beat your best score. An on-screen keypad keeps it smooth on mobile.",
    href: "/games/math-sprint",
    categories: ["brain", "quick-break", "casual", "mobile-friendly"],
    tags: ["math", "arithmetic", "mental maths", "education", "kids", "practice", "numbers"],
    thumbnail: "➗",
    thumbnailType: "gradient",
    accent: "violet",
    isNew: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Type your answer and press Enter, or use the on-screen keypad. Choose operations and a mode (Practice, 60-second Sprint, or Kids) on the setup screen. Decimals accept a dot or comma. Best score and streak are saved on your device.",
    tips: [
      "Choose only the operations you want to practice before starting a sprint.",
      "Type the answer as soon as you recognize it instead of rechecking simple facts.",
      "Review incorrect answers after the round and repeat the weakest operation.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Math Sprint Online Free | Darma Games",
    seoDescription:
      "Play Math Sprint free in your browser. Fast arithmetic practice with addition, subtraction, multiplication, division, and decimals — Practice, 60-second Sprint, and Kids modes. No signup, mobile-friendly.",
    createdAt: "2026-06-30",
  },
  {
    id: "neon-core-defense",
    slug: "neon-core-defense",
    title: "Neon Core Defense",
    description: "Defend a glowing core through escalating waves of drones.",
    longDescription:
      "Neon Core Defense is a fast arcade shooter built around one simple idea: your core never moves, and everything else comes to you. Waves of drones spawn at the edges of the arena and converge on the centre — quick darts, armoured hulks, and splitters that break in two when destroyed. Click or tap in their direction and the core fires along that line, and switch between the Pulse, Rapid, and Heavy weapons to match what's inbound. Every edge flash warns you where the next drone lands. Kills sometimes drop power-ups — shields, slow fields, multi-shot, explosive rounds — that you collect by shooting them. Chain kills without taking damage to build a combo and multiply your score, and every third wave you pick a permanent upgrade for the rest of the run. Between runs you level up, earn cores, and spend them in a store on new weapons, passive modifiers, and themes, while chasing achievements, missions, and three daily challenges.",
    href: "/games/neon-core-defense",
    categories: ["arcade", "quick-break", "casual", "mobile-friendly"],
    tags: ["shooter", "survival", "waves", "reflex", "canvas", "neon", "arcade", "high score", "combo", "power-ups", "upgrades"],
    thumbnail: "🎯",
    thumbnailType: "gradient",
    accent: "cyan",
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Click or tap anywhere in the arena to fire from the core toward that point. Use 1, 2, and 3 (or the weapon buttons) to switch weapons, and the same keys to pick an upgrade between waves. Press Enter to start or restart, and P or Esc to pause. Your best score, best wave, highest combo, and favourite weapon are saved on this device.",
    tips: [
      "Use edge flashes to identify the next threat before it enters the arena.",
      "Switch weapons based on enemy type instead of staying with one favorite.",
      "Protect your combo by collecting defensive power-ups before chasing risky bonus shots.",
    ],
    privacyNote: LOCAL_PROGRESS_NOTE,
    seoTitle: "Play Neon Core Defense Online Free | Darma Games",
    seoDescription:
      "Play Neon Core Defense free in your browser. Defend a stationary neon core through escalating waves of drones, build combos for a bigger multiplier, and chase your best score. No signup, mobile-friendly.",
    createdAt: "2026-07-17",
  },
  {
    id: "pacman-canvas",
    slug: "pacman-canvas",
    title: "Pacman Canvas",
    description: "A polished Darma integration of the classic Pacman canvas game with original local assets, sounds, and mobile controls.",
    longDescription:
      "Pacman Canvas preserves the original mini Pacman maze, ghost SVG assets, pills, power pills, arcade sound files, scoring, lives, and level progression, then wraps it in a production Darma player with responsive canvas scaling, keyboard, swipe, D-pad controls, pause, restart, mute, focus mode, local best score, and clear win/game-over overlays.",
    href: "/games/pacman-canvas",
    categories: ["arcade", "classic", "quick-break", "mobile-friendly"],
    tags: ["pacman", "canvas", "arcade", "retro", "ghosts", "maze", "keyboard", "mobile"],
    thumbnail: "🟡",
    thumbnailType: "gradient",
    accent: "amber",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Use Arrow keys or WASD to move Pacman. On mobile, swipe on the canvas or use the D-pad. Space/Enter starts the game, P or Esc pauses. Eat power pills to catch vulnerable ghosts.",
    tips: [
      "Clear one side of the maze while keeping an escape route open.",
      "Save power pills until multiple ghosts are close enough to reward the risk.",
      "Use tunnels and corners to change direction before ghosts surround you.",
    ],
    privacyNote: LOCAL_SCORE_NOTE,
    seoTitle: "Play Pacman Canvas Online Free | Darma Games",
    seoDescription:
      "Play Pacman Canvas free in your browser with local retro assets, ghosts, power pills, score, lives, keyboard controls, mobile swipes, and no signup.",
    createdAt: "2026-07-01",
  },

  {
    id: "endless-runner",
    slug: "endless-runner",
    title: "Endless Runner",
    description: "A polished canvas runner with the original parallax backgrounds, an animated sprite character, fair speed-aware obstacles, and mobile controls.",
    longDescription:
      "Endless Runner keeps the original project’s two parallax background images, then upgrades the demo into a Darma-ready canvas arcade game. The player is a real animated sprite (idle, run, jump, fall, slide, hurt), obstacles are pooled and fairly spaced based on current speed and reaction time, and the game stays responsive for long sessions. Rocks, spikes, crates, and logs require a jump; a flying bird and a hanging branch require a slide. Includes lives with a brief shield after each hit, score, local best score, start/pause/restart, responsive sizing, keyboard controls, and tap-to-jump mobile play.",
    href: "/games/endless-runner",
    categories: ["arcade", "quick-break", "mobile-friendly", "casual"],
    tags: ["runner", "endless", "canvas", "jump", "parallax", "obstacles", "mobile", "score"],
    thumbnail: "🏃",
    thumbnailType: "gradient",
    accent: "orange",
    featured: true,
    popular: true,
    isNew: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls:
      "Press Space, Arrow Up, W, or tap the canvas to jump. Press Arrow Down or S, or the Slide button, to slide under head-height obstacles. Use P or Esc to pause. On mobile, tap the canvas or the Jump/Slide buttons to play.",
    tips: [
      "Read the obstacle silhouette early to decide between jump and slide.",
      "Avoid repeated taps; one deliberate input gives the character a cleaner arc.",
      "After taking damage, use the brief shield to recover rhythm rather than rushing.",
    ],
    privacyNote: LOCAL_SCORE_NOTE,
    seoTitle: "Play Endless Runner Online Free | Darma Games",
    seoDescription:
      "Play Endless Runner free in your browser. Jump over obstacles, slide under birds and branches, collect coins, enjoy parallax canvas backgrounds, mobile controls, and local best score. No signup required.",
    createdAt: "2026-07-01",
  },

  {
    id: "typing-speed",
    slug: "typing-speed",
    title: "Typing Speed Pro",
    description: "A professional typing trainer with WPM, raw WPM, accuracy, mistake patterns, history, and multiple modes.",
    longDescription:
      "Typing Speed Pro upgrades the basic WPM test into a browser-only typing trainer. Choose quick tests, practice, accuracy mode, or challenge text; track corrected WPM, raw WPM, accuracy, mistakes, repeated missed characters, best scores, and local history; then copy your result after each round.",
    href: "/games/typing-speed",
    categories: ["arcade", "brain", "quick-break"],
    tags: ["typing", "wpm", "speed", "keyboard", "accuracy", "trainer", "history"],
    thumbnail: "⌨️",
    thumbnailType: "gradient",
    accent: "sky",
    isNew: true,
    featured: true,
    difficulty: "medium",
    playTime: "5 min",
    input: ["keyboard"],
    devices: ["desktop", "tablet"],
    controls: "Choose a mode, then start typing. The timer begins on the first character; paste is disabled; results show WPM, raw WPM, accuracy, mistakes, and local history.",
    tips: [
      "Prioritize accuracy before trying to raise raw WPM.",
      "Keep your eyes slightly ahead of the character you are typing.",
      "Review repeated mistake patterns and practice those letter combinations separately.",
    ],
    privacyNote: LOCAL_STATS_NOTE,
    seoTitle: "Play Typing Speed Pro Online Free | Darma Games",
    seoDescription:
      "Test and improve typing speed free in your browser with WPM, raw WPM, accuracy, mistake patterns, modes, local history, and copyable results. No signup.",
    createdAt: "2026-06-20",
  },
];

let publicGames: GameDefinition[] | null = null;
let gamesBySlug: Map<string, GameDefinition> | null = null;

export function getGames(): GameDefinition[] {
  if (!publicGames) {
    publicGames = GAME_DEFINITIONS.filter((game) => (game.visibility ?? "public") === "public");
  }
  return publicGames;
}

export function getGameBySlug(slug: string): GameDefinition | null {
  if (!gamesBySlug) {
    gamesBySlug = new Map(GAME_DEFINITIONS.map((game) => [game.slug, game]));
  }
  return gamesBySlug.get(slug) ?? null;
}

export function getGameSlugs(): string[] {
  return getGames().map((game) => game.slug);
}
