import type { GameDefinition } from "../domain/game";

const PRIVACY_NOTE =
  "This game runs in your browser. No signup is required. If progress is saved in the future, it should use local storage only.";

const GAME_DEFINITIONS: GameDefinition[] = [
  {
    id: "2048",
    slug: "2048",
    title: "2048 Classic",
    description: "Slide and merge numbered tiles to reach 2048.",
    longDescription:
      "2048 is a single-player sliding puzzle. Combine matching number tiles to grow them, keep the board tidy, and chase the elusive 2048 tile. A calm but addictive numbers puzzle that rewards planning over speed.",
    href: "/games/2048",
    categories: ["puzzle", "brain", "classic"],
    tags: ["numbers", "merge", "sliding", "strategy"],
    thumbnail: "🔢",
    thumbnailType: "gradient",
    accent: "amber",
    featured: true,
    popular: true,
    difficulty: "medium",
    playTime: "10 min",
    input: ["keyboard", "touch", "mouse"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Use arrow keys or swipe to slide all tiles. Matching tiles merge into one.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play 2048 Classic Online Free | Darma Games",
    seoDescription:
      "Play 2048 in your browser for free. Slide and merge numbered tiles to reach 2048. No signup, no downloads — just a quick numbers puzzle.",
    pinned: 1,
    createdAt: "2026-05-10",
  },
  {
    id: "snake",
    slug: "snake",
    title: "Snake",
    description: "Eat, grow, and avoid crashing into yourself.",
    longDescription:
      "The timeless arcade classic. Guide the snake to collect food, grow longer with every bite, and survive as long as you can without hitting the walls or your own tail. Simple to learn, hard to master.",
    href: "/games/snake",
    categories: ["arcade", "classic", "quick-break"],
    tags: ["retro", "snake", "reflex", "score"],
    thumbnail: "🐍",
    thumbnailType: "gradient",
    accent: "emerald",
    featured: true,
    popular: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["keyboard", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Steer with the arrow keys or swipe to change direction. Don't run into yourself.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Snake Online Free | Darma Games",
    seoDescription:
      "Play the classic Snake game free in your browser. Eat, grow, and beat your high score. No signup, no downloads.",
    pinned: 2,
    createdAt: "2026-05-08",
  },
  {
    id: "tic-tac-toe",
    slug: "tic-tac-toe",
    title: "Tic Tac Toe",
    description: "Get three in a row before your opponent.",
    longDescription:
      "A friendly two-player classic. Take turns placing X and O on a 3×3 grid and be the first to line up three marks. Perfect for a 60-second showdown with a friend on the same device.",
    href: "/games/tic-tac-toe",
    categories: ["classic", "casual", "2-players", "quick-break"],
    tags: ["xo", "grid", "two player", "casual"],
    thumbnail: "⭕",
    thumbnailType: "gradient",
    accent: "rose",
    popular: true,
    difficulty: "easy",
    playTime: "1 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap or click an empty cell to place your mark. Players alternate turns.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Tic Tac Toe Online Free | Darma Games",
    seoDescription:
      "Play Tic Tac Toe free in your browser. A quick two-player classic — get three in a row to win. No signup needed.",
    createdAt: "2026-04-28",
  },
  {
    id: "memory-cards",
    slug: "memory-cards",
    title: "Memory Cards",
    description: "Flip cards and match every pair from memory.",
    longDescription:
      "A relaxing concentration game. Flip cards two at a time to find matching pairs, remember where each one is, and clear the whole board in as few moves as possible. Great for a focused mental warm-up.",
    href: "/games/memory-cards",
    categories: ["casual", "brain", "quick-break"],
    tags: ["memory", "matching", "concentration", "pairs"],
    thumbnail: "🃏",
    thumbnailType: "gradient",
    accent: "violet",
    featured: true,
    difficulty: "easy",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Click or tap a card to flip it. Match two cards to keep them face up.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Memory Cards Online Free | Darma Games",
    seoDescription:
      "Play the Memory Cards matching game free in your browser. Flip cards, find pairs, and train your focus. No signup.",
    createdAt: "2026-05-02",
  },
  {
    id: "word-match",
    slug: "word-match",
    title: "Word Match",
    description: "Pair words with their meanings against the clock.",
    longDescription:
      "A light vocabulary game. Connect each word to its matching meaning or pair before time runs out. A quick way to sharpen language recall and reaction in short, satisfying rounds.",
    href: "/games/word-match",
    categories: ["brain", "casual", "puzzle"],
    tags: ["words", "vocabulary", "matching", "language"],
    thumbnail: "🔤",
    thumbnailType: "gradient",
    accent: "cyan",
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap or click a word, then tap its matching pair to link them.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Word Match Online Free | Darma Games",
    seoDescription:
      "Play Word Match free in your browser. Pair words with their meanings to score points. No signup, no downloads.",
    createdAt: "2026-04-20",
  },
  {
    id: "sudoku-mini",
    slug: "sudoku-mini",
    title: "Sudoku Mini",
    description: "A compact Sudoku for a quick logic fix.",
    longDescription:
      "Sudoku Mini trims the classic number puzzle into a faster grid. Fill every row, column, and box without repeating a digit. All the logic of full Sudoku in a session you can finish on a coffee break.",
    href: "/games/sudoku-mini",
    categories: ["puzzle", "brain"],
    tags: ["sudoku", "numbers", "logic", "grid"],
    thumbnail: "🧮",
    thumbnailType: "gradient",
    accent: "indigo",
    featured: true,
    difficulty: "hard",
    playTime: "10 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Select a cell, then type or tap a number. Each digit appears once per row, column, and box.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Sudoku Mini Online Free | Darma Games",
    seoDescription:
      "Play Sudoku Mini free in your browser. A compact logic puzzle for a quick brain break. No signup required.",
    createdAt: "2026-04-15",
  },
  {
    id: "color-switch",
    slug: "color-switch",
    title: "Color Switch",
    description: "Tap through obstacles that only match your color.",
    longDescription:
      "A fast, hypnotic arcade game. Tap to keep moving and only pass through sections that match your current color. One-touch controls make it perfect for mobile, with reflex-testing difficulty that ramps quickly.",
    href: "/games/color-switch",
    categories: ["arcade", "quick-break", "mobile-friendly"],
    tags: ["reflex", "color", "tap", "endless"],
    thumbnail: "🎨",
    thumbnailType: "gradient",
    accent: "fuchsia",
    featured: true,
    isNew: true,
    difficulty: "medium",
    playTime: "1 min",
    input: ["touch", "mouse", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Tap, click, or press space to move. Only pass through matching colors.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Color Switch Online Free | Darma Games",
    seoDescription:
      "Play Color Switch free in your browser. A one-tap reflex arcade game built for quick mobile breaks. No signup.",
    createdAt: "2026-06-12",
  },
  {
    id: "reaction-timer",
    slug: "reaction-timer",
    title: "Reaction Timer",
    description: "Test how fast you respond when the screen flips.",
    longDescription:
      "A pure reflex test. Wait for the signal, then react as fast as you can — but don't jump the gun. Measure your reaction time across a few rounds and try to beat your personal best.",
    href: "/games/reaction-timer",
    categories: ["arcade", "quick-break", "casual"],
    tags: ["reflex", "speed", "reaction", "timing"],
    thumbnail: "⚡",
    thumbnailType: "gradient",
    accent: "lime",
    isNew: true,
    difficulty: "easy",
    playTime: "1 min",
    input: ["mouse", "touch", "keyboard"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Wait for the screen to change, then click, tap, or press any key as fast as you can.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Reaction Timer Online Free | Darma Games",
    seoDescription:
      "Test your reaction time free in your browser. React the instant the screen flips and beat your best. No signup.",
    createdAt: "2026-06-18",
  },
  {
    id: "minesweeper",
    slug: "minesweeper",
    title: "Minesweeper",
    description: "Clear the grid without detonating a mine.",
    longDescription:
      "The classic logic puzzle. Reveal safe squares using the numbers as clues, flag the mines you suspect, and clear the whole board without a single wrong move. Calm, methodical, and endlessly replayable.",
    href: "/games/minesweeper",
    categories: ["puzzle", "classic", "brain"],
    tags: ["mines", "logic", "grid", "strategy"],
    thumbnail: "💣",
    thumbnailType: "gradient",
    accent: "blue",
    popular: true,
    difficulty: "hard",
    playTime: "10 min",
    input: ["mouse"],
    devices: ["desktop"],
    controls: "Left-click to reveal a square, right-click to flag a suspected mine. Numbers show nearby mines.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Minesweeper Online Free | Darma Games",
    seoDescription:
      "Play Minesweeper free in your browser. Clear the grid using logic and avoid the mines. No signup, no downloads.",
    createdAt: "2026-04-10",
  },
  {
    id: "connect-four",
    slug: "connect-four",
    title: "Connect Four",
    description: "Drop discs and line up four in a row to win.",
    longDescription:
      "A strategic two-player favorite. Take turns dropping colored discs into the grid and be the first to connect four in a row — horizontally, vertically, or diagonally — while blocking your opponent.",
    href: "/games/connect-four",
    categories: ["classic", "2-players", "brain"],
    tags: ["strategy", "two player", "grid", "connect"],
    thumbnail: "🔴",
    thumbnailType: "gradient",
    accent: "orange",
    difficulty: "medium",
    playTime: "5 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet", "mobile"],
    controls: "Click or tap a column to drop your disc. First to connect four wins.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Connect Four Online Free | Darma Games",
    seoDescription:
      "Play Connect Four free in your browser. A two-player strategy classic — line up four to win. No signup required.",
    createdAt: "2026-04-22",
  },
  {
    id: "chess-mini",
    slug: "chess-mini",
    title: "Chess Mini",
    description: "A streamlined chess board for a focused match.",
    longDescription:
      "Chess Mini brings the full game of chess to a clean, distraction-free board. Plan your openings, control the center, and checkmate your opponent. Ideal for a longer, thoughtful session.",
    href: "/games/chess-mini",
    categories: ["classic", "brain", "2-players"],
    tags: ["chess", "strategy", "board", "two player"],
    thumbnail: "♟️",
    thumbnailType: "gradient",
    accent: "teal",
    difficulty: "hard",
    playTime: "15 min",
    input: ["mouse", "touch"],
    devices: ["desktop", "tablet"],
    controls: "Click or tap a piece, then tap a highlighted square to move it.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Chess Mini Online Free | Darma Games",
    seoDescription:
      "Play Chess Mini free in your browser. A clean chess board for a focused strategy match. No signup, no downloads.",
    createdAt: "2026-04-05",
  },
  {
    id: "typing-speed",
    slug: "typing-speed",
    title: "Typing Speed",
    description: "Measure your words-per-minute in a quick sprint.",
    longDescription:
      "A focused typing test. Type the prompt as fast and accurately as you can, then see your words-per-minute and accuracy. A satisfying way to warm up your fingers and track your progress over time.",
    href: "/games/typing-speed",
    categories: ["arcade", "brain", "quick-break"],
    tags: ["typing", "wpm", "speed", "keyboard"],
    thumbnail: "⌨️",
    thumbnailType: "gradient",
    accent: "sky",
    isNew: true,
    difficulty: "medium",
    playTime: "1 min",
    input: ["keyboard"],
    devices: ["desktop"],
    controls: "Start typing the prompt text. Your speed and accuracy are measured as you go.",
    privacyNote: PRIVACY_NOTE,
    seoTitle: "Play Typing Speed Test Online Free | Darma Games",
    seoDescription:
      "Test your typing speed free in your browser. Measure your words-per-minute and accuracy in a quick sprint. No signup.",
    createdAt: "2026-06-20",
  },
];

let publicGames: GameDefinition[] | null = null;
let gamesBySlug: Map<string, GameDefinition> | null = null;

export function getGames(): GameDefinition[] {
  if (!publicGames) {
    publicGames = GAME_DEFINITIONS.filter((game) => (game.visibility ?? "public") === "public");
  }
  return publicGames;
}

export function getGameBySlug(slug: string): GameDefinition | null {
  if (!gamesBySlug) {
    gamesBySlug = new Map(GAME_DEFINITIONS.map((game) => [game.slug, game]));
  }
  return gamesBySlug.get(slug) ?? null;
}

export function getGameSlugs(): string[] {
  return getGames().map((game) => game.slug);
}
