import { Button } from "@/components/ui";
import { PreviewToolbar, SegmentedControl } from "@/features/tools/components";
import { cn } from "@/lib/cn";
import type { TransformGeneratorState } from "../types";
import { getPreviewStyle, getPreviewTransform } from "../transform";

export function TransformPreview({ state, onPatch }: { state: TransformGeneratorState; onPatch: (patch: Partial<TransformGeneratorState>) => void }) {
  const style = getPreviewStyle(state);
  const transform = getPreviewTransform(state);
  return <section className="overflow-hidden rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)]"><PreviewToolbar title="Transform stage" description="Compare the original outline, origin marker, and transformed object." actions={<Button size="sm" variant="secondary" onClick={() => onPatch({ previewState: state.previewState === "animated" ? "base" : "animated" })}>Replay</Button>}><SegmentedControl ariaLabel="Transform preview overlays" value={state.showAxisOverlay ? "grid" : state.showBeforeOutline ? "outline" : "clean"} onChange={(value) => onPatch({ showAxisOverlay: value === "grid", show3dGrid: value === "grid", showBeforeOutline: value !== "clean" })} options={[{ value: "grid", label: "Grid" }, { value: "outline", label: "Outline" }, { value: "clean", label: "Clean" }]} /></PreviewToolbar><div className={cn("relative flex min-h-[520px] items-center justify-center overflow-hidden bg-[var(--color-bg-soft)] p-8", state.showAxisOverlay && "bg-[linear-gradient(to_right,var(--color-preview-grid)_1px,transparent_1px),linear-gradient(to_bottom,var(--color-preview-grid)_1px,transparent_1px)] bg-[size:40px_40px]")}><div className="relative" style={{ width: state.style.width, height: state.style.height }}>{state.showBeforeOutline ? <div className="absolute inset-0 rounded-[var(--radius-md)] border-2 border-dashed border-[var(--color-text-soft)]/40" /> : null}{state.showOriginMarker ? <span className="absolute left-1/2 top-1/2 z-20 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-[var(--color-accent)] shadow" /> : null}<div className="flex h-full w-full items-center justify-center rounded-[var(--radius-md)] text-center text-sm font-black shadow-[var(--shadow-md)] transition-transform motion-reduce:transition-none" style={{ ...style, transform, transformOrigin: `${state.origin.x} ${state.origin.y} ${state.origin.z}` }}>Transform</div></div></div></section>;
}
