import { Input, Select } from "@/components/ui";
import { ColorField, ControlGrid, ControlSection, NumberField, PresetGallery, SegmentedControl, SliderNumberField, ToolControlPanel } from "@/features/tools/components";
import { TRANSFORM_PRESETS } from "../presets";
import type { TransformGeneratorState, TransformMode, TransformOriginPreset, TransformPreset, PreviewObject } from "../types";
import { OriginPicker } from "./OriginPicker";
import { TransformOrderChips } from "./TransformOrderChips";

const modes: TransformMode[] = ["2d", "3d", "hover", "entrance", "card-tilt"];
const objects: PreviewObject[] = ["card", "image", "button", "modal", "badge", "panel"];

export function TransformControls({ state, onPatch, onLoadPreset }: { state: TransformGeneratorState; onPatch: (patch: Partial<TransformGeneratorState>) => void; onLoadPreset: (preset: TransformPreset) => void }) {
  return <ToolControlPanel title="Transform settings" description="Tune transforms, origin, interaction, and export options.">
    <ControlSection title="Presets"><PresetGallery presets={[...TRANSFORM_PRESETS]} selectedId={state.presetId} onSelect={(_, preset) => onLoadPreset(preset)} getId={(preset) => preset.id} getLabel={(preset) => preset.name} getDescription={(preset) => preset.description} /></ControlSection>
    <ControlSection title="Mode"><SegmentedControl ariaLabel="Transform mode" value={state.mode} onChange={(mode) => onPatch({ mode })} options={modes.map((value) => ({ value, label: value }))} /></ControlSection>
    <ControlSection title="2D transform"><ControlGrid columns={2}><SliderNumberField label="Translate X" value={state.transform2d.translateX} min={-300} max={300} unit={state.transform2d.translateUnit} onChange={(translateX) => onPatch({ transform2d: { ...state.transform2d, translateX } })} /><SliderNumberField label="Translate Y" value={state.transform2d.translateY} min={-300} max={300} unit={state.transform2d.translateUnit} onChange={(translateY) => onPatch({ transform2d: { ...state.transform2d, translateY } })} /><SliderNumberField label="Rotate" value={state.transform2d.rotate} min={-360} max={360} unit="deg" onChange={(rotate) => onPatch({ transform2d: { ...state.transform2d, rotate } })} /><SliderNumberField label="Scale X" value={state.transform2d.scaleX} min={0.1} max={3} step={0.05} onChange={(scaleX) => onPatch({ transform2d: { ...state.transform2d, scaleX } })} /><SliderNumberField label="Scale Y" value={state.transform2d.scaleY} min={0.1} max={3} step={0.05} onChange={(scaleY) => onPatch({ transform2d: { ...state.transform2d, scaleY } })} /><SliderNumberField label="Skew X" value={state.transform2d.skewX} min={-60} max={60} unit="deg" onChange={(skewX) => onPatch({ transform2d: { ...state.transform2d, skewX } })} /></ControlGrid><div className="mt-3"><TransformOrderChips order={state.transform2d.order} /></div></ControlSection>
    <ControlSection title="Origin"><OriginPicker value={state.origin.preset} onChange={(preset: TransformOriginPreset) => onPatch({ origin: { ...state.origin, preset, x: preset.split(" ")[1] ?? "center", y: preset.split(" ")[0] ?? "center" } })} /></ControlSection>
    <ControlSection title="Preview object"><ControlGrid columns={2}><label className="space-y-1 text-xs font-semibold text-[var(--color-text-soft)]"><span>Object</span><Select size="sm" value={state.style.previewObject} onChange={(e) => onPatch({ style: { ...state.style, previewObject: e.target.value as PreviewObject } })}>{objects.map((item) => <option key={item} value={item}>{item}</option>)}</Select></label><ColorField label="Background" value={state.style.background} onChange={(background) => onPatch({ style: { ...state.style, background } })} /><NumberField label="Width" value={state.style.width} min={80} max={640} unit="px" onChange={(width) => onPatch({ style: { ...state.style, width } })} /><NumberField label="Height" value={state.style.height} min={60} max={420} unit="px" onChange={(height) => onPatch({ style: { ...state.style, height } })} /></ControlGrid></ControlSection>
    <ControlSection title="Export"><Input size="sm" value={state.exportOptions.className} onChange={(e) => onPatch({ exportOptions: { ...state.exportOptions, className: e.target.value } })} aria-label="CSS class name" /></ControlSection>
  </ToolControlPanel>;
}
