import type { PomodoroPreset } from "./types";

export const DEFAULT_POMODORO_PRESET_ID = "classic";

export const POMODORO_PRESETS: PomodoroPreset[] = [
  {
    id: "classic",
    name: "Classic 25 / 5",
    description: "The standard four-session Pomodoro cycle with a 15-minute long break.",
    task: "Finish the next focused task",
    targetSessions: 4,
    config: {
      focusMinutes: 25,
      shortBreakMinutes: 5,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.55,
      notificationsEnabled: false,
    },
  },
  {
    id: "deep-work",
    name: "Deep work 50 / 10",
    description: "Longer concentration blocks for coding, writing, and design work.",
    task: "Deep work block",
    targetSessions: 3,
    config: {
      focusMinutes: 50,
      shortBreakMinutes: 10,
      longBreakMinutes: 25,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "study-cycle",
    name: "Study 45 / 15",
    description: "A balanced study rhythm with a longer recovery break.",
    task: "Study one topic",
    targetSessions: 4,
    config: {
      focusMinutes: 45,
      shortBreakMinutes: 15,
      longBreakMinutes: 30,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "quick-sprint",
    name: "Quick sprint 15 / 3",
    description: "Short activation blocks for small tasks or low-energy days.",
    task: "Complete one quick win",
    targetSessions: 4,
    config: {
      focusMinutes: 15,
      shortBreakMinutes: 3,
      longBreakMinutes: 10,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: true,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.45,
      notificationsEnabled: false,
    },
  },
  {
    id: "creative-flow",
    name: "Creative flow 90 / 20",
    description: "Extended blocks for illustration, editing, and uninterrupted creative work.",
    task: "Creative production block",
    targetSessions: 2,
    config: {
      focusMinutes: 90,
      shortBreakMinutes: 20,
      longBreakMinutes: 35,
      sessionsBeforeLongBreak: 2,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "meeting-recovery",
    name: "Meeting recovery 10 / 5",
    description: "A lightweight cycle for inbox cleanup, notes, and post-meeting actions.",
    task: "Process notes and next actions",
    targetSessions: 3,
    config: {
      focusMinutes: 10,
      shortBreakMinutes: 5,
      longBreakMinutes: 10,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: true,
      autoStartFocus: true,
      soundEnabled: true,
      volume: 0.4,
      notificationsEnabled: false,
    },
  },
  {
    id: "exam-cram",
    name: "Exam revision 30 / 5",
    description: "Repeatable revision blocks with short resets for long study days.",
    task: "Revise one exam topic",
    targetSessions: 6,
    config: {
      focusMinutes: 30,
      shortBreakMinutes: 5,
      longBreakMinutes: 20,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: true,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "writing-sprint",
    name: "Writing sprint 40 / 8",
    description: "Draft-first blocks that keep editing out of the writing window.",
    task: "Draft the next section",
    targetSessions: 3,
    config: {
      focusMinutes: 40,
      shortBreakMinutes: 8,
      longBreakMinutes: 20,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.45,
      notificationsEnabled: false,
    },
  },
  {
    id: "code-review",
    name: "Code review 20 / 5",
    description: "Enough time to read a pull request properly without losing the whole morning.",
    task: "Review one pull request",
    targetSessions: 4,
    config: {
      focusMinutes: 20,
      shortBreakMinutes: 5,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: true,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.45,
      notificationsEnabled: false,
    },
  },
  {
    id: "language-practice",
    name: "Language practice 20 / 10",
    description: "Alternating drill and rest blocks for vocabulary and listening work.",
    task: "Practise vocabulary and listening",
    targetSessions: 4,
    config: {
      focusMinutes: 20,
      shortBreakMinutes: 10,
      longBreakMinutes: 20,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: true,
      autoStartFocus: true,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "adhd-friendly",
    name: "Low-friction 12 / 6",
    description: "Very short starts with generous breaks for days when beginning is the hard part.",
    task: "Start the task, nothing more",
    targetSessions: 5,
    config: {
      focusMinutes: 12,
      shortBreakMinutes: 6,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: true,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.4,
      notificationsEnabled: false,
    },
  },
  {
    id: "reading-session",
    name: "Deep reading 35 / 10",
    description: "Long enough to hold an argument in mind, short enough to stay attentive.",
    task: "Read and annotate one chapter",
    targetSessions: 3,
    config: {
      focusMinutes: 35,
      shortBreakMinutes: 10,
      longBreakMinutes: 25,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.4,
      notificationsEnabled: false,
    },
  },
  {
    id: "admin-batch",
    name: "Admin batch 25 / 5",
    description: "One block for email, invoices, and small approvals instead of all-day drip.",
    task: "Clear admin and approvals",
    targetSessions: 2,
    config: {
      focusMinutes: 25,
      shortBreakMinutes: 5,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 2,
      autoStartBreaks: true,
      autoStartFocus: true,
      soundEnabled: true,
      volume: 0.35,
      notificationsEnabled: false,
    },
  },
  {
    id: "practice-instrument",
    name: "Instrument practice 20 / 5",
    description: "Warm-up, technique, and repertoire blocks with hand-rest breaks.",
    task: "Practise one piece or technique",
    targetSessions: 4,
    config: {
      focusMinutes: 20,
      shortBreakMinutes: 5,
      longBreakMinutes: 20,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.3,
      notificationsEnabled: false,
    },
  },
  {
    id: "evening-wind-down",
    name: "Evening wind-down 20 / 10",
    description: "A quieter end-of-day cycle for planning tomorrow and closing loops.",
    task: "Close the day and plan tomorrow",
    targetSessions: 2,
    config: {
      focusMinutes: 20,
      shortBreakMinutes: 10,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 2,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.3,
      notificationsEnabled: false,
    },
  },
  {
    id: "pair-programming",
    name: "Pair programming 45 / 15",
    description: "Driver and navigator blocks with a real break before switching roles.",
    task: "Pair on the current ticket",
    targetSessions: 3,
    config: {
      focusMinutes: 45,
      shortBreakMinutes: 15,
      longBreakMinutes: 30,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.45,
      notificationsEnabled: false,
    },
  },
];
