import type { PomodoroPreset } from "./types";

export const DEFAULT_POMODORO_PRESET_ID = "classic";

export const POMODORO_PRESETS: PomodoroPreset[] = [
  {
    id: "classic",
    name: "Classic 25 / 5",
    description: "The standard four-session Pomodoro cycle with a 15-minute long break.",
    task: "Finish the next focused task",
    targetSessions: 4,
    config: {
      focusMinutes: 25,
      shortBreakMinutes: 5,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.55,
      notificationsEnabled: false,
    },
  },
  {
    id: "deep-work",
    name: "Deep work 50 / 10",
    description: "Longer concentration blocks for coding, writing, and design work.",
    task: "Deep work block",
    targetSessions: 3,
    config: {
      focusMinutes: 50,
      shortBreakMinutes: 10,
      longBreakMinutes: 25,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "study-cycle",
    name: "Study 45 / 15",
    description: "A balanced study rhythm with a longer recovery break.",
    task: "Study one topic",
    targetSessions: 4,
    config: {
      focusMinutes: 45,
      shortBreakMinutes: 15,
      longBreakMinutes: 30,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "quick-sprint",
    name: "Quick sprint 15 / 3",
    description: "Short activation blocks for small tasks or low-energy days.",
    task: "Complete one quick win",
    targetSessions: 4,
    config: {
      focusMinutes: 15,
      shortBreakMinutes: 3,
      longBreakMinutes: 10,
      sessionsBeforeLongBreak: 4,
      autoStartBreaks: true,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.45,
      notificationsEnabled: false,
    },
  },
  {
    id: "creative-flow",
    name: "Creative flow 90 / 20",
    description: "Extended blocks for illustration, editing, and uninterrupted creative work.",
    task: "Creative production block",
    targetSessions: 2,
    config: {
      focusMinutes: 90,
      shortBreakMinutes: 20,
      longBreakMinutes: 35,
      sessionsBeforeLongBreak: 2,
      autoStartBreaks: false,
      autoStartFocus: false,
      soundEnabled: true,
      volume: 0.5,
      notificationsEnabled: false,
    },
  },
  {
    id: "meeting-recovery",
    name: "Meeting recovery 10 / 5",
    description: "A lightweight cycle for inbox cleanup, notes, and post-meeting actions.",
    task: "Process notes and next actions",
    targetSessions: 3,
    config: {
      focusMinutes: 10,
      shortBreakMinutes: 5,
      longBreakMinutes: 10,
      sessionsBeforeLongBreak: 3,
      autoStartBreaks: true,
      autoStartFocus: true,
      soundEnabled: true,
      volume: 0.4,
      notificationsEnabled: false,
    },
  },
];
