"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BookOpenText, ExternalLink, RotateCcw, Search } from "lucide-react";
import { Badge, Button, Card, Input, Select } from "@/components/ui";
import type { GlossaryCategory, GlossaryTerm } from "../schema";

type CategoryFilter = GlossaryCategory | "all";
const CATEGORIES: Record<CategoryFilter, string> = { all: "All categories", engineering: "Engineering", product: "Product", delivery: "Delivery", design: "Design", operations: "Operations", "people-business": "People & business" };

export function GlossaryExplorer({ terms }: { terms: GlossaryTerm[] }) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<CategoryFilter>("all");
  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return terms.filter((term) => (category === "all" || term.category === category) && (!needle || [term.term, term.acronym, ...term.aliases, term.definition, term.practicalMeaning, ...term.tags].filter(Boolean).join(" ").toLowerCase().includes(needle)));
  }, [category, query, terms]);
  const active = Boolean(query || category !== "all");
  return (
    <section className="mx-auto max-w-[var(--container-wide)] px-4 pb-16 sm:px-6 lg:px-8" aria-labelledby="glossary-explorer-title">
      <Card padding="lg" className="mb-6"><div className="grid gap-3 md:grid-cols-[minmax(280px,1.7fr)_minmax(200px,1fr)_auto]"><label className="relative block"><span className="sr-only">Search technical glossary</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-text-tertiary)]" aria-hidden /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search API, Sprint, SLO, design system…" className="pl-9" /></label><label><span className="sr-only">Filter glossary category</span><Select value={category} onChange={(event) => setCategory(event.target.value as CategoryFilter)}>{Object.entries(CATEGORIES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><Button variant="ghost" disabled={!active} onClick={() => { setQuery(""); setCategory("all"); }} leftIcon={<RotateCcw className="h-4 w-4" aria-hidden />}>Reset</Button></div><p id="glossary-explorer-title" className="mt-4 flex items-center gap-2 text-sm text-[var(--color-text-secondary)]" aria-live="polite"><BookOpenText className="h-4 w-4" aria-hidden /><strong className="text-[var(--color-text-primary)]">{filtered.length}</strong> matching terms</p></Card>
      {filtered.length ? <div className="grid gap-5 lg:grid-cols-2">{filtered.map((term) => <Card key={term.slug} as="article" padding="lg" id={term.slug} className="scroll-mt-28"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="soft">{CATEGORIES[term.category]}</Badge>{term.acronym ? <Badge variant="outline">{term.acronym}</Badge> : null}</div><Link href={`#${term.slug}`} aria-label={`Link to ${term.term}`} className="text-[var(--color-text-tertiary)] transition hover:text-[var(--color-primary)]">#</Link></div><h2 className="mt-4 text-2xl font-black text-[var(--color-text-primary)]">{term.term}</h2><p className="mt-3 text-sm leading-6 text-[var(--color-text-secondary)]">{term.definition}</p><div className="mt-5 rounded-[var(--radius-md)] border border-[var(--color-primary-border)] bg-[var(--color-primary-soft)] p-4"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-[var(--color-primary)]">In practice</p><p className="mt-2 text-sm leading-6 text-[var(--color-text-primary)]">{term.practicalMeaning}</p></div><div className="mt-4"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-[var(--color-text-tertiary)]">Example</p><p className="mt-2 text-sm leading-6 text-[var(--color-text-secondary)]">{term.example}</p></div>{term.relatedRoleSlugs.length || term.relatedMethodSlugs.length ? <div className="mt-5 flex flex-wrap gap-2">{term.relatedRoleSlugs.slice(0, 3).map((slug) => <Link key={slug} href={`/tech-careers/${slug}`} className="inline-flex items-center gap-1 rounded-[var(--radius-full)] border border-[var(--color-border-default)] px-3 py-1 text-xs font-semibold text-[var(--color-text-secondary)] transition hover:border-[var(--color-primary-border)] hover:text-[var(--color-primary)]">Role <ExternalLink className="h-3 w-3" aria-hidden /></Link>)}{term.relatedMethodSlugs.slice(0, 3).map((slug) => <Link key={slug} href={`/ways-of-working/${slug}`} className="inline-flex items-center gap-1 rounded-[var(--radius-full)] border border-[var(--color-border-default)] px-3 py-1 text-xs font-semibold text-[var(--color-text-secondary)] transition hover:border-[var(--color-primary-border)] hover:text-[var(--color-primary)]">Method <ExternalLink className="h-3 w-3" aria-hidden /></Link>)}</div> : null}</Card>)}</div> : <Card padding="lg" className="text-center"><h2 className="text-xl font-bold text-[var(--color-text-primary)]">No glossary term found</h2><p className="mt-2 text-sm text-[var(--color-text-secondary)]">Try the full term, an acronym, or a broader category.</p></Card>}
    </section>
  );
}
