import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { Badge, Card } from "@/components/ui";
import { getEditorialPage, getResourceHub, getResourceHubs } from "@/features/editorial";
import { getLearningPath } from "@/features/learning-paths";
import { getResourceCatalog } from "@/features/resources";
import { ResourceLogo } from "@/features/resources/components";
import { absoluteUrl } from "@/features/tools/seo";

type Props = { params: Promise<{ category: string }> };
export function generateStaticParams() { return getResourceHubs().map((hub) => ({ category: hub.slug })); }

function resourcesForHub(slug: string) {
  const hub = getResourceHub(slug); if (!hub) return [];
  const terms = hub.tagTerms.map((term) => term.toLowerCase());
  return getResourceCatalog().filter((resource) => resource.review.status !== "archived" && (resource.categories.some((category) => hub.categoryNames.includes(category)) || [...resource.tags, resource.name].some((value) => terms.some((term) => value.toLowerCase().includes(term))))).sort((a, b) => Number(b.featured) - Number(a.featured) || Number(b.review.status === "verified") - Number(a.review.status === "verified") || a.name.localeCompare(b.name));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { category } = await params; const hub = getResourceHub(category); if (!hub) return {};
  return { title: `${hub.title} — curated docs, courses, and tools | Darma`, description: hub.summary, keywords: [...hub.tagTerms, `${hub.shortTitle} resources`, "developer resources"], alternates: { canonical: `/resources/${hub.slug}` }, openGraph: { title: hub.title, description: hub.summary, url: absoluteUrl(`/resources/${hub.slug}`), type: "website" }, twitter: { card: "summary_large_image", title: hub.title, description: hub.summary } };
}

export default async function ResourceHubPage({ params }: Props) {
  const { category } = await params; const hub = getResourceHub(category); if (!hub) notFound();
  const resources = resourcesForHub(hub.slug); const featured = resources.slice(0, 18);
  const paths = hub.relatedPathSlugs.map(getLearningPath).filter(Boolean);
  const guides = hub.relatedGuideSlugs.map(getEditorialPage).filter(Boolean);
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", name: hub.title, description: hub.summary, url: absoluteUrl(`/resources/${hub.slug}`), dateModified: hub.updatedAt, mainEntity: { "@id": `${absoluteUrl(`/resources/${hub.slug}`)}#list` } }, { "@type": "ItemList", "@id": `${absoluteUrl(`/resources/${hub.slug}`)}#list`, numberOfItems: resources.length, itemListElement: featured.map((resource, index) => ({ "@type": "ListItem", position: index + 1, name: resource.name, url: resource.url })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Resources", item: absoluteUrl("/resources") }, { "@type": "ListItem", position: 3, name: hub.shortTitle, item: absoluteUrl(`/resources/${hub.slug}`) }] }] };
  return <div className="pb-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <section className="mx-auto max-w-[var(--container-wide)] px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><Link href="/resources" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--color-text-secondary)] transition hover:text-[var(--color-primary)]"><ArrowLeft className="h-4 w-4" aria-hidden />All resources</Link><div className="mt-7 grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px] lg:items-start"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><Badge variant="soft">Curated resource hub</Badge><Badge variant="outline">{resources.length} matching sources</Badge></div><h1 className="mt-5 text-4xl font-black tracking-[-0.045em] text-[var(--color-text-primary)] sm:text-5xl lg:text-6xl">{hub.title}</h1><p className="mt-6 max-w-3xl text-base leading-8 text-[var(--color-text-secondary)] sm:text-lg">{hub.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#recommended-resources" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--radius-md)] bg-[var(--color-primary)] px-5 text-sm font-semibold text-[var(--color-primary-text)]">See recommended resources <ArrowRight className="h-4 w-4" aria-hidden /></a><Link href={`/resources?category=${encodeURIComponent(hub.categoryNames[0])}`} className="inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] border border-[var(--color-border-default)] bg-[var(--color-surface-raised)] px-5 text-sm font-semibold text-[var(--color-text-primary)]">Open filtered explorer</Link></div></div><Card padding="lg"><ShieldCheck className="h-5 w-5 text-[var(--color-primary)]" aria-hidden /><h2 className="mt-4 text-xl font-black text-[var(--color-text-primary)]">How sources are selected</h2><ul className="mt-4 space-y-3">{hub.selectionCriteria.map((item) => <li key={item} className="flex items-start gap-2 text-sm leading-6 text-[var(--color-text-secondary)]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[var(--color-success-text)]" aria-hidden />{item}</li>)}</ul><Link href="/editorial-policy" className="mt-5 inline-flex text-sm font-bold text-[var(--color-primary)]">Read the full review policy →</Link></Card></div></section>

    <section className="mx-auto max-w-[var(--container-wide)] px-4 pb-10 sm:px-6 lg:px-8"><div className="grid gap-5 lg:grid-cols-2"><Card padding="lg"><h2 className="text-2xl font-black text-[var(--color-text-primary)]">Who this hub helps</h2><ul className="mt-5 space-y-3">{hub.audience.map((item) => <li key={item} className="flex items-start gap-2 text-sm leading-6 text-[var(--color-text-secondary)]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[var(--color-primary)]" aria-hidden />{item}</li>)}</ul></Card><Card padding="lg"><h2 className="text-2xl font-black text-[var(--color-text-primary)]">Learn these ideas first</h2><ol className="mt-5 space-y-3">{hub.learnFirst.map((item, index) => <li key={item} className="flex items-start gap-3 text-sm leading-6 text-[var(--color-text-secondary)]"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[var(--color-primary)] font-mono text-xs font-black text-[var(--color-primary-text)]">{index + 1}</span>{item}</li>)}</ol></Card></div></section>

    <section id="recommended-resources" className="mx-auto max-w-[var(--container-wide)] scroll-mt-28 px-4 pb-10 sm:px-6 lg:px-8"><div className="mb-6"><Badge variant="soft">Recommended starting points</Badge><h2 className="mt-3 text-3xl font-black tracking-[-0.035em] text-[var(--color-text-primary)]">Trusted references for {hub.shortTitle.toLowerCase()}</h2><p className="mt-3 max-w-3xl text-base leading-7 text-[var(--color-text-secondary)]">The cards prioritize featured and reviewed sources. Open the full explorer when you need narrower filters by level, format, price, or publisher.</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{featured.map((resource) => <Card key={resource.id} padding="lg" className="flex h-full flex-col"><div className="flex items-start justify-between gap-3"><ResourceLogo resource={resource} /><div className="flex flex-wrap justify-end gap-1"><Badge variant={resource.publisherType === "official" ? "success" : "outline"}>{resource.publisherType}</Badge><Badge variant="outline">{resource.resourceType}</Badge></div></div><h3 className="mt-5 text-lg font-black text-[var(--color-text-primary)]">{resource.name}</h3><p className="mt-2 flex-1 text-sm leading-7 text-[var(--color-text-secondary)]">{resource.summary}</p><div className="mt-4 flex flex-wrap gap-1.5">{resource.levels.map((level) => <Badge key={level} variant="soft">{level}</Badge>)}</div><a href={resource.url} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--color-primary)]">Visit source <ExternalLink className="h-4 w-4" aria-hidden /></a></Card>)}</div></section>

    {(guides.length || paths.length) ? <section className="mx-auto max-w-[var(--container-wide)] px-4 sm:px-6 lg:px-8"><div className="mb-5"><Badge variant="soft">Use the resources in context</Badge><h2 className="mt-3 text-3xl font-black tracking-[-0.035em] text-[var(--color-text-primary)]">Continue with a roadmap or guided path</h2></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{guides.map((guide) => <Link key={guide!.slug} href={`/guides/${guide!.slug}`} className="block h-full"><Card variant="interactive" padding="lg" className="h-full"><Badge variant="outline">Guide</Badge><h3 className="mt-4 text-lg font-black text-[var(--color-text-primary)]">{guide!.shortTitle}</h3><p className="mt-2 text-sm leading-6 text-[var(--color-text-secondary)]">{guide!.summary}</p></Card></Link>)}{paths.map((path) => <Link key={path!.slug} href={`/learning-paths/${path!.slug}`} className="block h-full"><Card variant="interactive" padding="lg" className="h-full"><Badge variant="outline">Learning path</Badge><h3 className="mt-4 text-lg font-black text-[var(--color-text-primary)]">{path!.shortTitle}</h3><p className="mt-2 text-sm leading-6 text-[var(--color-text-secondary)]">{path!.summary}</p></Card></Link>)}</div></section> : null}
  </div>;
}
