import {
  Bot,
  Boxes,
  Gamepad2,
  GraduationCap,
  LayoutTemplate,
  LibraryBig,
  Sparkles,
  Wrench,
} from "lucide-react";
import type { CollectionDefinition, CollectionId } from "../domain/collection";

export const COLLECTIONS: CollectionDefinition[] = [
  {
    id: "tools",
    title: "Tools",
    navLabel: "Tools",
    href: "/tools",
    eyebrow: "Utility collection",
    description: "Useful browser tools for daily work, content, design, development, and productivity.",
    status: "live",
    tone: "productive",
    accent: "orange",
    icon: Wrench,
    badges: ["Free", "Fast", "Browser tools"],
    metrics: [
      { label: "Purpose", value: "Daily utility" },
      { label: "Friction", value: "No signup" },
      { label: "Format", value: "Tool pages" },
    ],
    primaryAction: { label: "Browse tools", href: "/tools", variant: "primary" },
    searchPlaceholder: "Search tools, converters, generators…",
    sections: ["Featured", "Recent", "Daily use", "Developer", "Design"],
  },
  {
    id: "games",
    title: "Games",
    navLabel: "Games",
    href: "/games",
    eyebrow: "Play collection",
    description: "Lightweight browser games for quick breaks, classics, puzzles, and casual fun inside Darma.",
    status: "live",
    tone: "playful",
    accent: "violet",
    icon: Gamepad2,
    badges: ["No signup", "Browser-only", "Quick play"],
    metrics: [
      { label: "Games", value: "12", helper: "starter library" },
      { label: "Privacy", value: "Local only" },
      { label: "Best for", value: "Quick breaks" },
    ],
    primaryAction: { label: "Play games", href: "/games", variant: "primary" },
    secondaryAction: { label: "Surprise me", href: "/games/reaction-timer", variant: "secondary" },
    searchPlaceholder: "Search games, puzzles, classics…",
    sections: ["Continue", "Trending", "Brain", "Classics", "Touch friendly"],
  },
  {
    id: "templates",
    title: "Templates",
    navLabel: "Templates",
    href: "/templates",
    eyebrow: "Creation collection",
    description: "Ready-to-customize templates for posts, documents, presentations, briefs, and workflows.",
    status: "planned",
    tone: "creative",
    accent: "blue",
    icon: LayoutTemplate,
    badges: ["Planned", "Creative", "Reusable"],
    metrics: [
      { label: "Status", value: "Planned" },
      { label: "Focus", value: "Creation" },
      { label: "Format", value: "Reusable" },
    ],
    primaryAction: { label: "Coming soon", href: "/templates", variant: "secondary" },
    searchPlaceholder: "Search templates…",
    sections: ["Newest", "Social", "Business", "Education"],
  },
  {
    id: "components",
    title: "Components",
    navLabel: "Components",
    href: "/components",
    eyebrow: "UI collection",
    description: "Reusable UI components, patterns, snippets, and interaction examples for builders.",
    status: "planned",
    tone: "technical",
    accent: "teal",
    icon: Boxes,
    badges: ["Planned", "UI", "Open source"],
    metrics: [
      { label: "Status", value: "Planned" },
      { label: "Audience", value: "Builders" },
      { label: "Format", value: "Components" },
    ],
    primaryAction: { label: "Coming soon", href: "/components", variant: "secondary" },
    searchPlaceholder: "Search components…",
    sections: ["Inputs", "Cards", "Navigation", "Effects"],
  },
  {
    id: "ai",
    title: "AI",
    navLabel: "AI",
    href: "/ai",
    eyebrow: "AI collection",
    description: "Prompts, helpers, generators, and AI workflows for creators, students, and developers.",
    status: "planned",
    tone: "creative",
    accent: "emerald",
    icon: Bot,
    badges: ["Planned", "Prompts", "Workflows"],
    metrics: [
      { label: "Status", value: "Planned" },
      { label: "Focus", value: "AI helpers" },
      { label: "Use", value: "Daily" },
    ],
    primaryAction: { label: "Coming soon", href: "/ai", variant: "secondary" },
    searchPlaceholder: "Search AI prompts and helpers…",
    sections: ["Writing", "Design", "Learning", "Coding"],
  },
  {
    id: "resources",
    title: "Resources",
    navLabel: "Resources",
    href: "/resources",
    eyebrow: "Knowledge collection",
    description: "Guides, references, checklists, and curated links that help users learn and make faster decisions.",
    status: "planned",
    tone: "learning",
    accent: "amber",
    icon: LibraryBig,
    badges: ["Planned", "Guides", "References"],
    metrics: [
      { label: "Status", value: "Planned" },
      { label: "Focus", value: "Learning" },
      { label: "Format", value: "Guides" },
    ],
    primaryAction: { label: "Coming soon", href: "/resources", variant: "secondary" },
    searchPlaceholder: "Search resources…",
    sections: ["Guides", "References", "Checklists", "Examples"],
  },
  {
    id: "learning",
    title: "Learning",
    navLabel: "Learning",
    href: "/learning",
    eyebrow: "Study collection",
    description: "Simple learning paths, practice materials, explainers, and educational mini tools.",
    status: "planned",
    tone: "learning",
    accent: "rose",
    icon: GraduationCap,
    badges: ["Planned", "Study", "Practice"],
    metrics: [
      { label: "Status", value: "Planned" },
      { label: "Focus", value: "Practice" },
      { label: "Audience", value: "Learners" },
    ],
    primaryAction: { label: "Coming soon", href: "/learning", variant: "secondary" },
    searchPlaceholder: "Search learning paths…",
    sections: ["Practice", "Explain", "Review", "Mini lessons"],
  },
];

export function getCollectionById(id: CollectionId) {
  return COLLECTIONS.find((collection) => collection.id === id);
}

export function getLiveCollections() {
  return COLLECTIONS.filter((collection) => collection.status === "live");
}

export function getPlannedCollections() {
  return COLLECTIONS.filter((collection) => collection.status !== "live");
}
