import { encodeJwtSample } from "./jwt";
import type { JwtSampleDefinition } from "./types";

const minute = 60;
const hour = 60 * minute;
const day = 24 * hour;

export function getJwtSamples(nowSeconds = Math.floor(Date.now() / 1000)): JwtSampleDefinition[] {
  return [
    {
      id: "api-access",
      label: "API access token",
      category: "Common",
      description: "HS256-style access token with issuer, audience, role, and future expiration.",
      header: { alg: "HS256", typ: "JWT" },
      payload: {
        sub: "user_4821",
        name: "Darma Demo User",
        role: "developer",
        iss: "https://auth.example.com",
        aud: ["api", "dashboard"],
        iat: nowSeconds - 5 * minute,
        exp: nowSeconds + hour,
      },
    },
    {
      id: "expired",
      label: "Expired token",
      category: "Lifecycle",
      description: "A token whose exp claim passed 30 minutes ago.",
      header: { alg: "RS256", typ: "JWT", kid: "key-2026-01" },
      payload: {
        sub: "user_103",
        iss: "https://accounts.example.com",
        aud: "billing-api",
        iat: nowSeconds - 2 * hour,
        exp: nowSeconds - 30 * minute,
      },
    },
    {
      id: "not-yet-valid",
      label: "Future nbf token",
      category: "Lifecycle",
      description: "Shows a token that must not be accepted for another 15 minutes.",
      header: { alg: "ES256", typ: "JWT" },
      payload: {
        sub: "scheduled-job",
        scope: "reports:write",
        iat: nowSeconds,
        nbf: nowSeconds + 15 * minute,
        exp: nowSeconds + 2 * hour,
      },
    },
    {
      id: "unsigned",
      label: "Unsigned alg none",
      category: "Security",
      description: "Demonstrates why unsecured JWTs should be rejected by normal applications.",
      header: { alg: "none", typ: "JWT" },
      payload: { sub: "demo", admin: true, iat: nowSeconds, exp: nowSeconds + day },
      signature: "",
    },
    {
      id: "sensitive-payload",
      label: "Sensitive claims",
      category: "Privacy",
      description: "Highlights secrets and personal data that should not be placed in a readable JWT payload.",
      header: { alg: "HS256", typ: "JWT" },
      payload: {
        sub: "user_901",
        email: "person@example.com",
        apiKey: "demo-key-do-not-store-in-jwt",
        password: "demo-only",
        iat: nowSeconds,
        exp: nowSeconds + hour,
      },
    },
    {
      id: "oidc-id-token",
      label: "OIDC ID token",
      category: "Identity",
      description: "Identity-style claims including nonce, auth_time, azp, and email verification.",
      header: { alg: "RS256", typ: "JWT", kid: "oidc-signing-key" },
      payload: {
        iss: "https://identity.example.com",
        sub: "00u123example",
        aud: "web-client-id",
        azp: "web-client-id",
        nonce: "n-0S6_WzA2Mj",
        auth_time: nowSeconds - 10 * minute,
        iat: nowSeconds - 5 * minute,
        exp: nowSeconds + 55 * minute,
        email: "demo@example.com",
        email_verified: true,
      },
    },
    {
      id: "service-account",
      label: "Service account",
      category: "Machine identity",
      description: "Backend-to-backend token with service subject, scopes, audience, and short lifetime.",
      header: { alg: "RS256", typ: "JWT", kid: "svc-key-01" },
      payload: { sub: "service:billing-worker", iss: "https://auth.example.com", aud: "billing-api", scope: "invoices:read invoices:write", iat: nowSeconds, exp: nowSeconds + 20 * minute },
    },
    {
      id: "refresh-token-shape",
      label: "Refresh token claims",
      category: "Lifecycle",
      description: "Longer-lived token shape with jti and token_use metadata for lifecycle inspection.",
      header: { alg: "RS256", typ: "JWT" },
      payload: { sub: "user_4821", token_use: "refresh", jti: "refresh-demo-001", iat: nowSeconds - hour, exp: nowSeconds + 14 * day },
    },
    {
      id: "scoped-api-token",
      label: "Scoped API token",
      category: "Authorization",
      description: "Token with several OAuth-style scopes for permission review.",
      header: { alg: "ES256", typ: "JWT" },
      payload: { sub: "user_77", aud: "developer-api", scope: "projects:read deployments:write logs:read", iat: nowSeconds - minute, exp: nowSeconds + 45 * minute },
    },
    {
      id: "multi-audience",
      label: "Multiple audiences",
      category: "Authorization",
      description: "Shows an aud array shared across API, dashboard, and websocket services.",
      header: { alg: "RS256", typ: "JWT" },
      payload: { sub: "user_210", iss: "https://identity.example.com", aud: ["api", "dashboard", "realtime"], iat: nowSeconds, exp: nowSeconds + hour },
    },
    {
      id: "mobile-session",
      label: "Mobile session",
      category: "Common",
      description: "Mobile-app session token with device and session metadata.",
      header: { alg: "ES256", typ: "JWT", kid: "mobile-key-3" },
      payload: { sub: "user_310", aud: "mobile-app", session_id: "sess_demo_8f3", device: "android", iat: nowSeconds - 10 * minute, exp: nowSeconds + 50 * minute },
    },
    {
      id: "admin-role",
      label: "Admin role token",
      category: "Authorization",
      description: "Role-heavy token for checking authorization claims without treating them as proof of signature validity.",
      header: { alg: "RS256", typ: "JWT" },
      payload: { sub: "admin_14", roles: ["admin", "support"], permissions: ["users:read", "users:update"], iat: nowSeconds, exp: nowSeconds + 30 * minute },
    },
    {
      id: "missing-exp",
      label: "No expiration claim",
      category: "Security",
      description: "A token with iat but no exp so the security review can surface the missing lifetime boundary.",
      header: { alg: "HS256", typ: "JWT" },
      payload: { sub: "legacy-client", iss: "https://legacy.example.com", iat: nowSeconds - day },
    },
    {
      id: "future-issued-at",
      label: "Future issued-at",
      category: "Lifecycle",
      description: "Token whose iat is ahead of the current clock, useful for spotting clock-skew mistakes.",
      header: { alg: "RS256", typ: "JWT" },
      payload: { sub: "clock-skew-demo", iat: nowSeconds + 10 * minute, exp: nowSeconds + 70 * minute },
    },
    {
      id: "nested-custom-claims",
      label: "Nested custom claims",
      category: "Custom claims",
      description: "Payload with nested organisation and feature data for JSON structure inspection.",
      header: { alg: "ES256", typ: "JWT" },
      payload: { sub: "user_51", org: { id: "org_9", plan: "pro" }, features: { exports: true, seats: 12 }, iat: nowSeconds, exp: nowSeconds + hour },
    },
    {
      id: "minimal-token",
      label: "Minimal JWT",
      category: "Structure",
      description: "Small signed-token shape with only subject and timestamps for learning the three JWT segments.",
      header: { alg: "HS256", typ: "JWT" },
      payload: { sub: "demo", iat: nowSeconds, exp: nowSeconds + hour },
    },
  ];
}

export const DEFAULT_JWT = encodeJwtSample(getJwtSamples()[0]);

export const CLAIM_DESCRIPTIONS = [
  { claim: "iss", label: "Issuer", description: "Who issued the token." },
  { claim: "sub", label: "Subject", description: "Who or what the token is about." },
  { claim: "aud", label: "Audience", description: "The intended recipient or service." },
  { claim: "exp", label: "Expiration", description: "Unix time after which the token must be rejected." },
  { claim: "nbf", label: "Not before", description: "Unix time before which the token must be rejected." },
  { claim: "iat", label: "Issued at", description: "Unix time when the token was issued." },
  { claim: "jti", label: "JWT ID", description: "A unique identifier that can support replay protection." },
];
